### ISSUE TITLE
Error: Router not found for request /app-dist/setup.js

### ISSUE THREAD

**Issue by JaredWeatherby** [zadam/trilium#1004]
V 0.42.1

Error: Router not found for request /app-dist/setup.js
    at C:\Users\jared\Documents\trilium-master\src\app.js:84:17
    at Layer.handle [as handle_request] (C:\Users\jared\Documents\trilium-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\jared\Documents\trilium-master\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\jared\Documents\trilium-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\jared\Documents\trilium-master\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\jared\Documents\trilium-master\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle [as handle_request] (C:\Users\jared\Documents\trilium-master\node_modules\express\lib\router\layer.js:91:12)
    at trim_prefix (C:\Users\jared\Documents\trilium-master\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\jared\Documents\trilium-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\jared\Documents\trilium-master\node_modules\express\lib\router\index.js:335:12) {
  status: 404

**Comment by zadam** [comment]
Hello, what sort of installation is that. It kind of looks like a cloned git repo ... it would help to know what exactly you did.

**Comment by JaredWeatherby** [comment]
I downloaded the zip file, extracted to documents, installed node.js, tried to run as described in the wiki.

**Comment by zadam** [comment]
Oh, okay, you downloaded the auto generated github zip file - that's not a built version, just sources.

You need to download release from here: https://github.com/zadam/trilium/releases/tag/v0.42.1
