### ISSUE TITLE
Can't run trilium (electron) from source

### ISSUE THREAD

**Issue by jkurei** [zadam/trilium#1022]
I'm trying to run the last version of trilium from source, the electron app, and I'm getting this error:

```
→ npm run start-electron

> trilium@0.42.2 start-electron /Users/j/Desktop/trilium
> TRILIUM_ENV=dev electron .

App threw an error during load
Error: Cannot find module '/Users/j/Desktop/trilium/node_modules/sqlite3/lib/binding/electron-v9.0-darwin-x64/node_sqlite3.node'
Require stack:
- /Users/j/Desktop/trilium/node_modules/sqlite3/lib/sqlite3.js
- /Users/j/Desktop/trilium/src/services/sql_init.js
- /Users/j/Desktop/trilium/electron.js
- /Users/j/Desktop/trilium/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7735:16)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Module._load (electron/js2c/asar.js:738:28)
    at Function.Module._load (electron/js2c/asar.js:738:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/j/Desktop/trilium/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
```

I also tried to run older versions, going back a few months, and couldn't get it to work. Does it work for others from a clean _git clone_?

I've tried with node 10 and 12, by the way. I guess 12 is the right one, seeing that's the one used in the Docker file.

**Comment by jkurei** [comment]
This fixed it...

```
npm install electron-rebuild
./node_modules/.bin/electron-rebuild -w sqlite3 -p 
```

I hate technology sometimes.
