### ISSUE TITLE
Incorrect status code if server time is out of sync with desktop

### ISSUE THREAD

**Issue by SethCurry** [zadam/trilium#1056]
Version: 0.42.3

When the server and desktop time are not synchronized, Trilium will return a 400 error and the server logs:

```
POST /api/login/sync returned 400 with response {"message":"Auth request time is out of sync, please check that both client and server have correct time."}
```

Client logs look like:

```
Generated session secret
Generated sourceId=lDSlZH4yrdn0
App HTTP server starting up at port 37840
{
  "appVersion": "0.42.3",
  "dbVersion": 158,
  "syncVersion": 14,
  "buildDate": "2020-05-20T08:54:55+02:00",
  "buildRevision": "04c573e212db06e1dd60c74707e40f6912c85aab",
  "dataDirectory": "*obscured*",
  "clipperProtocolVersion": "1.0"
}
DB not initialized, please visit setup page
Getting document options from sync server.
Creating database for sync
Schema and not synced options generated.
Triggering sync.
sync failed: Request to POST https://notes.scurry.io/api/login/sync failed, error: 400 Bad RequestError: Request to POST https://*obscured*/api/login/sync failed, error: 400 Bad Request
    at generateError (C:\Users\scurry\trilium-windows-x64\resources\app.asar\src\services\request.js:170:12)
    at ClientRequest.<anonymous> (C:\Users\scurry\trilium-windows-x64\resources\app.asar\src\services\request.js:52:28)
    at ClientRequest.emit (events.js:223:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2561:12)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
```

I believe it should return a 403 (or maybe a 401) since the underlying issue is a problem with the authentication provided, rather than a problem with the request itself.

It's small and nitpicky, but I spent longer than I should have trying to pull request bodies thinking that my nginx proxy was mangling the request body for some reason.

**Comment by zadam** [comment]
Hi, thanks for bug report. Yes, it probably makes sense to return 401 here.
