### ISSUE TITLE
Unable To Build Trilium On Arm 32-bit Platforms

### ISSUE THREAD

**Issue by bonedaddy** [zadam/trilium#1057]
I'm attempting to compile a docker image for arm32v7 using the 0.42.3 release of trilium. This error happens both when trying to build trilium locally on my raspberry pi, as well as using docker. This is the error I get:

```
#7 112.0 node-pre-gyp WARN Using request for node-pre-gyp https download 
#7 113.0 node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.1/node-v64-linux-arm.tar.gz 
#7 113.0 node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.1.1 and node@10.20.1 (node-v64 ABI, musl) (falling back to source compile with node-gyp) 
#7 115.9 gyp ERR! find Python 
#7 115.9 gyp ERR! find Python Python is not set from command line or npm configuration
#7 115.9 gyp ERR! find Python Python is not set from environment variable PYTHON
#7 115.9 gyp ERR! find Python checking if "python" can be used
#7 115.9 gyp ERR! find Python - "python" is not in PATH or produced an error
#7 115.9 gyp ERR! find Python checking if "python2" can be used
#7 115.9 gyp ERR! find Python - "python2" is not in PATH or produced an error
#7 115.9 gyp ERR! find Python checking if "python3" can be used
#7 115.9 gyp ERR! find Python - "python3" is not in PATH or produced an error
#7 115.9 gyp ERR! find Python 
#7 115.9 gyp ERR! find Python **********************************************************
#7 115.9 gyp ERR! find Python You need to install the latest version of Python.
#7 115.9 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#7 115.9 gyp ERR! find Python you can try one of the following options:
#7 115.9 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#7 115.9 gyp ERR! find Python   (accepted by both node-gyp and npm)
#7 115.9 gyp ERR! find Python - Set the environment variable PYTHON
#7 115.9 gyp ERR! find Python - Set the npm configuration variable python:
#7 115.9 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#7 115.9 gyp ERR! find Python For more information consult the documentation at:
#7 115.9 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#7 115.9 gyp ERR! find Python **********************************************************
#7 115.9 gyp ERR! find Python 
#7 115.9 gyp ERR! configure error 
#7 115.9 gyp ERR! stack Error: Could not find any Python installation to use
#7 115.9 gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
#7 115.9 gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
#7 115.9 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
#7 115.9 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
#7 115.9 gyp ERR! stack     at exithandler (child_process.js:301:5)
#7 115.9 gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:313:5)
#7 115.9 gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
#7 115.9 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
#7 115.9 gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
#7 115.9 gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
#7 115.9 gyp ERR! System Linux 5.4.0-7629-generic
#7 115.9 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/trilium/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/trilium/node_modules/sqlite3/lib/binding/node-v64-linux-arm" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
#7 115.9 gyp ERR! cwd /trilium/node_modules/sqlite3
#7 115.9 gyp ERR! node -v v10.20.1
#7 115.9 gyp ERR! node-gyp -v v5.1.0
#7 115.9 gyp ERR! not ok 
#7 115.9 node-pre-gyp ERR! build error 
#7 115.9 node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/trilium/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/trilium/node_modules/sqlite3/lib/binding/node-v64-linux-arm --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
#7 115.9 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/trilium/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
#7 115.9 node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
#7 115.9 node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
#7 115.9 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
#7 115.9 node-pre-gyp ERR! System Linux 5.4.0-7629-generic
#7 115.9 node-pre-gyp ERR! command "/usr/local/bin/node" "/trilium/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#7 115.9 node-pre-gyp ERR! cwd /trilium/node_modules/sqlite3
#7 115.9 node-pre-gyp ERR! node -v v10.20.1
#7 115.9 node-pre-gyp ERR! node-pre-gyp -v v0.11.0
#7 115.9 node-pre-gyp ERR! not ok 
#7 115.9 Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/trilium/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node --module_name=node_sqlite3 --module_path=/trilium/node_modules/sqlite3/lib/binding/node-v64-linux-arm --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
#7 119.5 npm ERR! code ELIFECYCLE
#7 119.5 npm ERR! errno 1
#7 119.5 npm ERR! sqlite3@4.1.1 install: `node-pre-gyp install --fallback-to-build`
#7 119.5 npm ERR! Exit status 1
#7 119.5 npm ERR! 
#7 119.5 npm ERR! Failed at the sqlite3@4.1.1 install script.
#7 119.5 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#7 119.6 
#7 119.6 npm ERR! A complete log of this run can be found in:
#7 119.6 npm ERR!     /root/.npm/_logs/2020-05-29T21_58_32_097Z-debug.log
------
```

**Comment by zadam** [comment]
It's in the error message:

```
Could not find any Python installation to use
```

Just install python and try again (python is not necessary for running trilium, just for building sqlite binaries).

**Comment by bonedaddy** [comment]
that was it, thanks
