### ISSUE TITLE
api.getActiveTabTextEditor() failure

### ISSUE THREAD

**Issue by colingarbutt** [zadam/trilium#1087]
This is working ok for me in 0.40.6 but in 0.42.6 gives an error.
Console shows:

```
VM95:18 Console was cleared
VM95:23 editor:  Promise {<pending>}__proto__: Promise[[PromiseStatus]]: "rejected"[[PromiseValue]]: TypeError: t is not a function
    at editable-text.executeInActiveEditorEvent (http://127.0.0.1:37840/app-dist/desktop.js:1:182523)
    at async editable-text.callMethod (http://127.0.0.1:37840/app-dist/desktop.js:1:81832)
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async Promise.all (index 2)
    at async Promise.all (index 1)
    at async Promise.all (index 1)
editable_text.js:227 Uncaught (in promise) TypeError: t is not a function
    at editable-text.executeInActiveEditorEvent (editable_text.js:227)
    at async editable-text.callMethod (component.js:89)
    at async Promise.all (:37840/index 0)
    at async Promise.all (:37840/index 1)
    at async Promise.all (:37840/index 1)
    at async Promise.all (:37840/index 0)
    at async Promise.all (:37840/index 1)
    at async Promise.all (:37840/index 2)
    at async Promise.all (:37840/index 1)
    at async Promise.all (:37840/index 1)
executeInActiveEditorEvent @ desktop.js:1
```
My code:
```
api.addButtonToToolbar({
   title: 'Codecel',
   icon: 'check',
   shortcut: 'alt+n',
   action: async () => {
      console.clear();
      // all front end stuff
      //
      let note = api.getActiveTabNote();
      const editor = api.getActiveTabTextEditor();
      console.log("editor: ", editor);
/*
   my code
*/       
   }
});
```
Loving trilium
Colin.

**Comment by zadam** [comment]
Hi, 0.41 had big architectural changes and the API to get the textEditor instance had to change to callback:

```javascript
api.getActiveTabTextEditor().then(editor => {
	console.log("editor: ", editor);
});
```

API reference: https://zadam.github.io/trilium/frontend_api/FrontendScriptApi.html#getActiveTabTextEditor

**Comment by colingarbutt** [comment]
Thanks for the reply, but has something else changed?
This is still not working
```
api.addButtonToToolbar({
   title: 'test',
   icon: 'check',
   shortcut: 'alt+n',
   action: async () => {
      console.clear();

      api.getActiveTabTextEditor().then(editor => {
         console.log("editor: ", editor);
      });
   }
})

```

**Comment by zadam** [comment]
Sorry, I messed up a syntax, it's not promise based, but callback based, so:

```javascript
api.addButtonToToolbar({
   title: 'test',
   icon: 'check',
   shortcut: 'alt+n',
   action: async () => {
      console.clear();

      api.getActiveTabTextEditor(editor => {
         console.log("editor: ", editor.getData());
      });
   }
})
```

**Comment by colingarbutt** [comment]
Thanks.
