### ISSUE TITLE
[BUG] Custom Request Handlers

### ISSUE THREAD

**Issue by raytracer** [zadam/trilium#1125]
While playing with the idea of building my own custom Request handler I might have discovered a bug. Trying to call the custom handler via curl results in no response at all and the backend log produces the following entry: 

```
Error: No context available. ns.run() or ns.bind() must be called first.
    at Namespace.set (/usr/src/app/node_modules/cls-hooked/context.js:36:11)
    at Object.setEntityToCache (/usr/src/app/src/services/cls.js:57:22)
    at createEntityFromRow (/usr/src/app/src/entities/entity_constructor.js:37:13)
    at Array.map (<anonymous>)
    at Object.getEntities (/usr/src/app/src/services/repository.js:27:17)
    at async /usr/src/app/src/routes/custom.js:13:23
```

Version: 0.43.0-beta

**Comment by zadam** [comment]
Hello, thank you for reporting this issue, it has now been fixed.
