### ISSUE TITLE
SqliteError: no such table: entity_changes

### ISSUE THREAD

**Issue by millsoft** [zadam/trilium#1179]
Hi,
I just wanted to try trillium. I installed it on linux server (Ubuntu 20, 64 bit), did the `npm install` and after a while `npm start start-server`.
I opened the site in the browser and followed the installation instructions:

- :heavy_check_mark:  I'm a new user and I want to create new Trilium document for my notes
- clicked on "Finish Setup"

Log showed that the table entity_changes is not existent. See the log output:

```
npm run start-server
> trilium@0.43.3 start-server /home/michael/trilium
> cross-env TRILIUM_ENV=dev node ./src/www
DB not initialized, please visit setup page - http://[your-server-host]:[object Promise] to see instructions on how to initialize Trilium.
DB size: 4 KB
App HTTP server starting up at port 8080
{
"appVersion": "0.43.3",
"dbVersion": 163,
"syncVersion": 15,
"buildDate": "2020-07-31T23:34:05+02:00",
"buildRevision": "17d7ff3ff1bd50f272046864ca28e0ef407e24c9",
"dataDirectory": "/home/michael/.local/share/trilium-data",
"clipperProtocolVersion": "1.0"
}
CPU model: Intel Xeon Processor (Skylake, IBRS), logical cores: 2 freq: 2099 Mhz
Slow GET /setup took 16ms
Creating initial database ...
Slow POST /api/setup/new-document took 16ms
SqliteError: no such table: entity_changes
at stmt (/home/michael/trilium/src/services/sql.js:70:44)
at wrap (/home/michael/trilium/src/services/sql.js:197:25)
at execute (/home/michael/trilium/src/services/sql.js:163:12)
at insert (/home/michael/trilium/src/services/sql.js:32:17)
at Object.replace (/home/michael/trilium/src/services/sql.js:38:12)
at insertEntityChange (/home/michael/trilium/src/services/entity_changes.js:18:27)
at Object.addEntityChange (/home/michael/trilium/src/services/entity_changes.js:26:18)
at Function.<anonymous> (/home/michael/trilium/src/services/repository.js:122:34)
at Function.sqliteTransaction (/home/michael/trilium/node_modules/better-sqlite3/lib/transaction.js:58:24)
at Object.transactional (/home/michael/trilium/src/services/sql.js:214:48)
SqliteError: no such table: entity_changes
at stmt (/home/michael/trilium/src/services/sql.js:70:44)
at wrap (/home/michael/trilium/src/services/sql.js:197:25)
at execute (/following error showed up in the terminal where the server runs:
home/michael/trilium/src/services/sql.js:163:12)
at insert (/home/michael/trilium/src/services/sql.js:32:17)
at Object.replace (/home/michael/trilium/src/services/sql.js:38:12)
at insertEntityChange (/home/michael/trilium/src/services/entity_changes.js:18:27)
at Object.addEntityChange (/home/michael/trilium/src/services/entity_changes.js:26:18)
at Function.<anonymous> (/home/michael/trilium/src/services/repository.js:122:34)
at Function.sqliteTransaction (/home/michael/trilium/node_modules/better-sqlite3/lib/transaction.js:58:24)
at Object.transactional (/home/michael/trilium/src/services/sql.js:214:48)

```

**Comment by zadam** [comment]
Hi, thanks for hint, I fixed the issue. However note that master branch is used for development and it is quite unstable. It is recommended to use "stable" branch instead, or even better one of the available release builds.

**Comment by millsoft** [comment]
thanks! it works now. Ok, good to know, that master is used for development.

**Comment by Myzel394** [comment]
Unfortunately, this error currently occurs when you're manually setting up a server. Here's the error:

```
SqliteError: no such table: options
    at Database.prepare (/home/ubuntu/trilium/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at stmt (/home/ubuntu/trilium/src/services/sql.js:75:44)
    at wrap (/home/ubuntu/trilium/src/services/sql.js:208:23)
    at getRows (/home/ubuntu/trilium/src/services/sql.js:134:12)
    at Object.getRowOrNull (/home/ubuntu/trilium/src/services/sql.js:86:17)
    at getEntity (/home/ubuntu/trilium/src/services/repository.js:26:21)
    at Object.getOption (/home/ubuntu/trilium/src/services/repository.js:84:12)
    at Object.getOption (/home/ubuntu/trilium/src/services/options.js:2:44)
    at checkCredentials (/home/ubuntu/trilium/src/services/auth.js:85:38)
    at Layer.handle [as handle_request] (/home/ubuntu/trilium/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by zadam** [comment]
@Myzel394 which branch are you using?

**Comment by Myzel394** [comment]
[I'm following the docs](https://github.com/zadam/trilium/wiki/Manual-server-installation), which uses this command to get the latest stable release: `git clone -b stable https://github.com/zadam/trilium.git
`
