### ISSUE TITLE
New 0.44 search syntax - problems searching for "template" relation

### ISSUE THREAD

**Issue by wwwald** [zadam/trilium#1257]
I'm running the 0.44.3-beta release.

I have different note types in my journal, that link to different templates: `@template-snippet` for daily work snippets, `@template-meeting` for meeting notes, `@template-contact` for contact notes, `@template-note` for more general project notes.
All these notes also have a `project` label, that has the project name as value.

So a typical note would, for example, have these attributes: `#project=manhattan ~template=template-snippet`

Now - I want to find all "note" or "meeting" type notes for the "manhattan" project. In these cases, search sometimes errors out and I don't think the results are correct.

**Example 1:**  search string = `#project=manhattan`
→ this works
→ results as expected, all "manhattan" project snippets, meeting notes, project notes & contacts appear.

**Example 2:**  search string = `#project=manhattan ~template=template-meeting`
→ no error... "Search finished succesfully"
→ no errors reported in the backend log
→ BUT: search results are not correct

**Example 3:**  search string = `#project=manhattan ~template=template-note`
→ this gives me an error: "Search failed".
→ search results do not change from the previous search operation
→ backend log shows me the following error:
```
15:02:44.148 ERROR: get /api/search/:searchString threw exception: TypeError: Cannot read property 'token' of undefined
    at parseNoteProperty (E:\Dropbox\apps\trilium\resources\app.asar\src\services\search\services\parse.js:116:23)
    at getExpression (E:\Dropbox\apps\trilium\resources\app.asar\src\services\search\services\parse.js:366:30)
    at parse (E:\Dropbox\apps\trilium\resources\app.asar\src\services\search\services\parse.js:397:9)
    at parseQueryToExpression (E:\Dropbox\apps\trilium\resources\app.asar\src\services\search\services\search.js:57:24)
    at E:\Dropbox\apps\trilium\resources\app.asar\src\services\search\services\search.js:78:28
    at Object.stopWatch (E:\Dropbox\apps\trilium\resources\app.asar\src\services\utils.js:71:17)
    at findNotesWithQuery (E:\Dropbox\apps\trilium\resources\app.asar\src\services\search\services\search.js:77:18)
    at Object.searchTrimmedNotes (E:\Dropbox\apps\trilium\resources\app.asar\src\services\search\services\search.js:89:30)
    at searchNotes (E:\Dropbox\apps\trilium\resources\app.asar\src\routes\api\search.js:16:44)
    at Function.cb (E:\Dropbox\apps\trilium\resources\app.asar\src\routes\routes.js:94:34)
```

Is my search syntax for the "template" relation incorrect? Or is there something else going on?

**Comment by zadam** [comment]
Hi, there are two issues with your syntax:

*   relation is not a string value so such direct comparison is not possible, instead relation targets a note and it's necessary to more closely specify what you want to compare - in your case you need to specify `~template.title=MyTemplate`
*   `-` is a token separator, in such cases you need to surround your value with quotes - so final correct query would be `#project=manhattan ~template.title="template-meeting"`

However your attempts make sense and reveal lack of correct error handling for this case - errors should guide the user towards the correct syntax, so I will work on that.

**Comment by wwwald** [comment]
Ah, that clears up a lot. And works flawlessly!

Thanks a lot!
