### ISSUE TITLE
Ttrilium Server 0.43.4 Upgrade 0.44.* error

### ISSUE THREAD

**Issue by itplanes** [zadam/trilium#1271]
Ttrilium Server 0.43.4 Upgrade 0.44.* error.

```
CREATE TABLE IF NOT EXISTS "note_revisions_mig" (`noteRevisionId`       TEXT NOT NULL PRIMARY KEY,
                                             `noteId`   TEXT NOT NULL,
                                             `title`    TEXT,
                                             `isErased` INT NOT NULL DEFAULT 0,
                                             `isProtected`      INT NOT NULL DEFAULT 0,
                                             `utcDateLastEdited` TEXT NOT NULL,
                                             `utcDateCreated` TEXT NOT NULL,
                                             `utcDateModified` TEXT NOT NULL,
                                             `dateLastEdited` TEXT NOT NULL,
                                             `dateCreated` TEXT NOT NULL,
                                             type TEXT DEFAULT '' NOT NULL,
                                             mime TEXT DEFAULT '' NOT NULL,
                                             hash TEXT DEFAULT '' NOT NULL);

INSERT INTO note_revisions_mig (noteRevisionId, noteId, title, isErased, isProtected, utcDateLastEdited, utcDateCreated, utcDateModified, dateLastEdited, dateCreated, type, mime, hash)
SELECT noteRevisionId, noteId, title, isErased, isProtected, utcDateLastEdited, utcDateCreated, utcDateModified, dateLastEdited, dateCreated, type, mime, hash FROM note_revisions;

DROP TABLE note_revisions;
ALTER TABLE note_revisions_mig RENAME TO note_revisions;

CREATE INDEX `IDX_note_revisions_noteId` ON `note_revisions` (`noteId`);
CREATE INDEX `IDX_note_revisions_utcDateCreated` ON `note_revisions` (`utcDateCreated`);
CREATE INDEX `IDX_note_revisions_utcDateLastEdited` ON `note_revisions` (`utcDateLastEdited`);
CREATE INDEX `IDX_note_revisions_dateCreated` ON `note_revisions` (`dateCreated`);
CREATE INDEX `IDX_note_revisions_dateLastEdited` ON `note_revisions` (`dateLastEdited`);

Migration to version 165 has been successful.
Attempting migration to version 166
Migration with SQL script: CREATE TABLE IF NOT EXISTS "note_contents_mig" (
                                               `noteId` TEXT NOT NULL,
                                               `content`        TEXT NULL DEFAULT NULL,
                                               `hash` TEXT DEFAULT "" NOT NULL,
                                               `dateModified` TEXT NOT NULL,
                                               `utcDateModified` TEXT NOT NULL,
                                               PRIMARY KEY(`noteId`)
);

INSERT INTO note_contents_mig (noteId, content, hash, dateModified, utcDateModified)
    SELECT noteId,
           content,
           hash,
           (SELECT dateModified FROM notes WHERE noteId = note_contents.noteId),
           utcDateModified
    FROM note_contents;

DROP TABLE note_contents;

ALTER TABLE note_contents_mig RENAME TO note_contents;

ERROR: error during migration to version 166: SqliteError: NOT NULL constraint failed: note_contents_mig.dateModified
    at Object.executeScript (/opt/trilium-linux-x64-server/src/services/sql.js:195:25)
    at Function.<anonymous> (/opt/trilium-linux-x64-server/src/services/migration.js:52:25)
    at Function.sqliteTransaction (/opt/trilium-linux-x64-server/node_modules/better-sqlite3/lib/transaction.js:58:24)
    at Object.transactional (/opt/trilium-linux-x64-server/src/services/sql.js:230:48)
    at migrate (/opt/trilium-linux-x64-server/src/services/migration.js:46:17)
    at async Object.migrateIfNecessary (/opt/trilium-linux-x64-server/src/services/migration.js:105:9)
    at async initDbConnection (/opt/trilium-linux-x64-server/src/services/sql_init.js:39:5)
ERROR: migration failed, crashing hard
```

```
10:09:50.858 INFO  GET /api/clipper/handshake 
10:10:00.079 INFO  GET /api/clipper/handshake 
10:10:50.836 INFO  GET /api/clipper/handshake 
10:11:05.674 App db version is 170, while db version is 159. Migration needed.
10:11:05.678 DB size: 422162 KB
10:11:06.676 App HTTP server starting up at port 8506
10:11:06.676 {
  "appVersion": "0.44.4",
  "dbVersion": 170,
  "syncVersion": 16,
  "buildDate": "2020-09-24T23:33:36+02:00",
  "buildRevision": "748979eafd44704af42df54f4195d118dec891ae",
  "dataDirectory": "/opt/data/trilium-data",
  "clipperProtocolVersion": "1.0"
}
10:11:06.678 CPU model: Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz, logical cores: 1 freq: 2499 Mhz
10:11:06.694 Listening on port 8506
10:11:11.932 Created backup at /opt/data/trilium-data/backup/backup-before-migration.db
10:12:10.747 INFO  Generated sourceId=qOHNh2Lrniw6 
10:12:10.749 INFO  App HTTP server starting up at port 8506 
10:12:10.750 INFO  {
  "appVersion": "0.43.4",
  "dbVersion": 159,
  "syncVersion": 14,
  "buildDate": "2020-08-27T23:58:58+02:00",
  "buildRevision": "dc288fb18c7622f6e08c574888dc0e8c90e544c2",
  "dataDirectory": "/opt/data/trilium-data",
  "clipperProtocolVersion": "1.0"
} 
10:12:10.784 INFO  DB ready. 
10:12:10.821 INFO  DB size: 422162 KB 
10:12:30.788 INFO  Notes deleted: 288, not deleted 9748 
10:12:30.791 INFO  Note revisions deleted: 9, not deleted 673 
10:12:30.796 INFO  Branches deleted: 309, not deleted 9795 
10:12:30.805 INFO  Attributes deleted: 607, not deleted 19302 
10:12:30.806 INFO  API tokens deleted: 0, not deleted 3 
10:12:31.287 INFO  All consistency checks passed (took 501ms) 
```

**Comment by zadam** [comment]
Hello, I made the migration script more robust, please wait for 0.44.5 for the upgrade.
