### ISSUE TITLE
Sync fails

### ISSUE THREAD

**Issue by koutto** [zadam/trilium#1373]
Hi,
Syncing with my server fails. It gets stucked at "Sync in progress" page forever. 
My database is not very big, about 45MB
Here are the logs from clients:

```
15:10:04.100 GET /api/backend-log took 3ms
15:10:04.296 GET /api/backend-log took 6ms
15:10:05.393 GET /api/backend-log took 7ms
15:10:05.562 GET /api/backend-log took 5ms
15:10:05.741 GET /api/backend-log took 7ms
15:10:05.920 GET /api/backend-log took 3ms
15:10:21.504 sync failed: Process exceeded time limit 100000
stack: Error: Process exceeded time limit 100000
    at Object.timeLimit (/usr/lib/trilium/resources/app.asar/src/services/utils.js:249:19)
    at syncRequest (/usr/lib/trilium/resources/app.asar/src/services/sync.js:275:24)
    at pushChanges (/usr/lib/trilium/resources/app.asar/src/services/sync.js:215:15)
    at /usr/lib/trilium/resources/app.asar/src/services/sync.js:40:23
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.doExclusively (/usr/lib/trilium/resources/app.asar/src/services/sync_mutex.js:13:16)
    at async sync (/usr/lib/trilium/resources/app.asar/src/services/sync.js:30:16)
15:10:24.303 Slow query took 73ms: SELECT * FROM note_contents WHERE noteId = ?
15:10:40.784 GET /api/clipper/handshake took 7ms
15:11:21.873 Slow GET /api/backend-log took 14ms
15:11:40.757 GET /api/clipper/handshake took 2ms
15:12:04.770 sync failed: Process exceeded time limit 100000
stack: Error: Process exceeded time limit 100000
    at Object.timeLimit (/usr/lib/trilium/resources/app.asar/src/services/utils.js:249:19)
    at syncRequest (/usr/lib/trilium/resources/app.asar/src/services/sync.js:275:24)
    at pushChanges (/usr/lib/trilium/resources/app.asar/src/services/sync.js:215:15)
    at /usr/lib/trilium/resources/app.asar/src/services/sync.js:40:23
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.doExclusively (/usr/lib/trilium/resources/app.asar/src/services/sync_mutex.js:13:16)
    at async sync (/usr/lib/trilium/resources/app.asar/src/services/sync.js:30:16)
15:12:06.987 Slow query took 117ms: SELECT * FROM note_contents WHERE noteId = ?
15:12:40.787 Slow GET /api/clipper/handshake took 10ms
15:13:40.759 GET /api/clipper/handshake took 2ms
15:13:47.536 sync failed: Process exceeded time limit 100000
stack: Error: Process exceeded time limit 100000
    at Object.timeLimit (/usr/lib/trilium/resources/app.asar/src/services/utils.js:249:19)
    at syncRequest (/usr/lib/trilium/resources/app.asar/src/services/sync.js:275:24)
    at pushChanges (/usr/lib/trilium/resources/app.asar/src/services/sync.js:215:15)
    at /usr/lib/trilium/resources/app.asar/src/services/sync.js:40:23
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.doExclusively (/usr/lib/trilium/resources/app.asar/src/services/sync_mutex.js:13:16)
    at async sync (/usr/lib/trilium/resources/app.asar/src/services/sync.js:30:16)
15:13:49.105 Slow query took 61ms: SELECT * FROM note_contents WHERE noteId = ?
```

I have increase the timeout value, but with no success.
Do you have any idea where the problem comes from ?

Cheers

**Comment by gerroon** [comment]
I have the same issue now on my Windowx x64 box suddenly with 0.45.6  I have the same version on my Linux client but that one has no problem with the sync. 

`Sync failed: Process exceeded time limit 5000`

**Comment by zadam** [comment]
@gerroon this error is typically caused by something else - do you see some errors in the console when you press `CTRL+SHIFT+I`?

**Comment by gerroon** [comment]
I did not see any connection errors. I will try to investigate it.

**Comment by gerroon** [comment]
I am getting this again, here is some log


```
toast.js:75 22:01:43 error:  Sync failed: Process exceeded time limit 5000
toast.js:75 22:01:48 error:  Sync failed: Process exceeded time limit 5000
toast.js:75 22:03:52 error:  Sync failed: Process exceeded time limit 5000
toast.js:75 22:09:00 error:  Sync failed: Process exceeded time limit 5000
toast.js:75 22:09:05 error:  Sync failed: Process exceeded time limit 5000
:37840/#root/pFbQ8vW6536E/4Nk5Q0MnnwqK/evpLldGzBGpp/7Dnn2JIN93s4/I6vreAcGUiOl-R6IC:1 Refused to apply style from 'http://127.0.0.1:37840/api/notes/download/OfJIaJiuiVmL' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/libraries/bootstrap/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/libraries/fancytree/jquery.fancytree-all-deps.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/libraries/split.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/libraries/ckeditor/ckeditor.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/libraries/bootstrap/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
toast.js:75 22:10:03 error:  Sync failed: Process exceeded time limit 5000

```

**Comment by zadam** [comment]
First I would try to simply increase the timeout, maybe the network is just slow:

![image](https://user-images.githubusercontent.com/617641/119550015-22b68e00-bd98-11eb-8ab8-5e38d89089a2.png)
