### ISSUE TITLE
Sender API fails for some valid-seeming inputs.

### ISSUE THREAD

**Issue by elementc** [zadam/trilium#1397]
Reference:
https://github.com/zadam/trilium/blob/af41e5d115ce23e32006c5968a6c7bbe2c80ac90/src/routes/api/sender.js#L38-L42

While putting together the Android UI to apply a label to sent notes, I noticed the following error when sending a note with labels (copied from docker-compose logs):
```
trilium_1          | ERROR: Listener threw error: TypeError: Cannot read property 'toLowerCase' of undefined
trilium_1          |     at new Attribute (/usr/src/app/src/services/note_cache/entities/attribute.js:16:30)
trilium_1          |     at /usr/src/app/src/services/note_cache/note_cache_loader.js:135:26
trilium_1          |     at Object.emit (/usr/src/app/src/services/events.js:34:17)
trilium_1          |     at Function.<anonymous> (/usr/src/app/src/services/repository.js:134:30)
trilium_1          |     at Function.sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/transaction.js:58:24)
trilium_1          |     at Object.transactional (/usr/src/app/src/services/sql.js:230:48)
trilium_1          |     at Object.updateEntity (/usr/src/app/src/services/repository.js:114:9)
trilium_1          |     at Attribute.save (/usr/src/app/src/entities/entity.js:57:25)
trilium_1          |     at Note.setAttribute (/usr/src/app/src/entities/note.js:502:18)
trilium_1          |     at Note.setLabel (/usr/src/app/src/entities/note.js:672:41)
trilium_1          | POST /api/sender/note took 9ms
```
The body that I sent:
```
{"title":"my title","content":"my body","labels":[{"fromAndroid":""}]}
```

It's hard to tell from the log, but it seems that the empty string for the label value might be gettingturned into an undefined somewhere in flight?

Can confirm that sends without the "labels" component works fine.

Additionally, this causes desktop sync to break until I force a full sync:
```
trilium_1          | ERROR: get /api/sync/changed threw exception: Error: Entity attributes m0ipwXBhDlgD not found.
trilium_1          |     at getEntityChangeRow (/usr/src/app/src/services/sync.js:304:19)
trilium_1          |     at Object.getEntityChangesRecords (/usr/src/app/src/services/sync.js:324:24)
trilium_1          |     at getChanged (/usr/src/app/src/routes/api/sync.js:130:36)
trilium_1          |     at Function.cb (/usr/src/app/src/routes/routes.js:94:34)
trilium_1          |     at Function.sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/transaction.js:58:24)
trilium_1          |     at Object.transactional (/usr/src/app/src/services/sql.js:230:48)
trilium_1          |     at /usr/src/app/src/routes/routes.js:96:44
trilium_1          |     at /usr/src/app/node_modules/cls-hooked/context.js:118:13
trilium_1          |     at Namespace.run (/usr/src/app/node_modules/cls-hooked/context.js:97:5)
trilium_1          |     at Namespace.runAndReturn (/usr/src/app/node_modules/cls-hooked/context.js:117:8)
```

**Comment by zadam** [comment]
Hi, what you're sending is this:

```json
{
  "title": "my title",
  "content": "my body",
  "labels": [
    {
      "fromAndroid": ""
    }
  ]
}
```

but what is expected by the code is this:

```json
{
  "title": "my title",
  "content": "my body",
  "labels": [
    {
      "name": "fromAndroid",
      "value": ""
    }
  ]
}
```

**Comment by elementc** [comment]
Ah! My apologies, I misread the code. Thought the {} syntax grabbed
positionally, not by name. I'll try to update my pr one night this week!
Feel free to close.
