### ISSUE TITLE
Error running docker: Router not found

### ISSUE THREAD

**Issue by jbhanks** [zadam/trilium#1414]
When I pull and run the latest docker image (0.45.4), I get the following errors:

```
~ sudo docker run -t -i -p 127.0.0.1:8080:8080 -v ~/trilium-data:/root/trilium-data zadam/trilium:0.45-latest
DB size: 4 KB
DB not initialized, please visit setup page - http://[your-server-host]:8080 to see instructions on how to initialize Trilium.
App HTTP server starting up at port 8080
{
  "appVersion": "0.45.4",
  "dbVersion": 170,
  "syncVersion": 16,
  "buildDate": "2020-11-12T22:15:23+01:00",
  "buildRevision": "6c57b2220ff05059d7460369b195d281fcd9cbb6",
  "dataDirectory": "/root/trilium-data",
  "clipperProtocolVersion": "1.0"
}
CPU model: Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz, logical cores: 1 freq: 2294 Mhz
Listening on port 8080
Error: Router not found for request /test
    at /usr/src/app/src/app.js:69:17
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12) {
  status: 404
}

```

my nginx conf:
```
# HTTP — redirect all traffic to HTTPS
server {
    listen 80;
    listen [::]:80 ipv6only=on;
    root /var/www/html;
    index test_index.html;
    return 301 https://$host$request_uri;
}

server {
    # Enable HTTP/2
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name mydomain.com;
    include snippets/ssl-params.conf;
    location /test {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
    }
}
```

**Comment by zadam** [comment]
Can you provide more context? Are you upgrading or setting up a new installation?

Are you calling some `/test` request? Since that's the error in the logs and the request probably does not originate from trilium itself

**Comment by jbhanks** [comment]
It is a new installation. `/test` is just the name I gave the location in the nginx conf.

**Comment by zadam** [comment]
Ok, seems like a nginx config issue then. Not an expert, but maybe somebody else will be able to help.

**Comment by jbhanks** [comment]
A different container running on port 8080 was served as expected.

**Comment by Gnurfos** [comment]
Not sure from your last config quotes; but if that helps, for me changing from something like:

location /trilium/ {
    proxy_pass http://127.0.0.1:8080;

To:

location /trilium/ {
    proxy_pass http://127.0.0.1:8080/;

Fixed the (some?) "route not found issues". Note the added slash. See the [nginx doc](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass) for proxy_pass ("URI" vs "without a URI"):
