### ISSUE TITLE
Search results are empty

### ISSUE THREAD

**Issue by iSwiftLiu** [zadam/trilium#1437]
App version:	0.45.2
DB version:	170
Sync version:	16
Build date:	2020-10-29T22:57:25+01:00
Build revision:	4f75b6aaafef8144080fd17f403a605f61f5590d
![图片](https://user-images.githubusercontent.com/39252175/99634229-1533ea80-2a7b-11eb-9254-ec7c4e6e3bc1.png)

The search results of several recent versions are the same, whether it is on windows version, or server version access through domain name.

logs:
```
:20:15.731 Slow recursive query took 23ms.
15:20:15.762 Slow GET /api/tree?subTreeNoteId=CtNcXq3nam6t took 54ms
15:20:15.765 GET /api/notes/mtvKYUrueOl0 took 1ms
15:20:16.032 PUT /api/branches/WMS6Ke4TZV0d/expanded/1 took 2ms
15:20:16.521 Slow GET /api/similar-notes/CtNcXq3nam6t took 11ms
15:20:16.527 GET /api/notes/CtNcXq3nam6t/revisions took 1ms
15:20:16.529 POST /api/notes/CtNcXq3nam6t/link-map took 1ms
15:20:20.508 POST /api/recent-notes took 2ms
15:20:32.198 Search with query "03" took 3755ms
15:20:32.199 Slow GET /api/search/03?includeNoteContent=true&excludeArchived=true&fuzzyAttributeSearch=false took 3757ms
15:20:42.885 Slow query took 43ms: SELECT * FROM note_contents WHERE noteId = ?
15:20:48.021 sync failed: Process exceeded time limit 5000
stack: Error: Process exceeded time limit 5000
    at Object.timeLimit (D:\apps\trilium-windows\resources\app.asar\src\services\utils.js:249:19)
    at syncRequest (D:\apps\trilium-windows\resources\app.asar\src\services\sync.js:275:24)
    at pushChanges (D:\apps\trilium-windows\resources\app.asar\src\services\sync.js:215:15)
    at D:\apps\trilium-windows\resources\app.asar\src\services\sync.js:40:23
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.doExclusively (D:\apps\trilium-windows\resources\app.asar\src\services\sync_mutex.js:13:16)
    at async sync (D:\apps\trilium-windows\resources\app.asar\src\services\sync.js:30:16)
15:20:49.903 GET /api/clipper/handshake took 3ms
15:21:02.520 Search with query "03" took 4967ms
15:21:02.539 Slow GET /api/search/03?includeNoteContent=true&excludeArchived=true&fuzzyAttributeSearch=false took 4986ms
15:21:11.020 GET /api/notes/hzrQwLqiNHTx took 3ms
15:21:18.891 Search with query "03" took 4203ms
15:21:18.892 Slow GET /api/search/03?includeNoteContent=true&excludeArchived=true&fuzzyAttributeSearch=false took 4205ms
15:21:42.887 Slow query took 41ms: SELECT * FROM note_contents WHERE noteId = ?
15:21:48.029 sync failed: Process exceeded time limit 5000
stack: Error: Process exceeded time limit 5000
    at Object.timeLimit (D:\apps\trilium-windows\resources\app.asar\src\services\utils.js:249:19)
    at syncRequest (D:\apps\trilium-windows\resources\app.asar\src\services\sync.js:275:24)
    at pushChanges (D:\apps\trilium-windows\resources\app.asar\src\services\sync.js:215:15)
    at D:\apps\trilium-windows\resources\app.asar\src\services\sync.js:40:23
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.doExclusively (D:\apps\trilium-windows\resources\app.asar\src\services\sync_mutex.js:13:16)
    at async sync (D:\apps\trilium-windows\resources\app.asar\src\services\sync.js:30:16)
15:21:48.733 GET /api/notes/HEfR2GvfPXVf took 2ms
15:21:48.753 GET /api/notes/do4JaYH3fOii took 2ms
15:21:49.913 GET /api/clipper/handshake took 4ms
15:21:50.782 GET /api/app-info took 1ms
15:22:43.006 Slow query took 23ms: SELECT * FROM note_contents WHERE noteId = ?
15:22:48.196 sync failed: Process exceeded time limit 5000
stack: Error: Process exceeded time limit 5000
    at Object.timeLimit (D:\apps\trilium-windows\resources\app.asar\src\services\utils.js:249:19)
    at syncRequest (D:\apps\trilium-windows\resources\app.asar\src\services\sync.js:275:24)
    at pushChanges (D:\apps\trilium-windows\resources\app.asar\src\services\sync.js:215:15)
    at D:\apps\trilium-windows\resources\app.asar\src\services\sync.js:40:23
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.doExclusively (D:\apps\trilium-windows\resources\app.asar\src\services\sync_mutex.js:13:16)
    at async sync (D:\apps\trilium-windows\resources\app.asar\src\services\sync.js:30:16)
15:22:49.922 GET /api/clipper/handshake took 5ms
```

**Comment by zadam** [comment]
You seem to have some custom theme which I suspect hides the search results. This is how empty search results should look like:

![](https://user-images.githubusercontent.com/617641/99640728-983c4d00-2a49-11eb-94a6-ace405abb416.png)

**Comment by iSwiftLiu** [comment]
I changed to the default theme, still the same, I should not change the pre-installed theme
![image](https://user-images.githubusercontent.com/39252175/99666730-5261a200-2aa6-11eb-9fac-40b1daa9f705.png)

**Comment by zadam** [comment]
You must have some custom CSS since that's not how search box / results look like.

**Comment by iSwiftLiu** [comment]
Thank you very much, the search results can be displayed. I switched to the default theme and still can’t be displayed. I can search normally when I delete all other custom themes and adopt the default theme.
