### ISSUE TITLE
Sync server has source ID XXXXueo  which is also local

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#1667]
Hi

I am trying the new beta and I am getting these below. Anything concerning here?

server trilium-linux-x64-server-0.46.1-beta.tar.xz
client trilium_0.46.1-beta_amd64.deb

```
low 304 GET /api/sync/check took 365ms
200 GET /api/setup/status took 1ms
200 POST /api/login/sync took 1ms
sync failed: Sync server has source ID XXXXueo which is also local. Your sync setup is probably trying to connect to itself.
stack: Error: Sync server has source ID XXXXueo  which is also local. Your sync setup is probably trying to connect to itself.
    at doLogin (/opt/trillium_server/src/services/sync.js:104:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async login (/opt/trillium_server/src/services/sync.js:87:12)
    at async /opt/trillium_server/src/services/sync.js:35:37
    at async Object.doExclusively (/opt/trillium_server/src/services/sync_mutex.js:13:16)
    at async sync (/opt/trillium_server/src/services/sync.js:27:16)
Slow 304 GET /api/setup/status took 10ms
200 POST /api/login/sync took 2ms
304 GET /api/sync/changed?lastEntityChangeId=190068 took 1ms
204 POST /api/sync/finished took 1ms
Slow query took 295ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSynced = 1 AND entityName != 'note_reordering'
Content hash computation took 430ms
```

**Comment by zadam** [comment]
Hi, this happens when the sync client is (mis)configured to sync with itself - i.e. the URL to sync server actually points back to the sync client ... Or when sync server is trying to sync with itself (usually sync server should not have any sync server URL since it is itself the server).

Check what's in here on the instance where this error occurs:

![](https://user-images.githubusercontent.com/617641/108638629-6e535600-7490-11eb-9c6b-4410961ddb8d.png)
