### ISSUE TITLE
[Bug /api/login/token]

### ISSUE THREAD

**Issue by dislazy** [zadam/trilium#1705]
### server version
server version: 0.46-latest

### platform

uesd docker 

### error 
I used chrome application Trilium Web Clipper login my server is error :

12:16:57.646 Slow 500 POST /api/login/token took 53ms
12:20:56.241 ERROR: post /api/login/token threw exception: SqliteError: NOT NULL constraint failed: entity_changes.utcDateChanged
    at /usr/src/app/src/services/sql.js:167:31
    at wrap (/usr/src/app/src/services/sql.js:203:18)
    at execute (/usr/src/app/src/services/sql.js:167:12)
    at insert (/usr/src/app/src/services/sql.js:32:17)
    at Object.replace (/usr/src/app/src/services/sql.js:38:12)
    at insertEntityChange (/usr/src/app/src/services/entity_changes.js:20:27)
    at Object.addEntityChange (/usr/src/app/src/services/entity_changes.js:28:31)
    at Function.<anonymous> (/usr/src/app/src/services/repository.js:122:30)
    at Function.sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/transaction.js:58:24)
    at Object.transactional (/usr/src/app/src/services/sql.js:232:48)

**Comment by zadam** [comment]
Hi, thank you for reporting this issue, it's now fixed.
