### ISSUE TITLE
Underscore as thousand separator prevent starting trilium server on Raspberry Pi3 

### ISSUE THREAD

**Issue by TuxmAL** [zadam/trilium#1746]
Inside my RPi 3B+ with nodejs v10.24.0 I  cannot start Trilium  v 0.46.5 because of this error:
```
pi@home3:~$ /usr/bin/nodejs /var/www/nodejs/trilium/src/www
App db version is 183, while db version is 170. Migration needed.
DB size: 5398 KB
/var/www/nodejs/trilium/src/services/note_cache/entities/note.js:408
        let minDistance = 999_999;
                          ^^^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/www/nodejs/trilium/src/services/note_cache/note_cache_loader.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```  
After editing the `note.js` file and removing the underscore character all worked as usual.

[trilium-2021-03-15.log](https://github.com/zadam/trilium/files/6141071/trilium-2021-03-15.log)

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. Looks like a problem with nodejs 10 compatibility. Fixed.

**Comment by TuxmAL** [comment]
Thank you!
