### ISSUE TITLE
Failed upgrade from 45.8 (and 45.9) to 46.5 (manual install)

### ISSUE THREAD

**Issue by netnem** [zadam/trilium#1748]
[logs.txt](https://github.com/zadam/trilium/files/6143071/logs.txt)

root@trilium:# rm trilium -R
root@trilium:# git clone -b stable https://github.com/zadam/trilium.git
root@trilium:# cd trilium      
root@trilium:/trilium# npm install
root@trilium:/trilium# nohup node src/www
root@trilium:/trilium# cat nohup.out 
App db version is 183, while db version is 170. Migration needed.
DB size: 16162 KB
/root/trilium/src/services/note_cache/entities/note.js:408
        let minDistance = 999_999;
                          ^^^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/trilium/src/services/note_cache/note_cache_loader.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

I then did a rollback to 45.8, then upgraded to 45.9 without issues.  And 45.9 to 46.5 experienced the same issue.  

Running ubuntu 18.04.1 LTS

**Comment by netnem** [comment]
Related to #1746
