### ISSUE TITLE
Get error when I delete all revisions

### ISSUE THREAD

**Issue by JadeVane** [zadam/trilium#1774]
I use the lastest version of trilium, and when I want to delete all revisons, I get the error `sql is not defined`

log here:

```
DB size: 32260 KB
Note cache load took 67ms
App HTTP server starting up at port 8081
{
  "appVersion": "0.46.5",
  "dbVersion": 183,
  "syncVersion": 20,
  "buildDate": "2021-03-14T22:56:27+01:00",
  "buildRevision": "6c8d20288df302f3a415bd1bdcace98bf29d4bf6",
  "dataDirectory": "/var/www/trilium/data",
  "clipperProtocolVersion": "1.0"
}
CPU model: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz, logical cores: 2 freq: 2599 Mhz
Listening on port 8081
websocket client connected
Generated CSRF token y5Dqd3sm-IpCuLVZCemfyDqlJBZYffu_BaJQ with secret undefined
Slow 200 GET / took 35ms
websocket client connected
200 GET /api/notes/download/YRXWvYeYNZKi took 6ms
200 GET /api/notes/download/vfCRDuZkZ60X took 3ms
200 GET /api/notes/download/SA4plEGFl1xm took 1ms
200 GET /api/options took 3ms
200 GET /api/tree took 6ms
200 GET /api/keyboard-actions took 5ms
200 GET /api/keyboard-shortcuts-for-notes took 1ms
200 GET /api/script/widgets took 2ms
No handler matched for custom fonts/open-sans-v17-latin-regular.woff request.
No handler matched for custom fonts/open-sans-v17-latin-600.woff request.
200 GET /api/notes/SA4plEGFl1xm took 4ms
websocket client connected
200 GET /api/script/startup took 7ms
Slow 200 GET /api/similar-notes/SA4plEGFl1xm took 77ms
Slow query took 77ms: SELECT note_revisions.*, LENGTH(note_revision_contents.content) AS contentLength FROM note_revisions JOIN note_revision_contents ON note_revisions.noteRevisionId = note_revision_contents.noteRevisionId WHERE noteId = ? ORDER BY utcDateCreated DESC
Slow 200 GET /api/notes/SA4plEGFl1xm/revisions took 82ms
200 GET /api/notes/SA4plEGFl1xm took 4ms
200 POST /api/tree/load took 2ms
200 POST /api/tree/load took 2ms
200 GET /api/clipper/handshake took 2ms
200 POST /api/notes/SA4plEGFl1xm/link-map took 5ms
204 POST /api/recent-notes took 6ms
204 POST /api/recent-notes took 2ms
204 POST /api/recent-notes took 1ms
204 POST /api/recent-notes took 1ms
204 POST /api/recent-notes took 1ms
204 POST /api/recent-notes took 2ms
204 POST /api/recent-notes took 2ms
Table counts: notes: 582, note_revisions: 333, branches: 605, attributes: 1320, api_tokens: 2
Slow query took 98ms: SELECT noteId FROM notes JOIN note_contents USING (noteId) WHERE isDeleted = 0 AND isProtected = 0 AND content IS NULL
All consistency checks passed (took 146ms)
Slow query took 46ms: SELECT note_revisions.*, LENGTH(note_revision_contents.content) AS contentLength FROM note_revisions JOIN note_revision_contents ON note_revisions.noteRevisionId = note_revision_contents.noteRevisionId WHERE noteId = ? ORDER BY utcDateCreated DESC
Slow 200 GET /api/notes/SA4plEGFl1xm/revisions took 56ms
200 GET /api/notes/SA4plEGFl1xm/revisions/iynW0RhV3THa took 4ms
ERROR: delete /api/notes/:noteId/revisions threw exception: ReferenceError: sql is not defined
    at eraseAllNoteRevisions (/var/www/trilium/server/src/routes/api/note_revisions.js:83:36)
    at Function.cb (/var/www/trilium/server/src/routes/routes.js:96:34)
    at Function.sqliteTransaction (/var/www/trilium/server/node_modules/better-sqlite3/lib/transaction.js:58:24)
    at Object.transactional (/var/www/trilium/server/src/services/sql.js:234:52)
    at /var/www/trilium/server/src/routes/routes.js:98:44
    at /var/www/trilium/server/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/var/www/trilium/server/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/var/www/trilium/server/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/var/www/trilium/server/src/services/cls.js:5:22)
    at /var/www/trilium/server/src/routes/routes.js:90:32
500 DELETE /api/notes/SA4plEGFl1xm/revisions took 2ms
JS Error: Error when calling DELETE notes/SA4plEGFl1xm/revisions: error - 
Stack: Error
    at Object.logError (https://trilium.wenjinyu.me/app/services/ws.js:26:20)
    at Object.throwError (https://trilium.wenjinyu.me/app/services/toast.js:87:8)
    at reportError (https://trilium.wenjinyu.me/app/services/server.js:106:18)
    at async Object.error (https://trilium.wenjinyu.me/app/services/server.js:131:17)
```

**Comment by zadam** [comment]
Hi, thank you for reporting this issue. It's a bug, I have just fixed it. It will be in the next stable release.
