### ISSUE TITLE
`npm install` fails on master

### ISSUE THREAD

**Issue by Reinmar** [zadam/trilium#179]
Hi! `npm i` fails on 22e905a (latest `master`). 

I'm on macOS 10.13.5, Node v8.11.3, npm v6.4.0.

Running `npm i` on `trilium@v0.21.0` worked fine.

Error logs:

```
(master 22e905a) p@m /workspace/stuff/trilium> npm i
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

> @mlink/scrypt@6.1.2 preinstall /workspace/stuff/trilium/node_modules/@mlink/scrypt
> node node-scrypt-preinstall.js

Error: Error: Command failed: ./configure
configure: error: function AES_ENCRYPT not found


> sqlite3@4.0.2 install /workspace/stuff/trilium/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "/workspace/stuff/trilium/node_modules/sqlite3/lib/binding/node-v57-darwin-x64/node_sqlite3.node" is installed via remote

> @mlink/scrypt@6.1.2 install /workspace/stuff/trilium/node_modules/@mlink/scrypt
> node-gyp rebuild

  SOLINK_MODULE(target) Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  LIBTOOL-STATIC Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.1/lib/crypto/crypto_scrypt.o
In file included from ../scrypt/scrypt-1.2.1/lib/crypto/crypto_scrypt.c:29:
../scrypt/scrypt-1.2.1/scrypt_platform.h:7:10: fatal error: 'config.h' file not found
#include "config.h"
         ^
1 error generated.
make: *** [Release/obj.target/scrypt_lib/scrypt/scrypt-1.2.1/lib/crypto/crypto_scrypt.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /workspace/stuff/trilium/node_modules/@mlink/scrypt
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @mlink/scrypt@6.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @mlink/scrypt@6.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p/.npm/_logs/2018-09-07T10_24_56_479Z-debug.log
```

**Comment by zadam** [comment]
Hello, I only recently noticed the issue - if you build trilium youself, you need to have openssl-dev installed on the host system (in ubuntu package name is "libssl-dev").

**Comment by popey456963** [comment]
Closed as over a year old.
