### ISSUE TITLE
Recent changes to syncing/sync widget (392a00ac179dd61b28d98b85a0fb626471ff5d9e) break the web server for new installs

### ISSUE THREAD

**Issue by bavis-m** [zadam/trilium#1796]
Trilium version: a25419974699a4be10c9d63083931869a47d44cd

Change 392a00ac179dd61b28d98b85a0fb626471ff5d9e introduces a bare call to `getLastSyncedPush` at the top level of `src/services/sync.js` in order to get the latest synced/acknowledged update (I'm guessing). If you are starting the Trilium server for the first time the db doesn't contain any tables (schema hasn't been setup yet) and this causes an immediate crash. I believe a suitable fix would just be to check `sqlinit.isDbInitialized()` before making that call, if the database isn't initialized there have been no sync pushes so the default value of `lastSyncedPush` should be correct (from a 5 minute glance at the code).

Log output:
```
Debugger listening on ws://127.0.0.1:9229/e8647b32-f289-4bcd-b3ff-adfc71d2dd53
For help, see: https://nodejs.org/en/docs/inspector
Generated session secret
DB size: 4 KB

/c/Projects/trilium/src/services/sql.js:215
        throw e;
        ^
SqliteError: no such table: options
    at stmt (/c/Projects/trilium/src/services/sql.js:71:44)
    at wrap (/c/Projects/trilium/src/services/sql.js:204:23)
    at getRows (/c/Projects/trilium/src/services/sql.js:130:12)
    at Object.getRowOrNull (/c/Projects/trilium/src/services/sql.js:82:17)
    at getEntity (/c/Projects/trilium/src/services/repository.js:26:21)
    at Object.getOption (/c/Projects/trilium/src/services/repository.js:84:12)
    at Object.getOption (/c/Projects/trilium/src/services/options.js:2:44)
    at getLastSyncedPush (/c/Projects/trilium/src/services/sync.js:366:51)
    at Object.<anonymous> (/c/Projects/trilium/src/services/sync.js:395:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
```

**Comment by zadam** [comment]
Hi, thanks for the report and MR. I assume this is now fixed so I'll close this issue.
