### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mopsicus** [zadam/trilium#1805]
Smth went wrong and now I can't load my notes at all. Got error:

> Error when calling GET tree: error - Internal Server Error

Last log messages:
> 13:23:38.395 204 POST /api/recent-notes took 8ms
13:23:39.973 304 GET /api/attributes/names/?type=relation&query=template took 2ms
13:23:40.158 200 GET /api/attributes/names/?type=relation&query=templat took 2ms
13:23:40.345 200 GET /api/attributes/names/?type=relation&query=templa took 1ms
13:23:40.518 200 GET /api/attributes/names/?type=relation&query=templ took 2ms
13:23:40.667 200 GET /api/attributes/names/?type=relation&query=temp took 2ms
13:23:40.916 304 GET /api/attributes/names/?type=relation&query=te took 3ms
13:23:41.089 304 GET /api/attributes/names/?type=relation&query=t took 3ms
13:23:41.220 200 GET /api/attributes/names/?type=relation&query= took 1ms
13:23:43.217 ERROR: Listener threw error: RangeError: Maximum call stack size exceeded
    at Array.values (<anonymous>)
    at Note.invalidateSubtreeCaches (/opt/trilium/src/services/note_cache/entities/note.js:240:38)
    at Note.invalidateSubtreeCaches (/opt/trilium/src/services/note_cache/entities/note.js:241:23)
    at Note.invalidateSubtreeCaches (/opt/trilium/src/services/note_cache/entities/note.js:249:26)
    at Note.invalidateSubtreeCaches (/opt/trilium/src/services/note_cache/entities/note.js:241:23)
    at Note.invalidateSubtreeCaches (/opt/trilium/src/services/note_cache/entities/note.js:249:26)
    at Note.invalidateSubtreeCaches (/opt/trilium/src/services/note_cache/entities/note.js:241:23)
    at Note.invalidateSubtreeCaches (/opt/trilium/src/services/note_cache/entities/note.js:249:26)
    at Note.invalidateSubtreeCaches (/opt/trilium/src/services/note_cache/entities/note.js:241:23)
    at Note.invalidateSubtreeCaches (/opt/trilium/src/services/note_cache/entities/note.js:249:26)
13:23:43.219 Slow 204 PUT /api/notes/KVex0vrz61zN/attributes took 17ms
13:23:43.223 204 PUT /api/notes/KVex0vrz61zN/attributes took 1ms
13:23:43.333 304 GET /api/tree?subTreeNoteId=KVex0vrz61zN took 2ms
13:23:43.338 304 GET /api/notes/KVex0vrz61zN took 2ms
13:23:44.341 200 POST /api/notes/KVex0vrz61zN/link-map took 3ms
13:23:45.854 204 PUT /api/branches/Q9sIHhmmloJ4/expanded/1 took 1ms
13:23:47.795 304 GET /api/notes/nkInFs8UjruI took 1ms
13:23:47.798 204 PUT /api/options took 2ms
13:23:48.783 Slow 200 GET /api/similar-notes/nkInFs8UjruI took 16ms
13:23:48.788 200 GET /api/notes/nkInFs8UjruI/revisions took 0ms
13:23:48.793 200 POST /api/notes/nkInFs8UjruI/link-map took 1ms
13:23:52.765 204 POST /api/recent-notes took 1ms
13:23:53.401 Sending message to all clients: {"type":"task-progress-count","taskId":"LBzETI2qEb","taskType":"delete-notes","progressCount":0}
13:23:53.404 Deleting note nkInFs8UjruI
13:23:53.405 Sending message to all clients: {"type":"task-succeeded","taskId":"LBzETI2qEb","taskType":"delete-notes"}
13:23:53.407 200 DELETE /api/branches/y56sRGObdENe?taskId=LBzETI2qEb&last=true took 7ms
13:23:53.622 204 PUT /api/options took 3ms
13:23:53.630 200 GET /api/notes/nkInFs8UjruI took 1ms
13:23:53.634 200 GET /api/autocomplete?query=&activeNoteId=null took 2ms
13:23:53.701 304 GET /api/notes/KVex0vrz61zN took 2ms
13:23:54.553 204 PUT /api/options took 2ms
13:23:54.603 Slow 200 GET /api/similar-notes/KVex0vrz61zN took 17ms
13:23:54.608 304 GET /api/notes/KVex0vrz61zN/revisions took 1ms
13:23:54.610 200 POST /api/notes/KVex0vrz61zN/link-map took 1ms
13:23:57.440 304 GET /api/attributes/names/?type=relation&query=template took 2ms
13:23:58.582 204 POST /api/recent-notes took 2ms
13:23:59.148 304 GET /api/attributes/names/?type=relation&query=template took 2ms
13:24:02.713 304 GET /api/attributes/names/?type=relation&query=template took 2ms
13:24:02.887 304 GET /api/attributes/names/?type=relation&query=templat took 2ms
13:24:03.798 304 GET /api/attributes/names/?type=relation&query=template took 6ms
13:24:09.293 204 PUT /api/notes/KVex0vrz61zN/attributes took 2ms
13:24:10.687 304 GET /api/attributes/names/?type=relation&query=myRelation took 1ms
13:24:10.690 200 POST /api/search-related took 2ms
13:24:10.692 304 GET /api/attributes/names/?type=relation&query=template took 1ms
13:24:12.292 200 POST /api/search-related took 3ms
13:24:13.804 304 GET /api/autocomplete?query=%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%20%D1%81%D0%BE%D0%B8%D1%81%D0%BA%D0%B0%D1%82%D0%B5%D0%BB%D1%8F&activeNoteId=KVex0vrz61zN took 3ms
13:24:16.394 ERROR: post /api/search-related threw exception: TypeError: Cannot read property 'noteId' of undefined
    at /opt/trilium/src/services/search/note_set.js:7:57
    at Array.map (<anonymous>)
    at new NoteSet (/opt/trilium/src/services/search/note_set.js:7:40)
    at RelationWhereExp.execute (/opt/trilium/src/services/search/expressions/relation_where.js:22:41)
    at AndExp.execute (/opt/trilium/src/services/search/expressions/and.js:23:42)
    at findNotesWithExpression (/opt/trilium/src/services/search/services/search.js:87:32)
    at Object.findNotesWithQuery (/opt/trilium/src/services/search/services/search.js:154:12)
    at getRelatedNotes (/opt/trilium/src/routes/api/search.js:231:48)
    at Function.cb (/opt/trilium/src/routes/routes.js:96:34)
    at Function.sqliteTransaction (/opt/trilium/node_modules/better-sqlite3/lib/transaction.js:58:24)
13:24:16.395 500 POST /api/search-related took 2ms
13:24:16.397 304 GET /api/autocomplete?query=%D0%A8%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%20%D1%81%D0%BE%D0%B8%D1%81%D0%BA%D0%B0%D1%82%D0%B5%D0%BB%D1%8F&activeNoteId=KVex0vrz61zN took 1ms
13:24:16.478 JS Error: Error when calling POST search-related: error - Internal Server Error
Stack: Error
    at Object.logError (https://docs.angrym.com/app/services/ws.js:26:20)
    at Object.throwError (https://docs.angrym.com/app/services/toast.js:87:8)
    at reportError (https://docs.angrym.com/app/services/server.js:106:18)
    at async Object.error (https://docs.angrym.com/app/services/server.js:131:17)
13:24:19.830 204 PUT /api/notes/KVex0vrz61zN/attributes took 4ms
13:24:19.916 304 GET /api/notes/KVex0vrz61zN took 2ms
13:24:19.927 ERROR: get /api/tree threw exception: TypeError: Cannot read property 'noteId' of undefined
    at collectEntityIds (/opt/trilium/src/routes/api/tree.js:13:39)
    at collectEntityIds (/opt/trilium/src/routes/api/tree.js:35:17)
    at getNotesAndBranchesAndAttributes (/opt/trilium/src/routes/api/tree.js:47:9)
    at getTree (/opt/trilium/src/routes/api/tree.js:144:12)
    at Function.cb (/opt/trilium/src/routes/routes.js:96:34)
    at Function.sqliteTransaction (/opt/trilium/node_modules/better-sqlite3/lib/transaction.js:58:24)
    at Object.transactional (/opt/trilium/src/services/sql.js:234:52)
    at /opt/trilium/src/routes/routes.js:98:44
    at /opt/trilium/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/opt/trilium/node_modules/cls-hooked/context.js:97:5)
13:24:19.928 500 GET /api/tree?subTreeNoteId=KVex0vrz61zN took 2ms
13:24:19.929 304 GET /api/attributes/values/city took 1ms
13:24:20.037 JS Error: Error when calling GET tree?subTreeNoteId=KVex0vrz61zN: error - Internal Server Error
Stack: Error
    at Object.logError (https://docs.angrym.com/app/services/ws.js:26:20)
    at Object.throwError (https://docs.angrym.com/app/services/toast.js:87:8)
    at reportError (https://docs.angrym.com/app/services/server.js:106:18)
    at async Object.error (https://docs.angrym.com/app/services/server.js:131:17)

Seem it's caused when I deleted some note or template, maybe...
So, how I can fix it and restore my notes??

**Comment by mopsicus** [comment]
I've fixed it by myself. Downloaded db and removed all entries where id = KVex0vrz61zN

**Comment by zadam** [comment]
Hi, thanks for reporting this issue.

Looks like the template relations were used in a way which caused an infinite cycle ("instance" note is an ancestor of "template" note). I added checks to prevent this from happening in the future.
