### ISSUE TITLE
Error when import zip file

### ISSUE THREAD

**Issue by aihuasxy** [zadam/trilium#1808]
verison：
"appVersion": "0.46.6"

error log:
11:10:10.979 Sending message to all clients: {"type":"task-progress-count","taskId":"OqMcNeOUFO","taskType":"import","data":{"safeImport":false,"shrinkImages":false,"textImportedAsText":false,"codeImportedAsCode":false,"explodeArchives":true,"replaceUnderscoresWithSpaces":false},"progressCount":0}
11:10:10.982 200 POST /api/notes/6gaZ26hvhXMW/import took 4ms
11:10:11.005 Sending message to all clients: {"type":"task-error","taskId":"OqMcNeOUFO","taskType":"import","data":{"safeImport":false,"shrinkImages":false,"textImportedAsText":false,"codeImportedAsCode":false,"explodeArchives":true,"replaceUnderscoresWithSpaces":false},"message":"Import failed with following error: 'Cannot set property 'notePosition' of undefined'. More details might be in the logs."}
11:10:11.007 ERROR: Import failed with following error: 'Cannot set property 'notePosition' of undefined'. More details might be in the logs.TypeError: Cannot set property 'notePosition' of undefined
    at Function.<anonymous> (D:\tool\trilium-windows-x64\resources\app.asar\src\services\tree.js:142:60)
    at Function.sqliteTransaction (D:\tool\trilium-windows-x64\resources\app.asar\node_modules\better-sqlite3\lib\transaction.js:58:24)
    at Object.transactional (D:\tool\trilium-windows-x64\resources\app.asar\src\services\sql.js:234:52)
    at Object.sortNotesByTitle (D:\tool\trilium-windows-x64\resources\app.asar\src\services\tree.js:110:9)
    at Object.importZip (D:\tool\trilium-windows-x64\resources\app.asar\src\services\import\zip.js:466:25)
    at async importToBranch (D:\tool\trilium-windows-x64\resources\app.asar\src\routes\api\import.js:54:20)
11:10:11.008 POST /api/notes/6gaZ26hvhXMW/import returned 500 with response "Import failed with following error: 'Cannot set property 'notePosition' of undefined'. More details might be in the logs."

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. Is it reproducible? Meaning, if you try the same ZIP, does the error occur again?

I added a defensive check for this situation so this should be handled in the future, but it would be good to figure out where does this error come from ...

**Comment by aihuasxy** [comment]
> Hi, thanks for reporting this issue. Is it reproducible? Meaning, if you try the same ZIP, does the error occur again?
> 
> I added a defensive check for this situation so this should be handled in the future, but it would be good to figure out where does this error come from ...

Yes, it is reproducible.

I want to find the problem .
Must I debug code or just by log?

in this code: 
note.branchId in noteCache.branches
I can't not find noteCache in log file and not konw how to determine if  noteCache is OK

**Comment by aihuasxy** [comment]
update:
After reboot trilium the imported files will be appeared.

**Comment by zadam** [comment]
Only Unicode is supported as encoding so I would advise to convert files to that first.

**Comment by aihuasxy** [comment]
> Only Unicode is supported as encoding so I would advise to convert files to that first.

Not encoding of file, but the default file name encoding in win10 chinese is gkb.
Maybe should be transcoded from gbk to unicode when creating note.
I will try to fix this problem.

**Comment by andrews89** [comment]
Just seconding the primary bug behavior - dragging a .zip file into the tree view will show the same error and log message:

`05:14:43.736 ERROR: Import failed with following error: 'Cannot set property 'notePosition' of undefined'. More details might be in the logs.TypeError: Cannot set property 'notePosition' of undefined
    at Function.<anonymous> (/usr/src/app/src/services/tree.js:142:60)
    at Function.sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/transaction.js:58:24)
    at Object.transactional (/usr/src/app/src/services/sql.js:234:52)
    at Object.sortNotesByTitle (/usr/src/app/src/services/tree.js:110:9)
    at Object.importZip (/usr/src/app/src/services/import/zip.js:466:25)
    at async importToBranch (/usr/src/app/src/routes/api/import.js:54:20)
05:14:43.737 POST /api/notes/CHCXaSE7xZUp/import returned 500 with response "Import failed with following error: 'Cannot set property 'notePosition' of undefined'. More details might be in the logs."`

A restart of the Trilium container made all three of my attempts appear (and at the correct places in the hierarchy).  Didn't expect the file to be unzipped, but a nice bonus since it was a git repo.

**Comment by xuxanwan** [comment]
> update:
> After reboot trilium the imported files appeared.
> 
> another problem is, the imorted file names with gbk codec becomes garbled
> 
> ![image](https://user-images.githubusercontent.com/6761242/113241774-ec054f80-92e1-11eb-8900-ee29b01b77f9.png)

You can use Bandzip to zip folders.
![截图_20213825113840](https://user-images.githubusercontent.com/5035496/119527428-e47a9800-bdb2-11eb-83ad-c8d19392bda0.png)
