### ISSUE TITLE
Internal server error on delete

### ISSUE THREAD

**Issue by mopsicus** [zadam/trilium#1814]
First I've tried to move note to protected tree, and got fail. After that I've tried to delete note and create new in protected notes, but got fail on delete.

`
Error when calling DELETE branches/7Hzb2SVoyxJu?taskId=WAlgfbnfJt&last=true: error - Internal Server Error
`

Last log

> 0:29:31.540 Slow 200 GET /api/similar-notes/mNijU1YgxJRK took 16ms
20:29:31.542 304 GET /api/notes/mNijU1YgxJRK/revisions took 1ms
20:29:32.210 ERROR: put /api/branches/:branchId/move-after/:afterBranchId threw exception: SqliteError: database disk image is malformed
    at Statement.all (<anonymous>)
    at /opt/trilium/src/services/sql.js:130:31
    at wrap (/opt/trilium/src/services/sql.js:204:18)
    at getRows (/opt/trilium/src/services/sql.js:130:12)
    at Object.getColumn (/opt/trilium/src/services/sql.js:152:20)
    at loadSubtreeNoteIds (/opt/trilium/src/services/tree.js:102:26)
    at checkTreeCycle (/opt/trilium/src/services/tree.js:72:5)
    at Object.validateParentChild (/opt/trilium/src/services/tree.js:51:10)
    at moveBranchAfterNote (/opt/trilium/src/routes/api/branches.js:101:42)
    at Function.cb (/opt/trilium/src/routes/routes.js:96:34)
20:29:32.210 500 PUT /api/branches/7Hzb2SVoyxJu/move-after/eemYjFonBIdr took 1ms
20:29:32.751 JS Error: Error when calling PUT branches/7Hzb2SVoyxJu/move-after/eemYjFonBIdr: error - Internal Server Error
Stack: Error
    at Object.logError (https://docs.angrym.com/app/services/ws.js:26:20)
    at Object.throwError (https://docs.angrym.com/app/services/toast.js:87:8)
    at reportError (https://docs.angrym.com/app/services/server.js:106:18)
    at async Object.error (https://docs.angrym.com/app/services/server.js:131:17)
20:29:33.415 204 POST /api/recent-notes took 2ms
20:29:35.529 204 POST /api/recent-notes took 2ms
20:29:46.363 Sending message to all clients: {"type":"task-progress-count","taskId":"N52Rp8hQJK","taskType":"delete-notes","progressCount":0}
20:29:46.365 ERROR: delete /api/branches/:branchId threw exception: SqliteError: database disk image is malformed
    at Statement.all (<anonymous>)
    at /opt/trilium/src/services/sql.js:130:31
    at wrap (/opt/trilium/src/services/sql.js:204:18)
    at Object.getRows (/opt/trilium/src/services/sql.js:130:12)
    at Object.getEntities (/opt/trilium/src/services/repository.js:20:22)
    at Note.getChildBranches (/opt/trilium/src/entities/note.js:836:32)
    at Object.deleteBranch (/opt/trilium/src/services/notes.js:545:40)
    at deleteBranch (/opt/trilium/src/routes/api/branches.js:187:37)
    at Function.cb (/opt/trilium/src/routes/routes.js:96:34)
    at Function.sqliteTransaction (/opt/trilium/node_modules/better-sqlite3/lib/transaction.js:58:24)
20:29:46.366 500 DELETE /api/branches/7Hzb2SVoyxJu?taskId=N52Rp8hQJK&last=true took 3ms
20:29:46.449 JS Error: Error when calling DELETE branches/7Hzb2SVoyxJu?taskId=N52Rp8hQJK&last=true: error - Internal Server Error
Stack: Error
    at Object.logError (https://docs.angrym.com/app/services/ws.js:26:20)
    at Object.throwError (https://docs.angrym.com/app/services/toast.js:87:8)
    at reportError (https://docs.angrym.com/app/services/server.js:106:18)
    at async Object.error (https://docs.angrym.com/app/services/server.js:131:17)
20:30:09.351 Sending message to all clients: {"type":"task-progress-count","taskId":"WAlgfbnfJt","taskType":"delete-notes","progressCount":0}
20:30:09.352 ERROR: delete /api/branches/:branchId threw exception: SqliteError: database disk image is malformed
    at Statement.all (<anonymous>)
    at /opt/trilium/src/services/sql.js:130:31
    at wrap (/opt/trilium/src/services/sql.js:204:18)
    at Object.getRows (/opt/trilium/src/services/sql.js:130:12)
    at Object.getEntities (/opt/trilium/src/services/repository.js:20:22)
    at Note.getChildBranches (/opt/trilium/src/entities/note.js:836:32)
    at Object.deleteBranch (/opt/trilium/src/services/notes.js:545:40)
    at deleteBranch (/opt/trilium/src/routes/api/branches.js:187:37)
    at Function.cb (/opt/trilium/src/routes/routes.js:96:34)
    at Function.sqliteTransaction (/opt/trilium/node_modules/better-sqlite3/lib/transaction.js:58:24)
20:30:09.353 500 DELETE /api/branches/7Hzb2SVoyxJu?taskId=WAlgfbnfJt&last=true took 3ms
20:30:09.678 JS Error: Error when calling DELETE branches/7Hzb2SVoyxJu?taskId=WAlgfbnfJt&last=true: error - Internal Server Error
Stack: Error
    at Object.logError (https://docs.angrym.com/app/services/ws.js:26:20)
    at Object.throwError (https://docs.angrym.com/app/services/toast.js:87:8)
    at reportError (https://docs.angrym.com/app/services/server.js:106:18)
    at async Object.error (https://docs.angrym.com/app/services/server.js:131:17)

**Comment by zadam** [comment]
Hi, this is quite unfortunate. The SQLite database file is corrupted and that's difficult to repair. This is probably caused by some kind of hardware crash or failure.

One option would be to try to recover the file: [https://stackoverflow.com/questions/18259692/how-to-recover-a-corrupt-sqlite3-database](https://stackoverflow.com/questions/18259692/how-to-recover-a-corrupt-sqlite3-database)

Or perhaps easier would be to restore a backup: https://github.com/zadam/trilium/wiki/Backup

**Comment by mopsicus** [comment]
Seems Trilium is not so stable as I expected... 
I'll check it one more time, but guess, I'll not make really full knowledge base on it. Pity... all features I really like.

**Comment by zadam** [comment]
This is not a Trilium's bug though - either it's a problem in SQLite itself or it was caused by a hardware failure. Trilium is "not able" to corrupt the SQLite database file ...

**Comment by mopsicus** [comment]
For last 10 days I've got 2 DB errors. My vds works more than year without any problems...

**Comment by zadam** [comment]
BTW, I just recalled that in the past this was usually caused by Dropbox or similar sync tool messing up the DB file (that's why this style of sync is heavily discouraged). Not sure if this is your case though ...
