### ISSUE TITLE
webclip error

### ISSUE THREAD

**Issue by aihuasxy** [zadam/trilium#1840]
version:
0.46.6

log:
16:41:30.182 ERROR: post /api/clipper/notes threw exception: TypeError: Cannot read property 'substr' of undefined
    at processContent (D:\tool\trilium-windows-x64\resources\app.asar\src\routes\api\clipper.js:110:80)
    at createNote (D:\tool\trilium-windows-x64\resources\app.asar\src\routes\api\clipper.js:90:30)
    at Function.cb (D:\tool\trilium-windows-x64\resources\app.asar\src\routes\routes.js:96:34)
    at Function.sqliteTransaction (D:\tool\trilium-windows-x64\resources\app.asar\node_modules\better-sqlite3\lib\transaction.js:58:24)
    at Object.transactional (D:\tool\trilium-windows-x64\resources\app.asar\src\services\sql.js:234:52)
    at D:\tool\trilium-windows-x64\resources\app.asar\src\routes\routes.js:98:44
    at D:\tool\trilium-windows-x64\resources\app.asar\node_modules\cls-hooked\context.js:118:13
    at Namespace.run (D:\tool\trilium-windows-x64\resources\app.asar\node_modules\cls-hooked\context.js:97:5)
    at Namespace.runAndReturn (D:\tool\trilium-windows-x64\resources\app.asar\node_modules\cls-hooked\context.js:117:8)
    at Object.init (D:\tool\trilium-windows-x64\resources\app.asar\src\services\cls.js:5:22)

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. This probably happens only with some unparseable images, I improved the handling of such errors so that whole clipping does not fail.
