### ISSUE TITLE
Using orderBy when the search result is empty causes an error

### ISSUE THREAD

**Issue by WPum** [zadam/trilium#1870]
ERROR: get /api/search-note/:noteId threw exception: TypeError: Cannot read property 'match' of undefined
    at isOperator (.../src/services/search/services/parse.js:44:16)
    at parseLabel (.../src/services/search/services/parse.js:236:38)
    at parseAttribute (.../src/services/search/services/parse.js:228:34)
    at getExpression (.../src/services/search/services/parse.js:347:30)
    at parse (.../src/services/search/services/parse.js:410:9)
    at parseQueryToExpression (.../src/services/search/services/search.js:123:24)
    at Object.findNotesWithQuery (.../src/services/search/services/search.js:148:24)
    at search (.../src/routes/api/search.js:31:45)
    at searchFromNote (.../src/routes/api/search.js:56:18)
    at Function.cb (.../src/routes/routes.js:96:34)

**Comment by WPum** [comment]
This is potentially caused by an invalid search term
