### ISSUE TITLE
Note name "constructor" causes error in similar notes

### ISSUE THREAD

**Issue by zhuyizheng** [zadam/trilium#1895]
Version: 0.46.9
Linux

The moment I create a new note named "constructor", an error like this shows up as a pop-up:

> Error when calling GET /api/similar-notes/4EB0dJ5yZUbD: 500 - splitToWords is not a function or its return value is not iterable

Error log:

> 20:01:57.345 JS Error: Error when calling GET /api/similar-notes/4EB0dJ5yZUbD: 500 - splitToWords is not a function or its return value is not iterable
Stack: Error
    at Object.w [as logError] (http://127.0.0.1:37840/app-dist/desktop.js:1:86359)
    at Object.throwError (http://127.0.0.1:37840/app-dist/desktop.js:1:64376)
    at c (http://127.0.0.1:37840/app-dist/desktop.js:1:61381)
    at async EventEmitter.<anonymous> (http://127.0.0.1:37840/app-dist/desktop.js:1:62048)

I have tested other names, but only naming a note "constructor" causes this bug.

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. It has been fixed and will be in the next stable release (0.47.2).
