### ISSUE TITLE
docker run 0.47-latest fail

### ISSUE THREAD

**Issue by NKid** [zadam/trilium#1960]
docker command
```
docker run -d --name trilium --network="my-bridge" \
-v ~/MyConfig/trilium:/home/node/trilium-data \
zadam/trilium:0.47-latest
```
docker logs
```
internal/fs/utils.js:269
    throw err;
    ^

Error: EACCES: permission denied, mkdir '/home/node/trilium-data/log'
    at Object.mkdirSync (fs.js:921:3)
    at Object.<anonymous> (/usr/src/app/src/services/log.js:7:8)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/src/app.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1015:30) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/home/node/trilium-data/log'
}
```

**Comment by zadam** [comment]
Hi, this is a permission issue, container does not have writable access to the directory.

If you're the only user on your computer then `chmod 777 ...` might be the simplest option ...

**Comment by NKid** [comment]
Yes, I'm only user.
`chmod 777 ~/MyConfig/trilium`, it works.
Thx a lot.
