### ISSUE TITLE
[Bug] Cannot access backend log (Docker version 0.47.3)

### ISSUE THREAD

**Issue by ehamminga** [zadam/trilium#1977]
In a Chrome browser I tried accessing the backend log. It threw me the following error:
![image](https://user-images.githubusercontent.com/16200113/119422322-00912180-bd40-11eb-9aa4-da00dca30b92.png)
When I looked in my trilium-data dir for my log file, there was none.
After triggering a "Erase deleted notes now" the log seems to be back up and running, and a log file can be found in my data dir. I had the same issue for two separate Docker images, both running 0.47.3

Log after clicking the "Erase deleted notes now":
24:11:34.705 ERROR: get /api/backend-log threw exception: Error: ENOENT: no such file or directory, open '/home/node/trilium-data/log/trilium-2021-05-25.log'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at getBackendLog (/usr/src/app/src/routes/api/backend_log.js:10:15)
    at Function.cb (/usr/src/app/src/routes/routes.js:97:34)
    at Function.sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (/usr/src/app/src/services/sql.js:238:52)
    at /usr/src/app/src/routes/routes.js:99:44
    at /usr/src/app/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/usr/src/app/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/usr/src/app/node_modules/cls-hooked/context.js:117:8)
00:11:34.707 500 GET /api/backend-log took 2ms
00:11:34.729 JS Error: Error when calling GET backend-log: error - Internal Server Error

**Comment by zadam** [comment]
Hi, it looks like you stumbled upon a corner case where the log file does not exist yet, because nothing has been added to the log that day. Based on time `00:11:34.707` this seems quite possible ...

Anyway I added more graceful handling of this situation ...

Thanks for reporting!
