### ISSUE TITLE
WindowsV0.47.3: sync failed: Option syncServerHost doesn't exist

### ISSUE THREAD

**Issue by Fulgaturi** [zadam/trilium#1985]
Hi there,

im not really familiar with the Workings of Windows and got an Error on the Windows Desktop Version 0.47.3
After the setup page the Program gets stuck at the "Inital-Sync" screen. 
The "Error: Option initialized doesn't exist" Exception loops indefenitly.
Can s.o. help me understand the issue? 

```
16:46:36.300 CPU model: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz, logical cores: 8 freq: 2803 Mhz
16:46:36.309 Listening on port 37840
16:46:36.407 Triggering sync.
16:46:36.412 200 GET /setup took 7ms
16:46:36.413 sync failed: Option syncServerHost doesn't exist
stack: Error: Option syncServerHost doesn't exist
    at Object.getOption (C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\src\services\options.js:5:15)
    at get (C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\src\services\sync_options.js:14:70)
    at Object.isSyncSetup (C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\src\services\sync_options.js:20:32)
    at C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\src\services\sync.js:28:30
    at Object.doExclusively (C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\src\services\sync_mutex.js:13:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.sync (C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\src\services\sync.js:27:16)
16:46:37.590 ERROR: get /api/sync/stats threw exception: Error: Option initialized doesn't exist
    at Object.getOption (C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\src\services\options.js:5:15)
    at getStats (C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\src\routes\api\sync.js:45:36)
    at Function.cb (C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\src\routes\routes.js:97:34)
    at Function.sqliteTransaction (C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\node_modules\better-sqlite3\lib\methods\transaction.js:65:24)
    at Object.transactional (C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\src\services\sql.js:238:52)
    at C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\src\routes\routes.js:99:44
    at C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\node_modules\cls-hooked\context.js:118:13
    at Namespace.run (C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\node_modules\cls-hooked\context.js:97:5)
    at Namespace.runAndReturn (C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\node_modules\cls-hooked\context.js:117:8)
    at Object.init (C:\Users\Tim\Downloads\trilium-windows-x64-0.47.3\trilium-windows-x64\resources\app.asar\src\services\cls.js:5:22)
16:46:37.590 500 GET /api/sync/stats took 1ms
```
Full log: [trilium-2021-05-29.log](https://github.com/zadam/trilium/files/6564922/trilium-2021-05-29.log)

**Comment by zadam** [comment]
Hi, thanks for reporting this issue.

The log is weird. I'm not sure what's going on there exactly. 

Would you mind sending me zipped directory of `C:\\Users\\Tim\\AppData\\Roaming\\trilium-data` to `zadam.apps@gmail.com`? As I understand this is a clean installation so there shouldn't be any sensitive data yet. This would help me to analyze this problem.

Thanks.

**Comment by Fulgaturi** [comment]
Thx for the fast reply, 
i sent you the directory, it is indeed from a clean install so no worries there.

**Comment by zadam** [comment]
Thank you for the database ZIP. Based on that and the log it seems to me that the initialization was interrupted and the database got into an unexpected state. I don't know why was the initialization interrupted, logs doesn't have any error but it's clear that it did not finish.

I implemented changes to put all critical initialization steps into one transaction so that it does not end up in such in-between step.

For you, I would advise to delete the `trilium-data` directory and try again. Make sure that it gets to the end before stopping it.

**Comment by Fulgaturi** [comment]
I tried some of the older releases for comparison and up to V0.46.9 they seem to be working fine. 

I cant see any difference in the logs, up to the point where 0.47 stops doing anything, from both clean installs (also checked the installation via cmd startup)
The 0.47.3 Version stops in the cmd at:
```
...
Listening on port 37840
200 GET /setup took 4ms
Creating initial database ...
Slow 200 POST /api/setup/new-document took 12ms

```

**Comment by zadam** [comment]
I see, that's strange. If you create the document with 0.46.9 and then upgrade to 0.47 then does this work?

**Comment by Fulgaturi** [comment]
Yes that works, after setting it up with 0.46.9 it runs perfectly fine on 0.47.3
All functionality connected to the DB i could test seemed to work fine in 0.47.3 after this
