### ISSUE TITLE
SqliteError: unable to open database file

### ISSUE THREAD

**Issue by Clueluss** [zadam/trilium#2020]
Sorry, I'm very new to all of this.
I installed trilium-bin on aur, but it's giving me an Sqlite error. I've tried (re)installing the sqlite entries mentioned in the Arch wiki, but nothing changed

```
A JavaScript error occurred in the main process
Uncaught Exception:
SqliteError: unable to open database file
    at new Database (/opt/trilium-bin/resources/app.asar/node_modules/better-sqlite3/lib/database.js:46:26)
    at Object.<anonymous> (/opt/trilium-bin/resources/app.asar/src/services/sql.js:12:22)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/trilium-bin/resources/app.asar/src/services/sql_init.js:4:13)
```

**Comment by Clueluss** [comment]
Well, the answer was `sudo chown` on one of the Trilium files, though whether it was the ones in /opt or /home I can't say
