### ISSUE TITLE
Trilium v0.47.4: Cannot find module 'archiver' on Arm

### ISSUE THREAD

**Issue by ilikeorangutans** [zadam/trilium#2022]
Built Trilium 0.47.4 dockerfile with docker buildx for armv7 but it fails to start up with the following log:
```
DB size: 8433 KB
internal/modules/cjs/loader.js:834
  throw err;
  ^
Error: Cannot find module 'archiver'
Require stack:
- /usr/src/app/src/services/export/zip.js
- /usr/src/app/src/routes/api/export.js
- /usr/src/app/src/routes/routes.js
- /usr/src/app/src/app.js
- /usr/src/app/src/www
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/src/services/export/zip.js:15:18)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/src/app/src/services/export/zip.js',
    '/usr/src/app/src/routes/api/export.js',
    '/usr/src/app/src/routes/routes.js',
    '/usr/src/app/src/app.js',
    '/usr/src/app/src/www'
  ]
}
```

I'm not sure if it's archiver specifically or if it just happens to be the first dependency in alphabetical order. Comparing `packages.json` and `server-packages.json` shows me that `archiver` among others is missing. Maybe there's just some elements that should be in server-packages.json ?

**Comment by ilikeorangutans** [comment]
After some digging I realized I had an old server-package.json in place. This was all entirely my own doing. :facepalm:
