### ISSUE TITLE
Add tutorial for contribution

### ISSUE THREAD

**Issue by Myzel394** [zadam/trilium#2037]
I'm currently trying to get `start-electron` working, but I keep getting this error:

```bash
Debugger listening on ws://127.0.0.1:5858/e0475c4a-d4f4-4c46-a2bb-a16eb957869a
For help, see: https://nodejs.org/en/docs/inspector
App threw an error during load
Error: The module '/home/myzel394/WebstormProjects/trilium/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 89. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/home/myzel394/WebstormProjects/trilium/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/myzel394/WebstormProjects/trilium/node_modules/better-sqlite3/lib/database.js:9:24)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: The module '/home/myzel394/WebstormProjects/trilium/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 89. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (/home/myzel394/WebstormProjects/trilium/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/myzel394/WebstormProjects/trilium/node_modules/better-sqlite3/lib/database.js:9:24)
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
mesa: for the --structurizecfg-skip-uniform-regions option: may only occur zero or one times!
```

I tried to rebuild the project with Node `v16.1.0` and `v14.17.0` but the error stays the same.
Maybe it's a good idea to add the required versions to the [`README.MD`](https://github.com/zadam/trilium/blob/master/README.md)?

Btw, `start-server` works perfectly, here's the server log:

```
17:04:30.899 Generated session secret
17:04:30.945 DB size: 4 KB
17:04:31.473 DB not initialized, please visit setup page - http://[your-server-host]:8080 to see instructions on how to initialize Trilium.
17:04:31.473 App HTTP server starting up at port 8080
17:04:31.473 {
  "appVersion": "0.47.2",
  "dbVersion": 183,
  "syncVersion": 20,
  "buildDate": "2021-04-26T22:32:54+02:00",
  "buildRevision": "6f1b0b92fe8dcea736c15217c69512c7fee769cb",
  "dataDirectory": "/home/myzel394/.local/share/trilium-data",
  "clipperProtocolVersion": "1.0"
}
17:04:31.492 CPU model: AMD Ryzen 7 3700X 8-Core Processor, logical cores: 16 freq: 1979 Mhz
17:04:31.496 Listening on port 8080
```

OS: Ubuntu 20.04

**Comment by zadam** [comment]
electron requires rebuilding of the binary packages - you need to run `./node_modules/.bin/electron-rebuild` (but the these are not compatible with normal node.js)
