### ISSUE TITLE
TypeError: Cannot read property 'noteId' of undefined

### ISSUE THREAD

**Issue by TheBlusky** [zadam/trilium#2058]
I created a new instance, and played with it.

When going to today's note, I got the following error:

![vivaldi_ZPIXurfx8P](https://user-images.githubusercontent.com/441709/124572770-351cf080-de49-11eb-8b9d-36b4925a67a5.png)

When looking at logs, I got the following error:

```
ERROR: get /api/edited-notes/:date threw exception: TypeError: Cannot read property 'noteId' of undefined
    at Object.getNotePath (/usr/src/app/src/services/note_cache/note_cache_service.js:178:62)
    at getEditedNotesOnDate (/usr/src/app/src/routes/api/note_revisions.js:124:67)
    at Function.cb (/usr/src/app/src/routes/routes.js:97:34)
    at Function.sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (/usr/src/app/src/services/sql.js:238:52)
    at /usr/src/app/src/routes/routes.js:99:44
    at /usr/src/app/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/usr/src/app/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/usr/src/app/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/usr/src/app/src/services/cls.js:5:22)
JS Error: Error when calling GET edited-notes/2021-07-06: error -
```

When digging into source code, I think the problem is here: https://github.com/zadam/trilium/blob/master/src/becca/becca_service.js#L178

```
        return {
            noteId: noteId,
            branchId: becca.getBranchFromChildAndParent(noteId, parentNote.noteId).branchId, <-------
            title: noteTitle,
            notePath: retPath,
            path: retPath.join('/')
        };
```

Because, in today's modified note, there is the `root` note, and I tihnk this note does not have a parent.

I too new to this project to suggest a PR for fixing this, but I think this investigation should be enough to let someone fix it easily.

**Comment by zadam** [comment]
Hi, thanks for bug report, your analysis was correct. Fixed.
