### ISSUE TITLE
Server cannot start; wrong ELF class?

### ISSUE THREAD

**Issue by PAK90** [zadam/trilium#2059]
I'm using 0.47.5, extracted on Raspbian 10, with node v12.17.0, and I try to run `node src/www` and I get this:

```
Error: /home/usr/Downloads/trilium-linux-x64-server/node_modules/better-sqlite3/build/Release/better_sqlite3.node: wrong ELF class: ELFCLASS64
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/home/usr/Downloads/trilium-linux-x64-server/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/usr/Downloads/trilium-linux-x64-server/node_modules/better-sqlite3/lib/database.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
```

It didn't do this when I was using an older 0.42 version, from what I remember... The log file is empty too, so nothing there.

edit: I tried doing `./trilium.sh` but that gives me `./trilium.sh: 2: ./trilium.sh: ./node/bin/node: Exec format error`, which seems bad too.

**Comment by TheBlusky** [comment]
Looks like you are using a x64 build (`trilium-linux-x64-server`) for an ARM processor (Raspberry ?).

If you just run JavaScript files through local node, it should not be a problem.

However, the package `better-sqlite3` was not present in the 0.42 version but is on latests, and it contains a binary (packaged for x64). That's why it does not work.

You can try removing the `node_modules` directory, and run `npm install`. If there's a AMR64 compatible build for dependencies, it will be installed.

(however, `better-sqlite3` does not seems to provide ARM builds https://github.com/JoshuaWise/better-sqlite3/issues/653)

Good luck

**Comment by PAK90** [comment]
Thanks for that suggestion, it seems to have worked out. I did `npm install` and despite giving a 404 error, it was in the post-install script so I tried running `node src/www` anyway and it seems to be working fine; it performed several db migrations and synced with my local Trilium instance. Might be a good thing to move it off a rasberry pi at some point anyway...
