### ISSUE TITLE
trilium-server will not sync with trilium-desktop over TLS; ERROR: ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by radomuc** [zadam/trilium#2060]
Hello,
over http I got a successful sync, but with https I didn't managed to get a sync. I tried with a certificate signed by CA - this failed. I don't know how I can configure the desktop-variant to accept my CA. I can't find any documentation about this. So I then tried a self-signed certificate as described in the documentation, but this also failed again with the same error (ERR_CERT_AUTHORITY_INVALID). Do you have any suggestions about this issue?

--- LOG ---
09:14:18.386 DB size: 1601 KB
09:14:19.673 Note cache load took 9ms
09:14:19.745 App HTTP server starting up at port 37840
09:14:19.745 {
  "appVersion": "0.47.5",
  "dbVersion": 183,
  "syncVersion": 20,
  "buildDate": "2021-06-25T21:26:48+02:00",
  "buildRevision": "0a2807c0b3fb7809d1cd1be3a051d127db010b5e",
  "dataDirectory": "/home/user/.local/share/trilium-data",
  "clipperProtocolVersion": "1.0"
}
09:14:19.773 CPU model: Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz, logical cores: 8 freq: 1333 Mhz
09:14:19.782 Listening on port 37840
09:14:19.841 Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
09:14:19.878 Generated CSRF token ClT3oPLF-_IbmWO9NkKQKrMMAwj48y836hNQ with secret _csrf=2Jrja-apy3MjDEhD8lxjrRNr; Path=/
09:14:20.214 200 GET /api/options took 2ms
09:14:20.222 200 GET /api/keyboard-actions took 2ms
09:14:20.226 200 GET /api/keyboard-shortcuts-for-notes took 0ms
09:14:20.228 200 GET /api/tree took 1ms
09:14:20.230 200 GET /api/script/widgets took 2ms
09:14:20.232 200 POST /api/tree/load took 0ms
09:14:20.833 200 GET /api/notes/HNqMDt8QC6oe took 2ms
09:14:21.903 Slow 200 GET /api/similar-notes/HNqMDt8QC6oe took 97ms
09:14:21.905 200 GET /api/notes/HNqMDt8QC6oe/revisions took 1ms
09:14:22.031 200 POST /api/notes/HNqMDt8QC6oe/link-map took 2ms
09:14:22.286 200 GET /api/script/startup took 1ms
09:14:22.290 200 POST /api/tree/load took 1ms
09:14:22.296 200 POST /api/tree/load took 0ms
09:14:22.303 200 POST /api/tree/load took 1ms
09:14:24.861 sync failed: Request to GET https://nextcloudrpi.ho:7777/api/setup/status failed, error: Error: net::ERR_CERT_AUTHORITY_INVALID
stack: Error: Request to GET https://nextcloudrpi.ho:7777/api/setup/status failed, error: Error: net::ERR_CERT_AUTHORITY_INVALID
    at generateError (/usr/lib/trilium/resources/app.asar/src/services/request.js:191:12)
    at ClientRequest.<anonymous> (/usr/lib/trilium/resources/app.asar/src/services/request.js:58:47)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest._die (electron/js2c/browser_init.js:105:8391)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7128)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.callbackTrampoline (internal/async_hooks.js:131:14)

**Comment by zadam** [comment]
Hi, there's a `trilium-no-cert-check.sh` which will disable TLS cert verification. Start the desktop client using that and it should work (the communication is still encrypted but the cert is not verified).

**Comment by Y-con** [comment]
> Hi, there's a `trilium-no-cert-check.sh` which will disable TLS cert verification. Start the desktop client using that and it should work (the communication is still encrypted but the cert is not verified).

Hi,
I ran with `trilium-no-cert-check.sh` but it did not help.
So I simulated `trilium-no-cert-check.sh` way to set the env and print it.But NODE_TLS_REJECT_UNAUTHORIZED is undefined .
Even if I set up a global windows environment for NODE_TLS_REJECT_UNAUTHORIZED ,it won't help.
That seems a little bit weird for me.

`trilium> set NODE_TLS_REJECT_UNAUTHORIZED=0`
`trilium> node .\src\www`

<img width="666" alt="1627729035(1)" src="https://user-images.githubusercontent.com/22042129/127737775-5fbfd365-3dbe-4cac-827b-3fb456612f70.png">

**Comment by d03j** [comment]
> Hi, there's a `trilium-no-cert-check.sh` which will disable TLS cert verification. Start the desktop client using that and it should work (the communication is still encrypted but the cert is not verified).

I am having a similar issue running 0.47.5 desktop on unbuntu 21.04 and 0.47.5 server on a docker container.

I used Let's Encrypt's certbot to generate a certificate for my no-ip domain and updated the config.ini with the pahs to the certificate and key. While I am testing the configuration, I haven't opened a port in my router yet but know TLS is working because I can access the server by entering its IP address in my browser (https://xxx.xxx.xxx.xxx) and choosing to ignore the certificate warning. 

When I try to sync the desktop (working before I moved it to https) I get ERR_CERT_COMMON_NAME_INVALID. The reult is the same for trilium (expected) and trilium-no-cert-check.sh (unexpected),

If I run `echo $NODE_TLS_REJECT_UNAUTHORIZED` after starting trilium-no-cert-check.sh I get an empty result, If I enter `export NODE_TLS_REJECT_UNAUTHORIZED=0` in the command line myself and then start trillium, I get "0" when I try `echo $NODE_TLS_REJECT_UNAUTHORIZED`.

In all cases I get ERR_CERT_COMMON_NAME_INVALID when trying to sync.

**Comment by chncho** [comment]
> > Hi, there's a `trilium-no-cert-check.sh` which will disable TLS cert verification. Start the desktop client using that and it should work (the communication is still encrypted but the cert is not verified).
> 
> I am having a similar issue running 0.47.5 desktop on unbuntu 21.04 and 0.47.5 server on a docker container.
> 
> I used Let's Encrypt's certbot to generate a certificate for my no-ip domain and updated the config.ini with the pahs to the certificate and key. While I am testing the configuration, I haven't opened a port in my router yet but know TLS is working because I can access the server by entering its IP address in my browser (https://xxx.xxx.xxx.xxx) and choosing to ignore the certificate warning.
> 
> When I try to sync the desktop (working before I moved it to https) I get ERR_CERT_COMMON_NAME_INVALID. The reult is the same for trilium (expected) and trilium-no-cert-check.sh (unexpected),
> 
> If I run `echo $NODE_TLS_REJECT_UNAUTHORIZED` after starting trilium-no-cert-check.sh I get an empty result, If I enter `export NODE_TLS_REJECT_UNAUTHORIZED=0` in the command line myself and then start trillium, I get "0" when I try `echo $NODE_TLS_REJECT_UNAUTHORIZED`.
> 
> In all cases I get ERR_CERT_COMMON_NAME_INVALID when trying to sync.

Have you repair it ? I has the save problem too.

**Comment by PracBesTice** [comment]
Hey, 
i have the same Problem, is there any solution? 
Push.

**Comment by luddet** [comment]
I have the same problem on Kali linux.
I have trilium_0.49.5_amd64.deb installed and try to sync to my trilium server version 0.49.5 running in docker.
I'm using a certificate that is signed with my own self-signed CA cert. I have added the CA cert to /usr/local/share/ca-certificates and run update-ca-certificates --fresh.
I have also imported the CA cert into firefox certificate store, and logging in to trilium that way works just fine, so it seems that node is not picking up the CA cert from the system on linux.
Also, connecting to my server from a windows install of trilium works just fine after installing my CA cert into the trusted root CA store, so it seems that the problem happens only on linux.
Is there any workaround yet?

**Comment by mytlogos** [comment]
I found a currently working workaround, for disabled any certificate errors:
Start trilium with the following flag: `/usr/lib/trilium/trilium --ignore-certificate-errors`
This flag comes from Electron.js itself, where it will ignore any certificate errors.
Syncing works with a custom CA and DNS Name.

See https://www.electronjs.org/docs/latest/api/command-line-switches#--ignore-certificate-errors
If it works for everyone, than it could maybe added to the current trilium-no-cert-check.sh script.

**Comment by Nordiger** [comment]
Hi, some problem here.

I'm running trilium with docker on my Synology NAS and use a Let's Encrypt's certificate. 

Is there a solution? I use it on v0.53.2

**Comment by egidijus** [comment]
You can also use the switch with windows standalone.
Create a shortcut to the trillium binary, then edit the shortcut and append to the target field like this:
```
trilium-windows-x64\trilium.exe --ignore-certificate-errors
```

![image](https://github.com/zadam/trilium/assets/6087967/50a64d75-54ca-4bed-9d4d-a17c2bfcf65f)

**Comment by Darkfoxjj12** [comment]
> What should I do ?

--- Solution ---
This worked for me, I've setted up a reverse proxy ( HaProxy for myself ), I made a[ ssl termination ](https://avinetworks.com/glossary/ssl-termination/) and generated a self signed certificate, because I doesn't have a domain to make DNS Zones. After that i Imported the cerficate from the new reverse https proxy in my windows certificate manager. 
I moved the trillium server to the root of my windows C:/  Due to syntax problems like spaces
Then I created a shortlink to my desktop with the " --ignore-certificate-errors" parameter.
It look like this **C:\trilium-windows-x64-0.63.3\trilium-windows-x64\trilium.exe** --ignore-certificate-errors**
And when I launched the link and connected it to my reverse proxy it's synchronizing the data yay ! 
If I made somes misunderstandings please let me know  :)

**Comment by youli42** [comment]
使用 --ignore-certificate-errors 作为启动参数是我现在使用的唯一有效的方案，谢谢各位

**Comment by Abhi-cc** [comment]
Chromium Browsers uses separate trusted CA Database just like Firefox. Even the self signed certificate is trusted by system it wont work on electron. 

I manually imported my root CA certificate to the electron/chromium trusted Certificate store and it fixed the issue for me.

**Comment by drasikhov** [comment]
Still broken on Windows desktop app (0.101.3). Adding `NODE_TLS_REJECT_UNAUTHORIZED=0` environment variable doesn't do anything. [This documentation section](https://docs.triliumnotes.org/user-guide/setup/server/https#self-signed-certificate) should be updated with relevant information about simply adding the `--ignore-certificate-errors ` flag to executable shortcut. `trilium-no-cert-check.bat ` is probably unnecessary.

**Comment by mrbeandev** [comment]
my issue was : 

<img width="466" height="493" alt="Image" src="https://github.com/user-attachments/assets/174efb28-80a7-4dc6-9004-386cba24620f" />

the solution was much simpler than i tought for me !
i have opened my laptop after many months , so its time was out of sync with my current timezone.
so once i synced the date & time setting , everything worked perfectly ! 

finally fixed it - 

<img width="636" height="178" alt="Image" src="https://github.com/user-attachments/assets/c9a5061e-40f5-4163-9ddf-64ab5f2187be" />
