### ISSUE TITLE
Deleting a note sometimes causes an error in the main process

### ISSUE THREAD

**Issue by abitofevrything** [zadam/trilium#2073]
Trilium version: `master@f3959cf2aada016b4b96fc097e7d6fee9185b123`
Log file: [trilium-2021-07-21.log](https://github.com/zadam/trilium/files/6856661/trilium-2021-07-21.log)

Deleting a note sometimes causes the following exception to occur: 
```
Uncaught Exception:
TypeError: Cannot read property 'getContent' of undefined
    at Function.<anonymous> (.../trilium/src/services/notes.js:365:46)
    at Function.sqliteTransaction (.../trilium/node_modules/better-sqlite3/lib/methods/transactio...:24)
    at Object.transactional (.../trilium/src/services/sql.js:238:52)
    at Timeout._onTimeout (.../trilium/src/services/notes.js:361:17)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

## How to reproduce:

1. Open devtools in the electron app
2. Go to network tab > throttling and set to 'Offline'
3. Create a new note, then delete it
4. Go back to network tab > throttling and reset to 'No throttling'
5. After a couple of seconds the error will appear

This seems to be due to notes being deleted while note images are still being downloaded.

**Comment by zadam** [comment]
Hi, thanks for report, fixed.
