### ISSUE TITLE
Problems after Let's Encrypt certificate renewal syncing trilium-server vs. desktop

### ISSUE THREAD

**Issue by HiFiJ** [zadam/trilium#2227]
Hi everyone,
thanks zadam for this great solution to notetaking (and much more)!
After today's renewal of my server's (0.47.8) let's encrypt certificate, the sync to my numerous desktop clients (0..47.8) stopped connecting/syncing with 
```
error: Error: net::ERR_CERT_DATE_INVALID
    at generateError (/opt/trilium-bin/resources/app.asar/src/services/request.js:191:12)
    at ClientRequest.<anonymous> (/opt/trilium-bin/resources/app.asar/src/services/request.js:58:47)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest._die (electron/js2c/browser_init.js:105:8391)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7128)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.callbackTrampoline (internal/async_hooks.js:131:14)
```
I suppose the new root certificate used by LE might be the problem; here are some sources I found:

[https://stackoverflow.com/questions/69414479/giving-axios-letsencrypts-new-root-certificate-on-old-version-of-node](url)
[https://github.com/electron/electron/issues/31212](url)

Thanks for any help,
best regards,

Joost

**Comment by zadam** [comment]
Hmm, weird. As a workaround you can run `trilium-no-cert-check.sh` which will disable TLS verification (assuming you accept the risks involved ...)

**Comment by HiFiJ** [comment]
Is there any chance that running the server on port 8080 interferes?

**Comment by HiFiJ** [comment]
> Hmm, weird. As a workaround you can run `trilium-no-cert-check.sh` which will disable TLS verification (assuming you accept the risks involved ...)

Thanks, will look around for this, it's a manjaro package install and not in path. Will get back with results.

Btw. Chromium loads the server just fine, no cert errors there.

**Comment by HiFiJ** [comment]
Thanks, but unfortunately...:

```
~/.../Trilium/trilium-linux-x64 >>> NODE_TLS_REJECT_UNAUTHORIZED=0 trilium                                                                                                                        
                                                                                                                  

DB size: 13438 KB
Note cache load took 11ms
App HTTP server starting up at port 37840
{
  "appVersion": "0.47.8",
  "dbVersion": 183,
  "syncVersion": 20,
  "buildDate": "2021-10-04T22:18:33+02:00",
  "buildRevision": "1f75b9c92f1f695e4f43230f88d676ab8a0b39c0",
  "dataDirectory": "/home/jc/.local/share/trilium-data",
  "clipperProtocolVersion": "1.0"
}
CPU model: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, logical cores: 8 freq: 1879 Mhz
Listening on port 37840
Registered global shortcut Ctrl+Alt+P for action createNoteIntoInbox
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Generated CSRF token qrV1l087-Xxn-eqUkB_pUw4K6WDPGYUQLvks with secret _csrf=UEc6LduJa1X_mGhvx3Kw91vG; Path=/
200 GET /api/options took 1ms
200 GET /api/keyboard-actions took 2ms
200 GET /api/keyboard-shortcuts-for-notes took 1ms
200 GET /api/tree took 2ms
200 GET /api/script/widgets took 1ms
websocket client connected
200 GET /api/notes/kdiVvMfXmCR1 took 2ms
Slow 200 GET /api/similar-notes/kdiVvMfXmCR1 took 27ms
200 GET /api/notes/kdiVvMfXmCR1/revisions took 2ms
200 GET /api/script/startup took 2ms
sync failed: Request to GET https://h2910XXX.stratoserver.net:8080/api/setup/status failed, error: Error: net::ERR_CERT_DATE_INVALID
stack: Error: Request to GET https://h291XXXstratoserver.net:8080/api/setup/status failed, error: Error: net::ERR_CERT_DATE_INVALID
    at generateError (/opt/trilium-bin/resources/app.asar/src/services/request.js:191:12)
    at ClientRequest.<anonymous> (/opt/trilium-bin/resources/app.asar/src/services/request.js:58:47)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest._die (electron/js2c/browser_init.js:105:8391)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7128)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.callbackTrampoline (internal/async_hooks.js:131:14)
Slow 204 POST /api/recent-notes took 15ms
Slow 204 POST /api/recent-notes took 11ms
204 POST /api/recent-notes took 9ms
Table counts: notes: 388, note_revisions: 1162, branches: 414, attributes: 330, api_tokens: 0
All consistency checks passed (took 46ms)
```

**Comment by HiFiJ** [comment]
Hi everyone,

just as a further follow up and solution, as this issue still persisted:

The problem seems to be related to Electron caching certificate data on the client/desktop side (my own non-programmer  interpretation).
Removing ( e.g. renaming) the folder
`~/.config/trilium Notes/Cache`
resolved this nagging issue immediately.

Thanks everyone,

Joost
