### ISSUE TITLE
(Bug report) inherited attributes display error

### ISSUE THREAD

**Issue by anno189** [zadam/trilium#2292]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.3

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

macOS Big Sur， Ubuntu 18.04

### Expected Behavior

click  inherited attributes

<img width="776" alt="截屏2021-10-29 下午4 53 17" src="https://user-images.githubusercontent.com/3339262/139406966-9a10efc5-c43d-45d5-a856-5861c7114058.png">

### Actual Behavior

Backend log

16:59:19.640 ERROR: post /api/search-related threw exception: RangeError: Maximum call stack size exceeded
    at Array.flat (<anonymous>)
    at Note.getSubtreeNotesIncludingTemplated (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/becca/entities/note.js:748:20)
    at Note.getSubtreeNotesIncludingTemplated (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/becca/entities/note.js:735:32)
    at Note.getSubtreeNotesIncludingTemplated (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/becca/entities/note.js:735:32)
    at Note.getSubtreeNotesIncludingTemplated (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/becca/entities/note.js:735:32)
    at Note.getSubtreeNotesIncludingTemplated (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/becca/entities/note.js:735:32)
    at Note.getSubtreeNotesIncludingTemplated (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/becca/entities/note.js:735:32)
    at Note.getSubtreeNotesIncludingTemplated (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/becca/entities/note.js:743:35)
    at Note.getSubtreeNotesIncludingTemplated (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/becca/entities/note.js:735:32)
    at Note.getSubtreeNotesIncludingTemplated (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/becca/entities/note.js:735:32)
16:59:19.672 304 GET /api/clipper/handshake with 45 bytes took 5ms
16:59:19.678 JS Error: Error when calling POST /api/search-related: 500 - Maximum call stack size exceeded
Stack: Error
    at Object.N [as logError] (http://127.0.0.1:37840/app-dist/desktop.js:2:97997)
    at Object.throwError (http://127.0.0.1:37840/app-dist/desktop.js:2:83551)
    at c (http://127.0.0.1:37840/app-dist/desktop.js:2:80478)
    at async EventEmitter.<anonymous> (http://127.0.0.1:37840/app-dist/desktop.js:2:81223)

**Comment by zadam** [comment]
Hi, thanks for reporting this, fixed.
