### ISSUE TITLE
Windows 0.48.5 wont open (new setup)

### ISSUE THREAD

**Issue by CorneliousJD** [zadam/trilium#2315]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/zadam/trilium/issues) for a bug report that matches the one I want to file, without success.

### Trilium Version

0.48.5

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 10 Pro

### Expected Behavior

Download 0.48.5 and extract it then open it -- it just never opens, no errors.

### Actual Behavior

Nothing, no errors. 

### Additional Information

If I run the portable.bat file I DO get the new welcome interface.

**Comment by CorneliousJD** [comment]
I did end up trying to run from command line and found the "app db version is 185 while db version is 170. Migration needed" but this is a brand new download/setup, so that's odd. I tried delting the 

```
C:\Users\Corey\Downloads\trilium\trilium-windows-x64>
App db version is 185, while db version is 170. Migration needed.
DB size: 2236 KB
App HTTP server starting up at port 37840
{
  "appVersion": "0.48.5",
  "dbVersion": 185,
  "syncVersion": 21,
  "buildDate": "2021-11-01T10:25:43+01:00",
  "buildRevision": "6f60cf1a861fb9b5a4af5f4f916b6d0e416bef64",
  "dataDirectory": "C:\\Users\\Corey\\AppData\\Roaming\\trilium-data",
  "clipperProtocolVersion": "1.0"
}
CPU model: AMD Ryzen 9 5950X 16-Core Processor            , logical cores: 32 freq: 3400 Mhz
Listening on port 37840
Created backup at C:\Users\Corey\AppData\Roaming\trilium-data\backup/backup-before-migration.db
ERROR: Direct migration from your current version is not supported. Please upgrade to the latest v0.47.X first and only then to this version.
The database connection is not open
The database connection is not open
TypeError: sql.getRawRows is not a function or its return value is not iterable
    at load (C:\Users\Corey\Downloads\trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:32:27)
    at C:\Users\Corey\Downloads\trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:17:9
TypeError: sql.getRawRows is not a function or its return value is not iterable
    at load (C:\Users\Corey\Downloads\trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:32:27)
    at C:\Users\Corey\Downloads\trilium\trilium-windows-x64\resources\app.asar\src\becca\becca_loader.js:17:9
Error: Option "spellCheckEnabled" doesn't exist
    at getOption (C:\Users\Corey\Downloads\trilium\trilium-windows-x64\resources\app.asar\src\services\options.js:7:15)
    at Object.getOptionBool (C:\Users\Corey\Downloads\trilium\trilium-windows-x64\resources\app.asar\src\services\options.js:32:17)
    at Object.createMainWindow (C:\Users\Corey\Downloads\trilium\trilium-windows-x64\resources\app.asar\src\services\window.js:51:45)
    at App.<anonymous> (C:\Users\Corey\Downloads\trilium\trilium-windows-x64\resources\app.asar\electron.js:32:29)
Error: Option "spellCheckEnabled" doesn't exist
    at getOption (C:\Users\Corey\Downloads\trilium\trilium-windows-x64\resources\app.asar\src\services\options.js:7:15)
    at Object.getOptionBool (C:\Users\Corey\Downloads\trilium\trilium-windows-x64\resources\app.asar\src\services\options.js:32:17)
    at Object.createMainWindow (C:\Users\Corey\Downloads\trilium\trilium-windows-x64\resources\app.asar\src\services\window.js:51:45)
    at App.<anonymous> (C:\Users\Corey\Downloads\trilium\trilium-windows-x64\resources\app.asar\electron.js:32:29)
```

**Comment by CorneliousJD** [comment]
Well, I was able to go in adn delete this folder to start fresh fresh (I had an old test install a while back) and it seems to be opening/working now. Very weird, perhaps still a bug that needs to be addressed so I'll leave this open so you can review.

Thank you, sorry for all the new notifications this may have caused you.

PS - The old icon still exists on the web clipper and trilium-sender android app, not sure how often you update those but the old icon still shows up on those. not sure how recent the new icon is ;)

**Comment by zadam** [comment]
Hi, the old `trilium-data` directory was found by your new installation so it wasn't totally new set up. Because of big changes in 0.48 it's not possible to directly migrate from too old databases and it needs either a delete (like you did) or in-between installation of 0.47 which will migrate the DB.

The icon is new in 0.48 and is not yet updated on sender and web clipper which have slower release cycles.
