### ISSUE TITLE
Error GLIBC_2.28

### ISSUE THREAD

**Issue by N4d4** [zadam/trilium#246]
My system:
```
OS: Debian GNU/Linux testing (buster) x86_64 
Kernel: 4.18.0-2-amd64  
nodejs: v8.14.0
```
I've downloaded [this build](https://github.com/zadam/trilium/releases/download/v0.24.5/trilium-linux-x64-0.24.5.7z) and this happen when I try to run it:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/nada/Scrivania/trilium-linux-x64/resources/app/node_modules/sqlite3/lib/binding/electron-v4.0-linux-x64/node_sqlite3.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/nada/Scrivania/trilium-linux-x64/resources/app/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Object.<anonymous> (/home/nada/Scrivania/trilium-linux-x64/resources/app/node_modules/sqlite3/lib/sqlite3.js:190:3)
```

**Comment by zadam** [comment]
Unfortunately it looks like Glibc 2.28 is not in testing yet (it is in unstable). Binary build of Trilium assumes up to date distribution. I think that the only possible solution to this (general) problem is to provide flatpak or distro-specific packages ...

**Comment by sorinsfirlogea** [comment]
any chance for distro packages? or a flatpak?

**Comment by zadam** [comment]
Hello, since 0.25.1-beta I use precompiled binaries for sqlite which link against 2.27 - so 18.04 and debian testing should be supported. Previously this depended on platform I was building on (which was Ubuntu 18.10 with glibc 2.28 - and this caused the issue).
