### ISSUE TITLE
(Bug report) - 49.1 beta - Sharing: Cannot read properties of undefined (reading 'noteID')

### ISSUE THREAD

**Issue by netnem** [zadam/trilium#2484]
### Trilium Version

0.49.1-beta

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Windows 10

### Description

Recently upgraded from 48.8 to 49.1-Beta to test new features (manual install).  I did upgrade to NodeJS 16.13.1 and npm 8.3.0 as part of this upgrade.

When trying to share a note the following error is reported:

```
ERROR: put /api/notes/:noteId/clone-to/:parentBranchId threw exception: TypeError: Cannot read properties of undefined (reading 'noteId')
    at Object.cloneNoteToParent (/root/trilium/src/services/cloning.js:22:61)
    at cloneNoteToParent (/root/trilium/src/routes/api/cloning.js:9:27)
    at Function.cb (/root/trilium/src/routes/routes.js:146:34)
    at Function.sqliteTransaction (/root/trilium/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (/root/trilium/src/services/sql.js:223:52)
    at /root/trilium/src/routes/routes.js:148:44
    at /root/trilium/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/root/trilium/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/root/trilium/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/root/trilium/src/services/cls.js:5:22)
JS Error: Error when calling PUT notes/Zv7n8ofjXs1C/clone-to/share: error - Internal Server Error
Stack: Error
    at Object.logError (https://mydomain.com/app/services/ws.js:23:20)
    at Object.throwError (https://mydomain.com/app/services/toast.js:87:8)
    at reportError (https://mydomain.com/app/services/server.js:106:18)
    at async Object.error (https://mydomain.com/app/services/server.js:131:17)
```

**Comment by netnem** [comment]
Some additional tests: I installed the docker version of 49.1-beta and synced it to existing server and it still had the "JS Error: Error .... - Internal Server Error."  I then installed the docker 49.1-neta version "fresh" (no sync, new install) and then imported my 48.9 .zip export into the docker and everything worked as intended.  So I think this may be a database issue from the older versions to this version.

**Comment by zadam** [comment]
Hi, thanks for reporting this issue.

The sharing relied on a specific (branch) ID to exist, this should be done by a migration script but there might be some special case where it did not work properly.

I implemented this in a better way so it does not rely on this specific branchId anymore.
