### ISSUE TITLE
(Bug report) Can't close new window opened in menu -> "Open new window"

### ISSUE THREAD

**Issue by sigaloid** [zadam/trilium#2502]
### Trilium Version

0.49.1-beta

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Fedora

### Description

```
JS Error: Uncaught error: Message: Uncaught Error: @electron/remote is disabled for this WebContents. Call require("@electron/remote/main").enable(webContents) to enable it., URL: /usr/lib/trilium/resources/app.asar/node_modules/@electron/remote/dist/src/renderer/remote.js, Line: 270, Column: 13, Error object: {}, Stack: Error: @electron/remote is disabled for this WebContents. Call require("@electron/remote/main").enable(webContents) to enable it.
    at IpcMainImpl.<anonymous> (/usr/lib/trilium/resources/app.asar/node_modules/@electron/remote/dist/src/main/server.js:317:61)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:10774)
    at Object.emit (node:events:394:28)
    at Object.callbackTrampoline (node:internal/async_hooks:130:17)
Stack: Error
    at Object.N [as logError] (http://127.0.0.1:37840/app-dist/desktop.js:2:99321)
    at window.onerror (http://127.0.0.1:37840/app-dist/desktop.js:2:398543)
```

I'm on Wayland, if that makes a difference.

It won't let me close the new window, straight up just doesn't close at all unless I ctrl+q (which closes all windows)

**Comment by zadam** [comment]
Hi, thanks for reporting, this is related to the electron 16 update.
