### ISSUE TITLE
(Bug report) database update failed

### ISSUE THREAD

**Issue by JustinWuCN** [zadam/trilium#2514]
### Trilium Version

0.49.2-beta

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

ubuntu20.04

### Description

I am used 0.47.7 version before. and then upgrade to 0.49.2-beta.
on trilium.sh start . it show need to update db, but migration failed.

how can I update the version with my data??

```

App db version is 188, while db version is 183. Migration needed.
DB size: 3850 KB
App HTTP server starting up at port 8080
{
  "appVersion": "0.49.2-beta",
  "dbVersion": 188,
  "syncVersion": 23,
  "buildDate": "2022-01-02T22:43:30+01:00",
  "buildRevision": "feffd57f240438d107c1ed1c1772545611a97dee",
  "dataDirectory": "/home/justin/.local/share/trilium-data",
  "clipperProtocolVersion": "1.0"
}
CPU model: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz, logical cores: 12 freq: 2900 Mhz
Listening on port 8080
Created backup at /home/justin/.local/share/trilium-data/backup/backup-before-migration.db
Attempting migration to version 184
Migration with JS module
Becca (note cache) load took 6ms
ERROR: error during migration to version 184: SqliteError: table entity_changes has no column named changeId
    at Database.prepare (/home/justin/sda/work/trilium/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at stmt (/home/justin/sda/work/trilium/src/services/sql.js:77:44)
    at wrap (/home/justin/sda/work/trilium/src/services/sql.js:193:23)
    at execute (/home/justin/sda/work/trilium/src/services/sql.js:157:12)
    at insert (/home/justin/sda/work/trilium/src/services/sql.js:39:17)
    at Object.replace (/home/justin/sda/work/trilium/src/services/sql.js:45:12)
    at Object.addEntityChange (/home/justin/sda/work/trilium/src/services/entity_changes.js:23:17)
    at Attribute.addEntityChange (/home/justin/sda/work/trilium/src/becca/entities/abstract_entity.js:50:30)
    at Function.<anonymous> (/home/justin/sda/work/trilium/src/becca/entities/abstract_entity.js:83:18)
    at Function.sqliteTransaction (/home/justin/sda/work/trilium/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
ERROR: migration failed, crashing hard
```

**Comment by JustinWuCN** [comment]
I resolove this problem.

using sqlitebrower to open document.db file, 
and edit `entity_changes`, add one cloumn with name "changeId".

then the database is upgrade successful.


this question can be closed.

**Comment by zadam** [comment]
Hello, I'm glad you managed to resolve the issue on your own.

But it is actually a bug in migration, thanks to your report I was able to fix it.
