### ISSUE TITLE
(Bug report) Random notes lose their content, old revs. still available, last modified date untouched.

### ISSUE THREAD

**Issue by U-Bren** [zadam/trilium#2549]
### Trilium Version

0.49.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Win 10 pro version 20H2 build 19042.1288

### Description

Hi, first I apologize if some of the details are off-topic, but as I only recently discovered the breadth of the data loss I can only try to remember what I was doing around that time.

First, as mentioned in the title, old note revisions (if they existed, as contrary to if the note's content (inc. images) were to be manually deleted, no reversion was generated, and the "modified" dated isn't updated) are still available, and the issue seems to be document-wide (affecting multiple unrelated note trees).

In some cases, every subnote is blanked (for example note ```uaaHtSR951lR```), while in other cases (the ```x7225n2oaXj2``` tree) only some of them are blanked (```GgzF5PaBOgsx```,```E0YgVnLuPaoI```,```a4wke5LqZxiq```) while other are fine (```UKhTgQFM9Vc9```, ```zChD3gxBiEOA```)

The latest reversion date that I could find amongst affected notes seems to be on the 2021-12-21.

History of the document:
The original setup a Local + server sync one, but when upgrading from 0.46 to 0.47 I didn't bother to upgrade the server.
A few versions later, I finally updated the server and tried to restart the sync.
However, the synchronization simply failed, and so I deleted the server-side trilium data dir and restarted it, which didn't help, though I think that the error changed at that moment (```sync failed: Entity recent_notes 10ANViztOPp1 not found.```).
I then used "force full sync" and "fix consistency issues", which solved the synchronization problem.
It was around that time I think that I noticed that some of my notes were blank, but I thought nothing of it as the few others notes I used this day were fine.

Affected notes (as examples):
```GgzF5PaBOgsxx7225n2oaXj2``` (all subtree)

I understand that it might be difficult to pinpoint the exact cause of this issue, and I don't really expect to recover the data, through some help would be appreciated to, if possible 1) identify every effected note and 2) ease the recovery from backups.

Thanks

**Comment by zadam** [comment]
Hi, thanks for the report. I will try to take a look at this tomorrow.

**Comment by U-Bren** [comment]
Also, I have noticed that when restoring from recent changes a note affected by this bug, any attempt to interact with it seems sluggish, eg. the editor stay stuck displaying another note content, and more importantly, trying to delete the note again simply doesn't work (some help here would be appreciated 😂).

Here's the (relevant parts) of the backend log from trying to delete a bugged note that was restored using recent change.

Some context:
- Trying to delete note with ID ```DmHEur0zSypD```
- This note has 9 subnotes
- One of those 9 subnotes is called "Résumé", and has a subnote called "Ressources".
- **Trying to select "Résumé" or "Ressources" dosen't update the editor pane. Trying to right click on it dosen't open the right click menu.**
![image](https://user-images.githubusercontent.com/30356110/149621715-57e207bd-ea6c-4848-9ef3-5e7b28d0a456.png)




<details><summary>**Relevant parts of the log (can provide the entire file if needed):**</summary>
<p>
```
13:11:16.467 200 POST /api/delete-notes-preview with 225 bytes took 1ms
13:11:16.473 JS Error: No parents found for kMy8k4pyOdfh (Ressources) for path kMy8k4pyOdfh
Stack: Error
    at Object.N [as logError] (http://127.0.0.1:37840/app-dist/desktop.js:2:99691)
    at Object.l [as resolveNotePathToSegments] (http://127.0.0.1:37840/app-dist/desktop.js:2:85796)
    at async Object.createNoteLink (http://127.0.0.1:37840/app-dist/desktop.js:2:51367)
    at async N (http://127.0.0.1:37840/app-dist/263.desktop.js:1:919)
    at async Module.Z (http://127.0.0.1:37840/app-dist/263.desktop.js:1:1416)
    at async Object.deleteNotes (http://127.0.0.1:37840/app-dist/desktop.js:2:24652)
    at async B.deleteNotesCommand (http://127.0.0.1:37840/app-dist/desktop.js:2:169453)
    at async B.callMethod (http://127.0.0.1:37840/app-dist/desktop.js:2:107068)
13:11:20.212 No connection to sync server.
13:12:20.226 No connection to sync server.
13:12:20.234 200 GET /api/backend-log with 69288 bytes took 1ms
13:12:36.286 200 GET /api/notes/DmHEur0zSypD with 431 bytes took 0ms
13:12:41.178 200 POST /api/delete-notes-preview with 225 bytes took 2ms
13:12:41.205 JS Error: No parents found for kMy8k4pyOdfh (Ressources) for path kMy8k4pyOdfh
Stack: Error
    at Object.N [as logError] (http://127.0.0.1:37840/app-dist/desktop.js:2:99691)
    at Object.l [as resolveNotePathToSegments] (http://127.0.0.1:37840/app-dist/desktop.js:2:85796)
    at async Object.createNoteLink (http://127.0.0.1:37840/app-dist/desktop.js:2:51367)
    at async N (http://127.0.0.1:37840/app-dist/263.desktop.js:1:919)
    at async Module.Z (http://127.0.0.1:37840/app-dist/263.desktop.js:1:1416)
    at async Object.deleteNotes (http://127.0.0.1:37840/app-dist/desktop.js:2:24652)
    at async B.deleteNotesCommand (http://127.0.0.1:37840/app-dist/desktop.js:2:169453)
    at async B.callMethod (http://127.0.0.1:37840/app-dist/desktop.js:2:107068)
13:12:43.342 200 GET /api/backend-log with 70275 bytes took 1ms
13:13:01.467 200 GET /api/tree?subTreeNoteId=XdFYJD0BlCpk with 639 bytes took 0ms
13:13:01.689 JS Error: Cannot find branch=RruMd8qZLixR
Stack: Error
    at N (http://127.0.0.1:37840/app-dist/desktop.js:2:99691)
    at B.setExpanded (http://127.0.0.1:37840/app-dist/desktop.js:2:168125)
    at HTMLDivElement.expand (http://127.0.0.1:37840/app-dist/desktop.js:2:156654)
    at _.<computed>.<computed>._trigger (http://127.0.0.1:37840/libraries/fancytree/jquery.fancytree-all-deps.min.js:1:7715)
    at P._triggerNodeEvent (http://127.0.0.1:37840/libraries/fancytree/jquery.fancytree-all-deps.min.js:1:41920)
    at O.<anonymous> (http://127.0.0.1:37840/libraries/fancytree/jquery.fancytree-all-deps.min.js:1:56645)
    at c (http://127.0.0.1:37840/libraries/jquery.min.js:2:28327)
    at Object.fireWith [as resolveWith] (http://127.0.0.1:37840/libraries/jquery.min.js:2:29072)
    at http://127.0.0.1:37840/libraries/fancytree/jquery.fancytree-all-deps.min.js:1:57558
    at HTMLUListElement.always (http://127.0.0.1:37840/libraries/fancytree/jquery.fancytree-all-deps.min.js:1:57171)
13:13:02.764 JS Error: No parents found for XdFYJD0BlCpk (Résumé) for path root/DAGekjFVsJ66/cDOiKwrCOuom/cCTeY4hiAcze/DmHEur0zSypD/XdFYJD0BlCpk/kMy8k4pyOdfh
Stack: Error
    at Object.N [as logError] (http://127.0.0.1:37840/app-dist/desktop.js:2:99691)
    at l (http://127.0.0.1:37840/app-dist/desktop.js:2:85796)
    at async Object.resolveNotePath (http://127.0.0.1:37840/app-dist/desktop.js:2:87769)
    at async I.getResolvedNotePath (http://127.0.0.1:37840/app-dist/desktop.js:2:9484)
    at async I.setNote (http://127.0.0.1:37840/app-dist/desktop.js:2:8513)
    at async HTMLDivElement.activate (http://127.0.0.1:37840/app-dist/desktop.js:2:156542)
13:13:02.764 JS Error: Cannot resolve note path root/DAGekjFVsJ66/cDOiKwrCOuom/cCTeY4hiAcze/DmHEur0zSypD/XdFYJD0BlCpk/kMy8k4pyOdfh
Stack: Error
    at N (http://127.0.0.1:37840/app-dist/desktop.js:2:99691)
    at I.getResolvedNotePath (http://127.0.0.1:37840/app-dist/desktop.js:2:9613)
    at async I.setNote (http://127.0.0.1:37840/app-dist/desktop.js:2:8513)
    at async HTMLDivElement.activate (http://127.0.0.1:37840/app-dist/desktop.js:2:156542)
13:13:03.846 JS Error: No parents found for XdFYJD0BlCpk (Résumé) for path root/DAGekjFVsJ66/cDOiKwrCOuom/cCTeY4hiAcze/DmHEur0zSypD/XdFYJD0BlCpk
Stack: Error
    at Object.N [as logError] (http://127.0.0.1:37840/app-dist/desktop.js:2:99691)
    at l (http://127.0.0.1:37840/app-dist/desktop.js:2:85796)
    at async Object.resolveNotePath (http://127.0.0.1:37840/app-dist/desktop.js:2:87769)
    at async I.getResolvedNotePath (http://127.0.0.1:37840/app-dist/desktop.js:2:9484)
    at async I.setNote (http://127.0.0.1:37840/app-dist/desktop.js:2:8513)
    at async HTMLDivElement.activate (http://127.0.0.1:37840/app-dist/desktop.js:2:156542)
13:13:03.846 JS Error: Cannot resolve note path root/DAGekjFVsJ66/cDOiKwrCOuom/cCTeY4hiAcze/DmHEur0zSypD/XdFYJD0BlCpk
Stack: Error
    at N (http://127.0.0.1:37840/app-dist/desktop.js:2:99691)
    at I.getResolvedNotePath (http://127.0.0.1:37840/app-dist/desktop.js:2:9613)
    at async I.setNote (http://127.0.0.1:37840/app-dist/desktop.js:2:8513)
    at async HTMLDivElement.activate (http://127.0.0.1:37840/app-dist/desktop.js:2:156542)
13:13:11.198 200 POST /api/delete-notes-preview with 225 bytes took 1ms
13:13:11.217 JS Error: No parents found for XdFYJD0BlCpk (Résumé) for path XdFYJD0BlCpk
Stack: Error
    at Object.N [as logError] (http://127.0.0.1:37840/app-dist/desktop.js:2:99691)
    at Object.l [as resolveNotePathToSegments] (http://127.0.0.1:37840/app-dist/desktop.js:2:85796)
    at async Object.createNoteLink (http://127.0.0.1:37840/app-dist/desktop.js:2:51367)
    at async N (http://127.0.0.1:37840/app-dist/263.desktop.js:1:919)
    at async Module.Z (http://127.0.0.1:37840/app-dist/263.desktop.js:1:1416)
    at async Object.deleteNotes (http://127.0.0.1:37840/app-dist/desktop.js:2:24652)
    at async B.deleteNotesCommand (http://127.0.0.1:37840/app-dist/desktop.js:2:169453)
    at async B.callMethod (http://127.0.0.1:37840/app-dist/desktop.js:2:107068)
```
</p>
</details>

**Comment by eliandoran** [comment]
Although the level of detail of the issue is impressive, I'm going to close it as stale since it's a very old version (0.49.4).
