### ISSUE TITLE
(Bug report) Error: Invalid CSRF token

### ISSUE THREAD

**Issue by dyyd** [zadam/trilium#2565]
### Trilium Version

0.49.4

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Linux

### Description

Server running in docker with image `zadam/trilium:0.49.4`.
Client using Trilium desktop app for Linux (debian).

Client getting error popups, server logging:
```
ERROR: Invalid CSRF token: ypHo1UdZ-mxv56FHowql5XklXaOqiSuLXvJo, secret: 09U2ZJPtRRVrRiw6mgVnxC3s
Error: Invalid CSRF token
    at /usr/src/app/src/app.js:64:11
    at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:321:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:341:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/node_modules/express/lib/router/index.js:641:15
    at next (/usr/src/app/node_modules/express/lib/router/index.js:260:14)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:127:14)
    at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:67:12) {
  status: 403
}
JS Error: Error when calling PUT notes/kBAfqwpQvgWF: error - Forbidden
Stack: logError@https://<server host, proxied>/app/services/ws.js:23:20
throwError@https://<server host>/app/services/toast.js:87:8
reportError@https://<server host>/app/services/server.js:106:18
```

The error started after switching both from version 0.45.8 to version 0.49.4.

So far no data loss has been noted and changes made in client app are also available when client connects through web browser. However the errors are concerning and degrading the user experience.

**Comment by zadam** [comment]
Hi, could you try refreshing cache (`CTRL-SHIFT-R`) if it helps?

**Comment by dyyd** [comment]
Hmm, sees that indeed this has helped. Haven't encountered this issue for a while now.
