### ISSUE TITLE
(Bug report) Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by attzonko** [zadam/trilium#2578]
### Trilium Version

0.49-latest

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu 20.04.3 LTS

### Description

Running this using Docker. On initial bring-up, got the welcome page where I chose the settings and then after submitting got a black screen. 
Server Set-up: Running docker and traefik as reverse proxy
Client: Chrome Browser

Here is the log error I see in the docker container log:
```
2022-01-18T21:09:14.854993414Z Schema and initial content generated.
2022-01-18T21:09:14.858558770Z Becca (note cache) load took 3ms
2022-01-18T21:09:14.859579596Z Slow 204 POST /api/setup/new-document with 0 bytes took 575ms
2022-01-18T21:09:15.080513821Z Triggering sync.
2022-01-18T21:09:15.110257424Z Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
2022-01-18T21:09:15.110278029Z     at new NodeError (node:internal/errors:371:5)
2022-01-18T21:09:15.110283497Z     at ServerResponse.setHeader (node:_http_outgoing:576:11)
2022-01-18T21:09:15.110301679Z     at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:776:10)
2022-01-18T21:09:15.110306496Z     at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
2022-01-18T21:09:15.110310286Z     at done (/usr/src/app/node_modules/express/lib/response.js:1013:10)
2022-01-18T21:09:15.110314003Z     at tryHandleCache (/usr/src/app/node_modules/ejs/lib/ejs.js:278:5)
2022-01-18T21:09:15.110317649Z     at View.exports.renderFile [as engine] (/usr/src/app/node_modules/ejs/lib/ejs.js:489:10)
2022-01-18T21:09:15.110321429Z     at View.render (/usr/src/app/node_modules/express/lib/view.js:135:8)
2022-01-18T21:09:15.110325067Z     at tryRender (/usr/src/app/node_modules/express/lib/application.js:640:10)
2022-01-18T21:09:15.110328716Z     at Function.render (/usr/src/app/node_modules/express/lib/application.js:592:3) {
2022-01-18T21:09:15.110332467Z   code: 'ERR_HTTP_HEADERS_SENT'
2022-01-18T21:09:15.110336428Z }
2022-01-18T21:09:15.112960025Z Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
2022-01-18T21:09:15.112975806Z     at new NodeError (node:internal/errors:371:5)
2022-01-18T21:09:15.112980948Z     at ServerResponse.setHeader (node:_http_outgoing:576:11)
2022-01-18T21:09:15.112985273Z     at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:776:10)
2022-01-18T21:09:15.112989279Z     at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
2022-01-18T21:09:15.112993163Z     at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:267:15)
2022-01-18T21:09:15.112996923Z     at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:158:21)
2022-01-18T21:09:15.113000706Z     at /usr/src/app/src/app.js:89:9
2022-01-18T21:09:15.113004338Z     at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:71:5)
2022-01-18T21:09:15.113008179Z     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:321:13)
2022-01-18T21:09:15.113011900Z     at /usr/src/app/node_modules/express/lib/router/index.js:284:7
2022-01-18T21:09:18.862138620Z Table counts: notes: 166, note_revisions: 0, branches: 184, attributes: 241, api_tokens: 0
2022-01-18T21:09:18.869521269Z All consistency checks passed with no errors detected (took 8ms)
```

**Comment by zadam** [comment]
Hi, could you reload the page? Based on the log the setup succeeded.

IIRC I've already fixed this bug in master.

**Comment by attzonko** [comment]
Interestingly it ended up being the ADGUARD Adblocker which was preventing the page to load anything.

**Comment by attzonko** [comment]
It was complaining about https://trilium.example.com/app/widgets/backlinks.js being blocked due to some '/backlinks' rule.
