### ISSUE TITLE
arm64 client

### ISSUE THREAD

**Issue by bill88t** [zadam/trilium#2613]
Hello! I'm trying to build & run the trilium client for my Raspberry Pi 400. (Running Raspberry Pi OS 64-bit)<br />
After changing around some strings from amd64 to arm64 it built successfully, however upon running it I get:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.vkPqxi: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2027)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at bindings (/buildir/trilium/dist/trilium-linux-arm64/resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/buildir/trilium/dist/trilium-linux-arm64/resources/app.asar/node_modules/better-sqlite3/lib/database.js:9:24)
```
Am I doing something wrong or it genuinely won't run on arm64?<br /><br />

my steps were:<br /><br />

git clone<br />
git checkout v0.49.5<br /> (did try 0.50.1 too)
npm install<br />
npm rebuild<br />
edit bin/build-linux-x64.sh, bin/build-debian.sh, deb-options.json to do arm64 instead of amd64<br />
remove a few lines from bin/build-debian.sh about the repackaging, as it was not necessary by the looks of it<br />
then after installing & running it I got the error.

**Comment by Myzel394** [comment]
Have you tried running one of the [releases](https://github.com/zadam/trilium/releases)? ([maybe this release?](https://github.com/zadam/trilium/releases/download/v0.50.1/trilium_0.50.1_amd64.deb))

**Comment by bill88t** [comment]
I'm trying to build **ARM** 64 (arm64), not amd64 (aka x64).
Trilium at the moment doesn't not have client builds for arm at all.

**Comment by bill88t** [comment]
No I, not very long after, stopped using the project.
