### ISSUE TITLE
(Bug report) Option "passwordVerificationSalt" doesn't exist

### ISSUE THREAD

**Issue by Evisolpxe** [zadam/trilium#2685]
### Trilium Version

v0.50.2 release

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows10

### Description

I just installed server by docker and synced desktop instance to server successfully. 
But when using another desktop instance for initital syncing, error show below:
` 
Sync setup failed: Request to get http://xxxx/api/setup/sync-seed failed, error: 500 Internal Server Error
`
Checked docker log:
```
304 GET /api/sync/check with 8696 bytes took 5ms
Error: Option "passwordVerificationSalt" doesn't exist
    at Object.getOption (/usr/src/app/src/services/options.js:21:15)
    at Object.getVerificationHash (/usr/src/app/src/services/my_scrypt.js:7:32)
    at Object.verifyPassword (/usr/src/app/src/services/password_encryption.js:7:62)
    at checkCredentials (/usr/src/app/src/services/auth.js:105:36)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:341:12)
```
I tried to restart docker instance and it be fixed...guess a bug or not?

**Comment by zadam** [comment]
Hi, thanks for reporting the error.

The error is not very descriptive, but it means that the server does not have a password set yet, without it, it is not possible to set up a sync from a server to client. This password requirement is not really obvious and isn't well communicated.

One thing, you mentioned that the error fixed itself with restart, but that does not seem probable to me. Did you perhaps after the restart set up the password and then retried the sync setup?

**Comment by Evisolpxe** [comment]
> Hi, thanks for reporting the error.
> 
> The error is not very descriptive, but it means that the server does not have a password set yet, without it, it is not possible to set up a sync from a server to client. This password requirement is not really obvious and isn't well communicated.
> 
> One thing, you mentioned that the error fixed itself with restart, but that does not seem probable to me. Did you perhaps after the restart set up the password and then retried the sync setup?

It made me realise that the error probably originated from sync initialisation, becasue I setted a password before first server sync. I guess docker restart triggers password initialisation so it be fixed.
