### ISSUE TITLE
(Bug report) v0.51.0-beta shared notes are invalid

### ISSUE THREAD

**Issue by flysaber** [zadam/trilium#2791]
### Trilium Version

v0.51.0-beta

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

win10,ubuntu20.04

### Description

I upgrade to the latest version v0 51.0-beta, it is found that all shared notes are invalid and cannot be shared, prompt

{"message":"Cannot set properties of undefined (setting 'isHidden')"}

**Comment by zadam** [comment]
Hi, could you please share the backend logs (files in `trilium-data/log` directory)? Thanks.

**Comment by ygbillet** [comment]
Same problem.

This is the output from console. 
Not so much information on trilium-data/log

```
TypeError: Cannot set properties of undefined (setting 'isHidden')
    at new Attribute (/usr/src/app/src/share/shaca/entities/attribute.js:39:33)
    at load (/usr/src/app/src/share/shaca/shaca_loader.js:65:9)
    at Object.ensureLoad (/usr/src/app/src/share/shaca/shaca_loader.js:75:9)
    at /usr/src/app/src/share/routes.js:67:21
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
    at param (/usr/src/app/node_modules/express/lib/router/index.js:360:14)
```

**Comment by zadam** [comment]
Hi, thanks for the log. Yes, this is a regression, please downgrade back to latest stable until there's a new release (in a couple of days).
