### ISSUE TITLE
(Bug report) After update to trilium-linux-x64-server-0.50.3.tar.xz restart error

### ISSUE THREAD

**Issue by agent-kimbley** [zadam/trilium#2796]
### Trilium Version

0.48.9

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

arch

### Description

```
Stack: Error
    at Object.N [as logError] (http://192.168.11.2:4444/app-dist/desktop.js:2:100779)
    at Object.throwError (http://192.168.11.2:4444/app-dist/desktop.js:2:85945)
    at c (http://192.168.11.2:4444/app-dist/desktop.js:2:82694)
    at async Object.error (http://192.168.11.2:4444/app-dist/desktop.js:2:83002)
304 GET /api/keyboard-shortcuts-for-notes with 2 bytes took 2ms
304 GET /api/script/widgets with 2 bytes took 2ms
JS Error: Error when calling GET tree: error - Not Found
Stack: Error
    at Object.N [as logError] (http://192.168.11.2:4444/app-dist/desktop.js:2:100779)
    at Object.throwError (http://192.168.11.2:4444/app-dist/desktop.js:2:85945)
    at c (http://192.168.11.2:4444/app-dist/desktop.js:2:82694)
    at async Object.error (http://192.168.11.2:4444/app-dist/desktop.js:2:83002)
Generated CSRF token cufbSHtq-SUJ44ntxhBbsbiRhixeq7HGXs34 with secret undefined
304 GET /api/options with 25 bytes took 2ms
GET /api/tree returned 404 with response "Note root not found in the cache"
404 GET /api/tree with 32 bytes took 2ms
304 GET /api/keyboard-actions with 11382 bytes took 3ms
304 GET /api/keyboard-shortcuts-for-notes with 2 bytes took 2ms
304 GET /api/script/widgets with 2 bytes took 2ms
websocket client connected
JS Error: Error when calling GET tree: error - Not Found
Stack: Error
    at Object.N [as logError] (http://192.168.11.2:4444/app-dist/desktop.js:2:100779)
    at Object.throwError (http://192.168.11.2:4444/app-dist/desktop.js:2:85945)
    at c (http://192.168.11.2:4444/app-dist/desktop.js:2:82694)
    at async Object.error (http://192.168.11.2:4444/app-dist/desktop.js:2:83002)
Generated CSRF token ezV9tIPx--EIHfZ14uiyFVWr1WU-7Lyucu1k with secret undefined
304 GET /api/options with 25 bytes took 2ms
GET /api/tree returned 404 with response "Note root not found in the cache"
404 GET /api/tree with 32 bytes took 3ms
304 GET /api/keyboard-actions with 11382 bytes took 3ms
304 GET /api/keyboard-shortcuts-for-notes with 2 bytes took 2ms
304 GET /api/script/widgets with 2 bytes took 2ms
websocket client connected
JS Error: Error when calling GET tree: error - Not Found
Stack: Error
    at Object.N [as logError] (http://192.168.11.2:4444/app-dist/desktop.js:2:100779)
    at Object.throwError (http://192.168.11.2:4444/app-dist/desktop.js:2:85945)
    at c (http://192.168.11.2:4444/app-dist/desktop.js:2:82694)
    at async Object.error (http://192.168.11.2:4444/app-dist/desktop.js:2:83002)
JS Error: Uncaught error: Message: Uncaught TypeError: Cannot read properties of undefined (reading 'switchToNoteContext'), URL: http://192.168.11.2:4444/app-dist/desktop.js, Line: 2, Column: 21573, Error object: {}, Stack: TypeError: Cannot read properties of undefined (reading 'switchToNoteContext')
    at http://192.168.11.2:4444/app-dist/desktop.js:2:21573
    at dispatch (http://192.168.11.2:4444/libraries/jquery.min.js:2:43064)
    at v.handle (http://192.168.11.2:4444/libraries/jquery.min.js:2:41048)
Stack: Error
    at Object.N [as logError] (http://192.168.11.2:4444/app-dist/desktop.js:2:100779)
    at Ue.window.onerror (http://192.168.11.2:4444/app-dist/desktop.js:2:401387)
websocket client connected
```

**Comment by agent-kimbley** [comment]
After I input password and chrome alter me 'Error when calling GET tree: error - Not Found' with blank page.
How do I do？
Thank.

**Comment by zadam** [comment]
Hello, sorry for late response. Could you send the whole log to zadam.apps@gmail.com? This would help me to understand the problem better. Thanks!

In the meantime it would be the best to continue using the old version.

**Comment by tbnorth** [comment]
FWIW I'm seeing this too, was working fine after upgrade for some time but suddenly doing the
```
Generated CSRF token kj1FRxhe-1H2IJcz4qtHTAu6l_ixB58mz8W4 with secret undefined
websocket client connected
304 GET /api/options with 6705 bytes took 1ms
304 GET /api/tree with 252618 bytes took 5ms
Keyboard action showNoteInfo found in database, but not in action definition.
Keyboard action showLinkMap found in database, but not in action definition.
Keyboard action focusOnAttributes found in database, but not in action definition.
Keyboard action toggleZenMode found in database, but not in action definition.
304 GET /api/keyboard-actions with 11756 bytes took 3ms
304 GET /api/keyboard-shortcuts-for-notes with 2 bytes took 1ms
304 GET /api/script/widgets with 2930 bytes took 2ms
200 POST /api/tree/load with 2688 bytes took 1ms
JS Error: Uncaught error: Message: Uncaught TypeError: Cannot read properties of undefined (reading 'switchToNoteContext'), URL: http://127.0.0.1:38080/app/services/app_context.js, Line: 164, Column: 31, Error object: {}, Stack: TypeError: Cannot read properties of undefined (reading 'switchToNoteContext')
    at http://127.0.0.1:38080/app/services/app_context.js:164:31
    at dispatch (http://127.0.0.1:38080/libraries/jquery.min.js:2:43064)
    at v.handle (http://127.0.0.1:38080/libraries/jquery.min.js:2:41048)
Stack: Error
    at Object.logError (http://127.0.0.1:38080/app/services/ws.js:23:20)
    at window.onerror (http://127.0.0.1:38080/app/services/glob.js:65:12)
```
thing on all links.
