### ISSUE TITLE
(Bug report) SqliteError: disk I/O error on deploying docker image to DigitalOcean

### ISSUE THREAD

**Issue by surajsharma** [zadam/trilium#2839]
### Trilium Version

latest

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Linux

### Description

tried deploying the docker image (latest) to digitalocean as an app but get the following error during the deployment:

```
[2022-05-07 15:40:45] Generated session secret
[2022-05-07 15:40:46] 
[2022-05-07 15:40:46] /usr/src/app/src/services/sql.js:217
[2022-05-07 15:40:46]         throw e;
[2022-05-07 15:40:46]         ^
[2022-05-07 15:40:46] SqliteError: disk I/O error
[2022-05-07 15:40:46]     at /usr/src/app/src/services/sql.js:95:39
[2022-05-07 15:40:46]     at wrap (/usr/src/app/src/services/sql.js:206:18)
[2022-05-07 15:40:46]     at Object.getValue (/usr/src/app/src/services/sql.js:95:12)
[2022-05-07 15:40:46]     at Object.<anonymous> (/usr/src/app/src/services/sql_init.js:180:28)
[2022-05-07 15:40:46]     at Module._compile (node:internal/modules/cjs/loader:1103:14)
[2022-05-07 15:40:46]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
[2022-05-07 15:40:46]     at Module.load (node:internal/modules/cjs/loader:981:32)
[2022-05-07 15:40:46]     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[2022-05-07 15:40:46]     at Module.require (node:internal/modules/cjs/loader:1005:19)
[2022-05-07 15:40:46]     at require (node:internal/modules/cjs/helpers:102:18)

```

what gives?

**Comment by zadam** [comment]
You have probably some misconfiguration. SQLite is not able to write to the disk. Might be read only, permissions or something else ...

**Comment by sigaloid** [comment]
What's the exact docker run command you used? The example given in the docs might have to be modified to point to a permissions-allowed or existent directory
