### ISSUE TITLE
export issue:Trace: ERROR: Error executing transaction, executing rollback.

### ISSUE THREAD

**Issue by lingjiao0710** [zadam/trilium#285]
Trace: ERROR: Error executing transaction, executing rollback. Inner exception: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (_http_outgoing.js:473:3)
    at Object.exportToTar (/work/trilium/trilium-linux-x64-server/src/services/export/tar.js:224:9)Error
    at Object.transactional (/work/trilium/trilium-linux-x64-server/src/services/sql.js:164:19)
    at cls.init (/work/trilium/trilium-linux-x64-server/src/routes/routes.js:73:38)
    at /work/trilium/trilium-linux-x64-server/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/work/trilium/trilium-linux-x64-server/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/work/trilium/trilium-linux-x64-server/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/work/trilium/trilium-linux-x64-server/src/services/cls.js:5:28)
    at router.(anonymous function) (/work/trilium/trilium-linux-x64-server/src/routes/routes.js:68:38)
    at Layer.handle [as handle_request] (/work/trilium/trilium-linux-x64-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/work/trilium/trilium-linux-x64-server/node_modules/express/lib/router/route.js:137:13)
    at checkApiAuthOrElectron (/work/trilium/trilium-linux-x64-server/src/services/auth.js:28:9)
    at Object.error (/work/trilium/trilium-linux-x64-server/src/services/log.js:33:13)
    at Promise (/work/trilium/trilium-linux-x64-server/src/services/sql.js:182:21)
Trace: ERROR: get /api/notes/:branchId/export/:type/:format threw exception: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (_http_outgoing.js:473:3)
    at Object.exportToTar (/work/trilium/trilium-linux-x64-server/src/services/export/tar.js:224:9)
    at Object.error (/work/trilium/trilium-linux-x64-server/src/services/log.js:33:13)
    at router.(anonymous function) (/work/trilium/trilium-linux-x64-server/src/routes/routes.js:87:17)

**Comment by zadam** [comment]
Thank you for the report, this looks like a bug. It looks like note you're exporting has some special characters in its title. Could you take a look and possibly write here any special characters you are using. It might help with fixing this issue.

Thanks.
