### ISSUE TITLE
(Bug report)  Docker image from the master

### ISSUE THREAD

**Issue by iGr33k** [zadam/trilium#2855]
### Trilium Version

0.51.2

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu 21.10 (Impish)

### Description

Trilium breaks after some time working. The setup is a Docker image built from the latest master branch branch.

Here's the log:
```
vagrant@ubuntu-impish:/vagrant_data$ sudo docker run -t -i -p 127.0.0.1:12323:8080 -v ~/trilium-data:/home/node/trilium-data zadam/trilium:0.51-latest
DB size: 4 KB
DB not initialized, please visit setup page - http://[your-server-host]:8080 to see instructions on how to initialize Trilium.
App HTTP server starting up at port 8080
{
  "appVersion": "0.51.2",
  "dbVersion": 194,
  "syncVersion": 25,
  "buildDate": "2022-05-01T23:18:35+02:00",
  "buildRevision": "b3763eed610fa3f2aabbcbdbd21efca704a5dd08",
  "dataDirectory": "/home/node/trilium-data",
  "clipperProtocolVersion": "1.0",
  "utcDateTime": "2022-05-17T16:50:36.570Z"
}
CPU model: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz, logical cores: 2 freq: 2304 Mhz
Listening on port 8080

/usr/src/app/src/services/sql.js:217
        throw e;
        ^
SqliteError: no such table: options
    at Database.prepare (/usr/src/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at stmt (/usr/src/app/src/services/sql.js:78:44)
    at wrap (/usr/src/app/src/services/sql.js:206:23)
    at Object.getRow (/usr/src/app/src/services/sql.js:85:12)
    at getOptionOrNull (/usr/src/app/src/services/options.js:11:22)
    at getOption (/usr/src/app/src/services/options.js:18:17)
    at Object.getOptionInt (/usr/src/app/src/services/options.js:31:17)
    at Timeout._onTimeout (/usr/src/app/src/services/protected_session.js:67:45)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

Trilium starts, works for about 20 seconds and then throws an exception.

**Comment by zadam** [comment]
Hi, thanks for the bug report, fixed. Note that it's not a critical bug and the application should work fine.
