### ISSUE TITLE
(Bug report) Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length

### ISSUE THREAD

**Issue by bonedaddy** [zadam/trilium#2951]
### Trilium Version

v0.53.0-beta

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu 22.04

### Description

Attempting to add notes to an encrypted note section results in repeat errors of the following
```
ERROR: put /api/notes/:noteId/content threw exception: Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Decipheriv.final (node:internal/crypto/cipher:193:29)
    at decrypt (/etc/trilium/code/src/services/data_encryption.js:71:91)
    at Object.decryptString (/etc/trilium/code/src/services/data_encryption.js:98:20)
    at Object.decryptString (/etc/trilium/code/src/services/protected_session.js:55:34)
    at new NoteRevision (/etc/trilium/code/src/becca/entities/note_revision.js:52:54)
    at Note.saveNoteRevision (/etc/trilium/code/src/becca/entities/note.js:1242:30)
    at saveNoteRevisionIfNeeded (/etc/trilium/code/src/services/notes.js:522:14)
    at Object.updateNoteContent (/etc/trilium/code/src/services/notes.js:533:5)
    at updateNoteContent (/etc/trilium/code/src/routes/api/notes.js:60:24)
    at Function.cb (/etc/trilium/code/src/routes/routes.js:155:34)
JS Error: Error when calling PUT notes/iqcjQNRbWs9e/content: error - Internal Server Error
Stack: logError@http://localhost:8080/app/services/ws.js:23:20
throwError@http://localhost:8080/app/services/toast.js:87:8
reportError@http://localhost:8080/app/services/server.js:110:18
```

**Comment by zadam** [comment]
Hello, thank you for reporting this regression, fixed.
