### ISSUE TITLE
(Bug report) Jump to note dialog doesn't update

### ISSUE THREAD

**Issue by FliegendeWurst** [zadam/trilium#3066]
### Trilium Version

0.54.2

### What operating system are you using?

Other Linux

### What is your setup?

Local + server sync

### Operating System Version

Linux nixOS 5.10.135 x86_64 GNU/Linux (NixOS 22.05)

### Description

Steps to reproduce:
1. Name your root note "root"
2. Open "Jump to note"
3. Type `global x` (or `global r` or similar)
4. Observe the error popup (`Error when calling GET /api/autocomplete?query=global%20x&activeNoteId=Zo4AnktQKR6F: 500 - Cannot read properties of undefined (reading 'includes')`)
5. Observe that the search results don't update

The issue apparently occurs because the root note is selected as a candidate in this loop: https://github.com/zadam/trilium/blob/bb3734052aa2e44e4bd2cfc8fe001a58934daf0f/src/services/search/expressions/note_flat_text.js#L78
Later, we expand the search to the "parent note" of the root note:
https://github.com/zadam/trilium/blob/bb3734052aa2e44e4bd2cfc8fe001a58934daf0f/src/services/search/expressions/note_flat_text.js#L101-L116
That doesn't work because the "parent note" of the root note isn't a valid note object.

<details><summary>full log</summary>

```
XX:YY:38.886 Slow 200 GET /api/autocomplete?query=g&activeNoteId=Zo4AnktQKR6F with 70027 bytes took 48ms
XX:YY:40.897 Slow 200 GET /api/autocomplete?query=gl&activeNoteId=Zo4AnktQKR6F with 33353 bytes took 19ms
XX:YY:40.985 200 GET /api/autocomplete?query=glo&activeNoteId=Zo4AnktQKR6F with 1464 bytes took 4ms
XX:YY:41.065 200 GET /api/autocomplete?query=glob&activeNoteId=Zo4AnktQKR6F with 1464 bytes took 4ms
XX:YY:41.184 200 GET /api/autocomplete?query=globa&activeNoteId=Zo4AnktQKR6F with 1193 bytes took 3ms
XX:YY:41.280 200 GET /api/autocomplete?query=global&activeNoteId=Zo4AnktQKR6F with 1193 bytes took 3ms
XX:YY:41.360 200 GET /api/autocomplete?query=global%20&activeNoteId=Zo4AnktQKR6F with 1193 bytes took 3ms
XX:YY:41.491 ERROR: get /api/autocomplete threw exception: TypeError: Cannot read properties of undefined (reading 'includes')
    at searchDownThePath (/nix/store/bi52wl0pn4gb9vp640zswl4c9z7cc3n2-trilium-desktop-0.54.2/share/trilium/resources/app.asar/src/services/search/expressions/note_flat_text.js:41:31)
    at NoteFlatTextExp.execute (/nix/store/bi52wl0pn4gb9vp640zswl4c9z7cc3n2-trilium-desktop-0.54.2/share/trilium/resources/app.asar/src/services/search/expressions/note_flat_text.js:114:21)
    at AndExp.execute (/nix/store/bi52wl0pn4gb9vp640zswl4c9z7cc3n2-trilium-desktop-0.54.2/share/trilium/resources/app.asar/src/services/search/expressions/and.js:26:42)
    at findResultsWithExpression (/nix/store/bi52wl0pn4gb9vp640zswl4c9z7cc3n2-trilium-desktop-0.54.2/share/trilium/resources/app.asar/src/services/search/services/search.js:77:32)
    at findResultsWithQuery (/nix/store/bi52wl0pn4gb9vp640zswl4c9z7cc3n2-trilium-desktop-0.54.2/share/trilium/resources/app.asar/src/services/search/services/search.js:173:12)
    at Object.searchNotesForAutocomplete (/nix/store/bi52wl0pn4gb9vp640zswl4c9z7cc3n2-trilium-desktop-0.54.2/share/trilium/resources/app.asar/src/services/search/services/search.js:194:30)
    at getAutocomplete (/nix/store/bi52wl0pn4gb9vp640zswl4c9z7cc3n2-trilium-desktop-0.54.2/share/trilium/resources/app.asar/src/routes/api/autocomplete.js:22:33)
    at Function.cb (/nix/store/bi52wl0pn4gb9vp640zswl4c9z7cc3n2-trilium-desktop-0.54.2/share/trilium/resources/app.asar/src/routes/routes.js:159:34)
    at Function.sqliteTransaction (/nix/store/bi52wl0pn4gb9vp640zswl4c9z7cc3n2-trilium-desktop-0.54.2/share/trilium/resources/app.asar/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (/nix/store/bi52wl0pn4gb9vp640zswl4c9z7cc3n2-trilium-desktop-0.54.2/share/trilium/resources/app.asar/src/services/sql.js:236:52)
XX:YY:41.495 JS Error: Error when calling GET /api/autocomplete?query=global%20x&activeNoteId=Zo4AnktQKR6F: 500 - Cannot read properties of undefined (reading 'includes')
Stack: Error
    at Object.N [as logError] (http://127.0.0.1:37840/app-dist/desktop.js:2:101340)
    at Object.throwError (http://127.0.0.1:37840/app-dist/desktop.js:2:86449)
    at c (http://127.0.0.1:37840/app-dist/desktop.js:2:83104)
    at async EventEmitter.<anonymous> (http://127.0.0.1:37840/app-dist/desktop.js:2:83956)
```

</details>

**Comment by zadam** [comment]
Hi, also discussed in https://github.com/zadam/trilium/pull/3063

I will take a look at this.

**Comment by zadam** [comment]
Hi, I believe I fixed that. Root note has a parent "none" which doesn't exist, but was mistakenly created as an entity in the memory data model.
