### ISSUE TITLE
(Bug report) Parsing error in search string

### ISSUE THREAD

**Issue by agentydragon** [zadam/trilium#3096]
### Trilium Version

0.54.3

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

macOS 12.5.1

### Description

I'm writing a script and I found out that searching for this string gives me an error from the backend:

```
#issue (~state.noteId=SittoKTBsvYX OR ~state.noteId=2CpyDq8DmG3E) ~hotlist.noteId=jVjWdmU5r1WP
```

I believe this is a perfectly cromulent search string - find all notes with the label `issue`, whose `hotlist` relation points at `jVjWdmU5r1WP` and whose `state` relation points at either `SittoKTBsvYX` or `2CpyDq8DmG3E`.

The error:

```
ws.js:17 23:14:14 Error when calling GET /api/search-note/x4ZvuyjNUP9U: 500 - Cannot read properties of undefined (reading 'match')
toast.js:90 Uncaught (in promise) Error: Error when calling GET /api/search-note/x4ZvuyjNUP9U: 500 - Cannot read properties of undefined (reading 'match')
    at Object.throwError (toast.js:90)
    at c (server.js:110)
    at async EventEmitter.<anonymous> (server.js:174)
```

backend log:

```
23:14:14.459 200 PUT /api/notes/x4ZvuyjNUP9U/title with 335 bytes took 2ms
23:14:14.870 ERROR: get /api/search-note/:noteId threw exception: TypeError: Cannot read properties of undefined (reading 'match')
    at isOperator (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/search/services/parse.js:43:16)
    at parseLabel (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/search/services/parse.js:231:38)
    at parseAttribute (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/search/services/parse.js:223:34)
    at getExpression (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/search/services/parse.js:345:30)
    at parse (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/search/services/parse.js:407:9)
    at parseQueryToExpression (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/search/services/search.js:128:24)
    at Object.findResultsWithQuery (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/search/services/search.js:167:24)
    at searchFromNoteInt (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/api/search.js:33:45)
    at searchFromNote (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/api/search.js:63:12)
    at Function.cb (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/routes.js:159:34)
23:14:14.885 JS Error: Error when calling GET /api/search-note/x4ZvuyjNUP9U: 500 - Cannot read properties of undefined (reading 'match')
Stack: Error
    at Object.N [as logError] (http://127.0.0.1:37840/app-dist/desktop.js:2:101340)
    at Object.throwError (http://127.0.0.1:37840/app-dist/desktop.js:2:86449)
    at c (http://127.0.0.1:37840/app-dist/desktop.js:2:83104)
    at async EventEmitter.<anonymous> (http://127.0.0.1:37840/app-dist/desktop.js:2:83956)
23:14:21.585 Sending message to all clients: {"type":"sync-push-in-progress","lastSyncedPush":64976}
23:14:21.587 Sync laMCadQ8eR: Pushing 2 sync changes in 308ms
```

**Comment by agentydragon** [comment]
as a workaround, `#issue AND (~state.noteId=SittoKTBsvYX OR ~state.noteId=2CpyDq8DmG3E) AND ~hotlist.noteId=jVjWdmU5r1WP` works. but still, the error could be improved.

**Comment by zadam** [comment]
Hi, thanks for the bug report, fixed. As a workaround, use explicit `AND` before parenthesis.
