### ISSUE TITLE
Error out in setup

### ISSUE THREAD

**Issue by groundswel** [zadam/trilium#324]
After cloning the github repo I do a npm install followed by npm start. Then when I go to the website at localhost:8080 and fill up username and password for new Note in the setup page I get the following internal server error

npm start

> trilium@0.27.4 start /Users/davidwoof/bal/pers/tril/trilium
> node ./src/www

Generated sourceId=5kp6aWkAtRu1
App HTTP server starting up at port 8080
{
  "appVersion": "0.27.4",
  "dbVersion": 121,
  "syncVersion": 3,
  "buildDate": "2019-01-10T21:31:30+01:00",
  "buildRevision": "0b251530fa0ee61edc8dcc9235033abb73afc614",
  "dataDirectory": "/Users/davidwoof/Library/Application Support/trilium-data"
}
DB not initialized, please visit setup page to see instructions on how to initialize Trilium.
Creating initial database ...
Trace: ERROR: Execution of script "attribute changed" (wjjoLouoPXti) failed with error: Load of script note "attribute changed" (wjjoLouoPXti) failed with: Cannot read property 'noteId' of null
    at Object.error (/Users/davidwoof/bal/pers/tril/trilium/src/services/log.js:33:13)
    at executeBundle (/Users/davidwoof/bal/pers/tril/trilium/src/services/script.js:38:13)
    at <anonymous>
Trace: ERROR: Execution of script "attribute changed" (wjjoLouoPXti) failed with error: Load of script note "attribute changed" (wjjoLouoPXti) failed with: Cannot read property 'noteId' of null
    at Object.error (/Users/davidwoof/bal/pers/tril/trilium/src/services/log.js:33:13)
    at executeBundle (/Users/davidwoof/bal/pers/tril/trilium/src/services/script.js:38:13)
    at <anonymous>
Trace: ERROR: Execution of script "attribute changed" (wjjoLouoPXti) failed with error: Load of script note "attribute changed" (wjjoLouoPXti) failed with: Cannot read property 'noteId' of null
    at Object.error (/Users/davidwoof/bal/pers/tril/trilium/src/services/log.js:33:13)
    at executeBundle (/Users/davidwoof/bal/pers/tril/trilium/src/services/script.js:38:13)
    at <anonymous>
Trace: ERROR: Execution of script "attribute changed" (wjjoLouoPXti) failed with error: Load of script note "attribute changed" (wjjoLouoPXti) failed with: Cannot read property 'noteId' of null
    at Object.error (/Users/davidwoof/bal/pers/tril/trilium/src/services/log.js:33:13)
    at executeBundle (/Users/davidwoof/bal/pers/tril/trilium/src/services/script.js:38:13)
    at <anonymous>
Trace: ERROR: Error executing transaction, executing rollback. Inner exception: TypeError: crypto.scryptSync is not a function
    at getScryptHash (/Users/davidwoof/bal/pers/tril/trilium/src/services/my_scrypt.js:19:27)
    at Object.getVerificationHash (/Users/davidwoof/bal/pers/tril/trilium/src/services/my_scrypt.js:9:12)
    at <anonymous>Error
    at Object.transactional (/Users/davidwoof/bal/pers/tril/trilium/src/services/sql.js:164:19)
    at cls.init (/Users/davidwoof/bal/pers/tril/trilium/src/routes/routes.js:73:38)
    at /Users/davidwoof/bal/pers/tril/trilium/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/Users/davidwoof/bal/pers/tril/trilium/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/Users/davidwoof/bal/pers/tril/trilium/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/Users/davidwoof/bal/pers/tril/trilium/src/services/cls.js:5:28)
    at router.(anonymous function) (/Users/davidwoof/bal/pers/tril/trilium/src/routes/routes.js:68:38)
    at Layer.handle [as handle_request] (/Users/davidwoof/bal/pers/tril/trilium/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/davidwoof/bal/pers/tril/trilium/node_modules/express/lib/router/route.js:137:13)
    at checkAppNotInitialized (/Users/davidwoof/bal/pers/tril/trilium/src/services/auth.js:55:9)
    at Object.error (/Users/davidwoof/bal/pers/tril/trilium/src/services/log.js:33:13)
    at Promise (/Users/davidwoof/bal/pers/tril/trilium/src/services/sql.js:182:21)
    at <anonymous>
Trace: ERROR: post /api/setup/new-document threw exception: TypeError: crypto.scryptSync is not a function
    at getScryptHash (/Users/davidwoof/bal/pers/tril/trilium/src/services/my_scrypt.js:19:27)
    at Object.getVerificationHash (/Users/davidwoof/bal/pers/tril/trilium/src/services/my_scrypt.js:9:12)
    at <anonymous>
    at Object.error (/Users/davidwoof/bal/pers/tril/trilium/src/services/log.js:33:13)
    at router.(anonymous function) (/Users/davidwoof/bal/pers/tril/trilium/src/routes/routes.js:87:17)
    at <anonymous

**Comment by zadam** [comment]
>  TypeError: crypto.scryptSync is not a function

This looks like you're using old node version. Only node 10 and later is supported.

**Comment by jkurei** [comment]
I hit this problem too and took me a while to figure out. May be on trying to boot the server it could detect the Node version and tell you about this? I'm willing to write this change and throw you a PR if you think it's a good idea.

**Comment by jkurei** [comment]
I'd do something like this:

```js
const majorVersion = parseInt(process.version.slice(1).split(".")[0]);
if (majorVersion < 10) {
    console.error("Trilium only supports node 10 and later");
    process.exit(1);
}
else {
    startTrilium();
}
```

But I wonder if you'd rather not exit and just warn the user. Also, trilium already depends on [semver](https://github.com/npm/node-semver) indirectly; I wouldn't add further dependency myself, but it's a really dependable package.

```
npm ls semver
trilium@0.27.4 /mnt/c/Users/j/Desktop/trilium
├─┬ cls-hooked@4.2.2
│ └── semver@5.6.0
├─┬ electron-rebuild@1.8.2
│ └─┬ node-gyp@3.8.0
│   └── semver@5.3.0
└─┬ imagemin-giflossy@5.1.10
  └─┬ giflossy@3.0.41
    └─┬ bin-wrapper@3.0.2
      └─┬ bin-version-check@2.1.0
        └── semver@4.3.6
```

**Comment by zadam** [comment]
@jkurei that's a good idea - I wanted to do it after receiving this issue, but then forgot it. I used your code with semver almost verbatim, so thanks for that!

I am actually exiting after the detection because older node is not just supported, it's actually known to not run correctly with Trilium.
