### ISSUE TITLE
When starting from VSCode libraries for CodeMirror aren't found (Bug report) 

### ISSUE THREAD

**Issue by Banbury** [zadam/trilium#3282]
### Trilium Version

master commit 0a02e5b

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 7 Version 6.1 (Build 7601: Service Pack 1)

### Description

When launching from VSCode or with `npm run start-server` the frontend can't load the language mode files for CodeMirror. The server throws the following error, when selecting a code note for JavaScript. For CSS notes it is `css.js`, that can't be loaded.

```
Error: Router not found for request /libraries/codemirror/mode/javascript/javascript.js
    at d:\projects\node\trilium\src\app.js:92:17
    at Layer.handle [as handle_request] (d:\projects\node\trilium\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (d:\projects\node\trilium\node_modules\express\lib\router\index.js:328:13)
    at d:\projects\node\trilium\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (d:\projects\node\trilium\node_modules\express\lib\router\index.js:346:12)
    at next (d:\projects\node\trilium\node_modules\express\lib\router\index.js:280:10)
    at Layer.handle [as handle_request] (d:\projects\node\trilium\node_modules\express\lib\router\layer.js:91:12)
    at trim_prefix (d:\projects\node\trilium\node_modules\express\lib\router\index.js:328:13)
    at d:\projects\node\trilium\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (d:\projects\node\trilium\node_modules\express\lib\router\index.js:346:12) {
  status: 404
}
```

My guess is, that it has something to do with the static route for the libraries path.
```
app.use(`/${assetPath}/libraries`, express.static(path.join(__dirname, '..', 'libraries')));
```
It expects some `assetPath` at the beginning of the request, but this is missing in the frontend request.

**Comment by zadam** [comment]
Hi, thanks for the heads up, I fixed the issue. To avoid such problems I recommend using "stable" branch, master is used for development and can have bugs such as this one.
