### ISSUE TITLE
Wight Tracker demo is broken

### ISSUE THREAD

**Issue by MAX10541** [zadam/trilium#329]
"Weight Tracker" button in the demo doesn't work. An error is printed in the terminal:

<pre>Trace: ERROR: JS Error: Can't find note "8LOr7xUMuWD4"
    at Object.error (/home/max/bin/trilium-linux-x64/resources/app/src/services/log.js:33:13)
    at WebSocket.ws.on.messageJson (/home/max/bin/trilium-linux-x64/resources/app/src/services/messaging.js:31:21)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage (/home/max/bin/trilium-linux-x64/resources/app/node_modules/ws/lib/websocket.js:741:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (/home/max/bin/trilium-linux-x64/resources/app/node_modules/ws/lib/receiver.js:417:14)
    at Receiver.getData (/home/max/bin/trilium-linux-x64/resources/app/node_modules/ws/lib/receiver.js:347:17)
    at Receiver.startLoop (/home/max/bin/trilium-linux-x64/resources/app/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/home/max/bin/trilium-linux-x64/resources/app/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:410:12)
</pre>
Trilium version:
Both v0.27.4 and v0.27.3

OS:
Ubuntu 18.04

**Comment by zadam** [comment]
This is actually just a button and you can navigate to the Weight Tracker manually - it's a child of "Trilium Demo" note. But of course this is a bug nevertheless so thanks for the report!
