### ISSUE TITLE
export not saving anything

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#331]
on latest, I select a note and say "export".  using wither note and children or single note, in either html or markdown - i get a dislog box to save, hit OK and nothing is created.

PS:  When saving a tree, it would be great to have it saved as a directory instead of a tra file.  Makes the content immediately available without having to extract.

**Comment by zadam** [comment]
Can you take a look into the logs (location depends on the platform - see https://github.com/zadam/trilium/wiki/Document ) if there's any error?

I use .tar because on the web version it's not possible to create directories so there would be feature disparity ...

**Comment by pcause** [comment]
OK, think I have more information and it is happening on a specific imported note, but not all.  .  On a very simple note I created by hand the export worked.  On a note that was imported as markdown I can also save.  On the note I originally had the issue with, the name in the OS save dialog box is just "markdown" or "html" and not the note title as with the other 2.   In the log I see errors. 

18:58:02.150 INFO  GET /api/notes/qz8c5rVX2WTi/export/single/markdown?protectedS

I also saw a previous error where there was a reference to an image that was imported in a different parent and seemed to have a link, but showed in the page as sort of empty.  Maybe the image didn't import correctly in the note.
essionId=null 
18:58:02.337 INFO  ERROR: Error executing transaction, executing rollback. Inner
 exception: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["
Content-Disposition"]
    at ServerResponse.setHeader (_http_outgoing.js:473:3)
    at Object.exportSingleNote (/home/XXX/apps/trilium-linux-x64/resources/app/s
rc/services/export/single.js:49:9)Error
    at Object.transactional (/home/XXX/apps/trilium-linux-x64/resources/app/src/
services/sql.js:164:19)
    at cls.init (/home/XXX/apps/trilium-linux-x64/resources/app/src/routes/route
s.js:73:38)
    at /home/XXX/apps/trilium-linux-x64/resources/app/node_modules/cls-hooked/co
ntext.js:118:13
    at Namespace.run (/home/XXX/apps/trilium-linux-x64/resources/app/node_module
s/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/home/XXX/apps/trilium-linux-x64/resources/app/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/home/XXX/apps/trilium-linux-x64/resources/app/src/services/cls.js:5:28)
    at router.(anonymous function) (/home/XXX/apps/trilium-linux-x64/resources/app/src/routes/routes.js:68:38)
at Layer.handle [as handle_request] (/home/XXX/apps/trilium-linux-x64/resources/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/XXX/apps/trilium-linux-x64/resources/app/node_modules/express/lib/router/route.js:137:13)
    at checkApiAuthOrElectron (/home/XXX/apps/trilium-linux-x64/resources/app/src/services/auth.js:28:9) 
18:58:02.340 INFO  ERROR: get /api/notes/:branchId/export/:type/:format threw exception: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (_http_outgoing.js:473:3)
    at Object.exportSingleNote (/home/XXX/apps/trilium-linux-x64/resources/app/src/services/export/single.js:49:9)

**Comment by zadam** [comment]
I see, that actually helps quite a bit, thank you for the followup! The problem is probably in the note title being exported - it seems to contain some special characters. I use a library which should sanitize the filename, but it looks like it doesn't work properly.
