### ISSUE TITLE
(Bug report) Cannot create a new Script Launcher

### ISSUE THREAD

**Issue by nemec** [zadam/trilium#3425]
### Trilium Version

master branch

### What operating system are you using?

macOS

### What is your setup?

Local (no sync)

### Operating System Version

12.6.1

### Description

When I go to "Configure launchbar" -> "Available Launchers" -> "Add a script launcher" I get the following error:

    Error when calling POST /api/special-notes/launchers/lbAvailableLaunchers/script: 500 - Cannot save relation 'template' since it target not existing note 'lbTplScriptLauncher'.

I just upgraded to the latest master commit today (`b202b43bf565`) so maybe I'm jumping the gun a bit on feature support lol. But it does seem to be the replacement for `addButtonToToolbar`, which no longer works.

### Error logs

17:16:39.501 Created new note 'lDu0S6Dbb3Hq', branch 'XADAKSrxZw49' of type 'launcher', mime 'application/octet-stream'
17:16:39.502 Transaction rollback dirtied the becca, forcing reload.
17:16:39.513 Becca (note cache) load took 11ms
17:16:39.515 ERROR: post /api/special-notes/launchers/:parentNoteId/:launcherType threw exception: Error: Cannot save relation 'template' since it target not existing note 'lbTplScriptLauncher'.
    at Attribute.beforeSaving (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/becca/entities/attribute.js:181:23)
    at Attribute.save (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/becca/entities/abstract_entity.js:87:18)
    at Note.addAttribute (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/becca/entities/note.js:1172:12)
    at Note.addRelation (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/becca/entities/note.js:1197:21)
    at Object.createLauncher (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/special_notes.js:166:14)
    at createLauncher (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/api/special_notes.js:70:32)
    at Function.cb (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/routes.js:161:34)
    at Function.sqliteTransaction (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:236:52)
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/routes.js:163:44
17:16:39.525 JS Error: Error when calling POST /api/special-notes/launchers/lbAvailableLaunchers/script: 500 - Cannot save relation 'template' since it target not existing note 'lbTplScriptLauncher'.
Stack: Error
    at Object.C [as logError] (http://127.0.0.1:37840/assets/v0.57.5/app-dist/desktop.js:2:101727)
    at Object.throwError (http://127.0.0.1:37840/assets/v0.57.5/app-dist/desktop.js:2:86876)
    at h (http://127.0.0.1:37840/assets/v0.57.5/app-dist/desktop.js:2:83010)
    at async EventEmitter.<anonymous> (http://127.0.0.1:37840/assets/v0.57.5/app-dist/desktop.js:2:83862)

**Comment by zadam** [comment]
Hi, thanks for the report - the bug is now fixed. However, master is a development, unreleased version. It would be much safer to switch to stable branch.
