### ISSUE TITLE
(Bug report)  Search with option "order by content size" cause error

### ISSUE THREAD

**Issue by zhaohui0923** [zadam/trilium#3488]
### Trilium Version

0.57.5

### What operating system are you using?

Other (specify below)

### What is your setup?

Server access only

### Operating System Version

docker

### Description

![屏幕截图 2023-01-04 172546](https://user-images.githubusercontent.com/39145884/210673245-aa2c4a5e-728f-40e8-a781-cde95962247f.png)
When search by tag with option "order by contentsize" will cause error

### Error logs

00:11:23.710 ERROR: get /api/search-note/:noteId threw exception: TypeError: valA.trim is not a function
    at /usr/src/app/src/services/search/expressions/order_by_and_limit.js:52:26
    at Array.sort (<anonymous>)
    at OrderByAndLimitExp.execute (/usr/src/app/src/services/search/expressions/order_by_and_limit.js:26:15)
    at findResultsWithExpression (/usr/src/app/src/services/search/services/search.js:151:32)
    at findResultsWithQuery (/usr/src/app/src/services/search/services/search.js:247:12)
    at Object.searchFromNote (/usr/src/app/src/services/search/services/search.js:37:31)
    at searchFromNote (/usr/src/app/src/routes/api/search.js:26:26)
    at Function.cb (/usr/src/app/src/routes/routes.js:159:34)
    at Function.sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (/usr/src/app/src/services/sql.js:236:52)
00:11:23.944 JS Error: Error when calling GET search-note/fSKNHQByBCTm: error - valA.trim is not a function
Stack: Error
    at Object.C [as logError] (https://xxxx:xxxx/assets/v0.57.5/app-dist/desktop.js:2:96330)
    at Object.throwError (https://xxxx:xxxx/assets/v0.57.5/app-dist/desktop.js:2:81380)
    at c (https://xxxx:xxxx/assets/v0.57.5/app-dist/desktop.js:2:78040)
    at async Object.error (xxxx:xxxx/assets/v0.57.5/app-dist/desktop.js:2:78346)
00:11:25.170 200 GET /api/health-check with 15 bytes took 2ms
00:11:29.880 304 GET /api/clipper/handshake with 45 bytes took 3ms

**Comment by zadam** [comment]
Thanks, fixed, will be released in 0.58.4
