### ISSUE TITLE
(Bug report) Container stops after several days 

### ISSUE THREAD

**Issue by chaseadam** [zadam/trilium#3495]
### Trilium Version

0.57

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

podman on Manjaro and Fedora

### Description

I am using the upstream docker container published on docker.io on aarch64 single board computers. Both have limited CPU, but one has 1GB and other has 8GB RAM and I appear to keep running into crashes. I believe this is due to OOM errors.

I believe there is a memory leak somewhere. Still confirming the issue, but wanted to start documenting it.

Could be related to #3240 or #2350

### Error logs

Error on 8GB
```
200 GET /api/health-check with 15 bytes took 4ms
200 GET /api/health-check with 15 bytes took 3ms
sync failed: Process exceeded time limit 120000
stack: Error: Process exceeded time limit 120000
    at Object.timeLimit (/usr/src/app/src/services/utils.js:257:19)
    at requestToSyncServer (/usr/src/app/src/services/setup.js:49:24)
    at Object.hasSyncServerSchemaAndSeed (/usr/src/app/src/services/setup.js:12:28)
    at login (/usr/src/app/src/services/sync.js:90:29)
    at /usr/src/app/src/services/sync.js:35:43
    at Object.doExclusively (/usr/src/app/src/services/sync_mutex.js:13:22)
    at async sync (/usr/src/app/src/services/sync.js:27:16)

<--- Last few GCs --->

[1:0xffff853e73c0] 1329011938 ms: Mark-sweep 2046.5 (2083.6) -> 2045.8 (2084.1) MB, 6366.5 / 92.1 ms  (average mu = 0.965, current mu = 0.912) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

separate error on 1GB RAM which happened shortly after start (while syncing?):

```
Jan 06 16:46:03 pine.827.chasen.name podman[1881]: 2023-01-06 16:46:03.472045395 -0500 EST m=+3192661.327390827 container kill 73dee8c75f754>
Jan 06 16:43:50 pine.827.chasen.name systemd[1646]: podman-884083.scope: Consumed 8.821s CPU time.
Jan 06 16:43:50 pine.827.chasen.name podman[884368]: 2023-01-06 16:43:50.687200937 -0500 EST m=+0.990117351 container remove 08361e2ecc143f6>
Jan 06 16:43:50 pine.827.chasen.name systemd[1646]: Stopped 08361e2ecc143f69208168edf009025b75dc9d44d53a3d6c8e608bf7ca892a5a.timer - /usr/bi>
Jan 06 16:43:49 pine.827.chasen.name systemd[1646]: 08361e2ecc143f69208168edf009025b75dc9d44d53a3d6c8e608bf7ca892a5a.service: Failed with re>
Jan 06 16:43:49 pine.827.chasen.name systemd[1646]: 08361e2ecc143f69208168edf009025b75dc9d44d53a3d6c8e608bf7ca892a5a.service: Main process e>
Jan 06 16:43:49 pine.827.chasen.name podman[884359]: Error: container 08361e2ecc143f69208168edf009025b75dc9d44d53a3d6c8e608bf7ca892a5a is no>
Jan 06 16:43:49 pine.827.chasen.name podman[884083]: 2023-01-06 16:43:49.682434059 -0500 EST m=+425.606837604 container died 08361e2ecc143f6>
Jan 06 16:43:49 pine.827.chasen.name systemd[1646]: libpod-08361e2ecc143f69208168edf009025b75dc9d44d53a3d6c8e608bf7ca892a5a.scope: Consumed >
Jan 06 16:43:41 pine.827.chasen.name systemd-oomd[577]: Killed /user.slice/user-1000.slice/user@1000.service/user.slice/libpod-08361e2ecc143>
Jan 06 16:43:40 pine.827.chasen.name systemd[1646]: Started 08361e2ecc143f69208168edf009025b75dc9d44d53a3d6c8e608bf7ca892a5a.service - /usr/>
Jan 06 16:43:09 pine.827.chasen.name podman[884339]: 2023-01-06 16:43:09.985963236 -0500 EST m=+35.362753830 container exec_died 08361e2ecc1>
Jan 06 16:43:09 pine.827.chasen.name trilium[884118]: 200 GET /api/health-check with 15 bytes took 7ms
Jan 06 16:43:09 pine.827.chasen.name podman[884339]: 2023-01-06 16:43:09.845581671 -0500 EST m=+35.222372057 container health_status 08361e2>
Jan 06 16:42:33 pine.827.chasen.name systemd[1646]: Started 08361e2ecc143f69208168edf009025b75dc9d44d53a3d6c8e608bf7ca892a5a.service - /usr/>
Jan 06 16:42:07 pine.827.chasen.name trilium[884118]: Erased attributes: ["UjzGgMkpIBk5"]
Jan 06 16:42:07 pine.827.chasen.name trilium[884118]: Erased branches: ["O8Z5Z3RvkHhB","ubIpTKsfi3uh","DJP8EchO8ZfZ","7swu38iRyx5f","wn4mqRP>
Jan 06 16:42:07 pine.827.chasen.name trilium[884118]: Erased notes: ["SznyAoawlyB2","BSPFKKYi6Yv3","dBBq99xiCXNO","90Qz0yuEDI8U","UjIoScNEqF>
Jan 06 16:42:07 pine.827.chasen.name trilium[884118]: Removing note revisions: ["I1q9E3wlTPNm"]
Jan 06 16:42:07 pine.827.chasen.name trilium[884118]: Erased attributes: ["CP7lcodP7iny","6vg8NYmkCstc","EAQAoJVnrXYk","bAfQTummtCeF","Q7WEe>
Jan 06 16:42:07 pine.827.chasen.name trilium[884118]: Erased branches: ["0apRBP6oN2XN","Qr0bWA5RbTXQ","40vxY2lxVUz2","ZAk4ejAuEFtK","fZkinnq>
Jan 06 16:42:02 pine.827.chasen.name podman[884319]: 2023-01-06 16:42:02.971654444 -0500 EST m=+0.427276751 container exec_died 08361e2ecc14>
Jan 06 16:42:02 pine.827.chasen.name trilium[884118]: 200 GET /api/health-check with 15 bytes took 6ms
Jan 06 16:42:02 pine.827.chasen.name podman[884319]: 2023-01-06 16:42:02.923671212 -0500 EST m=+0.379288686 container health_status 08361e2e>
Jan 06 16:42:02 pine.827.chasen.name systemd[1646]: Started 08361e2ecc143f69208168edf009025b75dc9d44d53a3d6c8e608bf7ca892a5a.service - /usr/>
Jan 06 16:41:32 pine.827.chasen.name podman[884299]: 2023-01-06 16:41:32.017551437 -0500 EST m=+0.463377970 container exec_died 08361e2ecc14>
Jan 06 16:41:31 pine.827.chasen.name trilium[884118]: 200 GET /api/health-check with 15 bytes took 5ms
Jan 06 16:41:31 pine.827.chasen.name podman[884299]: 2023-01-06 16:41:31.927342265 -0500 EST m=+0.373167424 container health_status 08361e2e>
Jan 06 16:41:31 pine.827.chasen.name systemd[1646]: Started 08361e2ecc143f69208168edf009025b75dc9d44d53a3d6c8e608bf7ca892a5a.service - /usr/>
Jan 06 16:41:08 pine.827.chasen.name trilium[884118]: Sending message to all clients: {"type":"sync-finished","lastSyncedPush":17148}
Jan 06 16:41:08 pine.827.chasen.name trilium[884118]: Content hash checks PASSED
Jan 06 16:41:08 pine.827.chasen.name trilium[884118]: Content hash computation took 120ms
Jan 06 16:41:08 pine.827.chasen.name trilium[884118]: Slow query took 71ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSy>
Jan 06 16:41:08 pine.827.chasen.name trilium[884118]: Nothing to push
Jan 06 16:41:08 pine.827.chasen.name trilium[884118]: Finished pull
Jan 06 16:41:07 pine.827.chasen.name trilium[884118]: Nothing to push
Jan 06 16:41:00 pine.827.chasen.name podman[884280]: 2023-01-06 16:41:00.482219583 -0500 EST m=+3.940340426 container exec_died 08361e2ecc14>
Jan 06 16:41:00 pine.827.chasen.name trilium[884118]: 200 GET /api/health-check with 15 bytes took 6ms
Jan 06 16:41:00 pine.827.chasen.name podman[884280]: 2023-01-06 16:41:00.397075345 -0500 EST m=+3.855194187 container health_status 08361e2e>
Jan 06 16:40:56 pine.827.chasen.name systemd[1646]: Started 08361e2ecc143f69208168edf009025b75dc9d44d53a3d6c8e608bf7ca892a5a.service - /usr/>
Jan 06 16:40:25 pine.827.chasen.name podman[884256]: 2023-01-06 16:40:25.681934299 -0500 EST m=+6.118337096 container exec_died 08361e2ecc14>
Jan 06 16:40:25 pine.827.chasen.name trilium[884118]: 200 GET /api/health-check with 15 bytes took 5ms
Jan 06 16:40:25 pine.827.chasen.name podman[884256]: 2023-01-06 16:40:25.640163417 -0500 EST m=+6.076566338 container health_status 08361e2e>
Jan 06 16:40:25 pine.827.chasen.name audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg=>
Jan 06 16:40:25 pine.827.chasen.name audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg>
Jan 06 16:40:25 pine.827.chasen.name systemd[1]: Finished sysstat-collect.service - system activity accounting tool.
Jan 06 16:40:25 pine.827.chasen.name systemd[1]: sysstat-collect.service: Deactivated successfully.
Jan 06 16:40:19 pine.827.chasen.name systemd[1]: Starting sysstat-collect.service - system activity accounting tool...
Jan 06 16:40:19 pine.827.chasen.name systemd[1646]: Started 08361e2ecc143f69208168edf009025b75dc9d44d53a3d6c8e608bf7ca892a5a.service - /usr/>
Jan 06 16:40:08 pine.827.chasen.name trilium[884118]: Sending message to all clients: {"type":"sync-finished","lastSyncedPush":17148}
Jan 06 16:40:08 pine.827.chasen.name trilium[884118]: Content hash checks PASSED
Jan 06 16:40:08 pine.827.chasen.name trilium[884118]: Content hash computation took 170ms
Jan 06 16:40:08 pine.827.chasen.name trilium[884118]: Slow query took 84ms: SELECT entityName, entityId, hash FROM entity_changes WHERE isSy>
Jan 06 16:40:08 pine.827.chasen.name trilium[884118]: Nothing to push
Jan 06 16:40:08 pine.827.chasen.name trilium[884118]: Finished pull
Jan 06 16:40:07 pine.827.chasen.name trilium[884118]: Nothing to push
```

**Comment by zadam** [comment]
Hi, thanks for the report, I have some questions:

* does it happen repeatedly? How long after the startup?
* does it happen after some usage pattern? You delete a subtree, create a note etc. Or you start it up, leave it alone and it just crashes after some time?
* do you use it on the server or is it used purely as a sync server?

**Comment by chaseadam** [comment]
What is the expected memory footprint?

It happens after it has been running for a while.

Here is an example on my 1GB machine Fedora machine (with systemd-oomd) from yesterday's crash:

`journalctl --since "5 days ago" -b0 --user -t trilium`

```
Jan 16 15:39:14 pine.827.chasen.name trilium[1116385]: No USER_UID specified, leaving 1000
Jan 16 15:39:14 pine.827.chasen.name trilium[1116385]: No USER_GID specified, leaving 1000
Jan 16 15:39:26 pine.827.chasen.name trilium[1116385]: DB size: 244916 KB
Jan 16 15:39:40 pine.827.chasen.name trilium[1116385]: Trusted reverse proxy: false
Jan 16 15:39:40 pine.827.chasen.name trilium[1116385]: App HTTP server starting up at port 8080
Jan 16 15:39:40 pine.827.chasen.name trilium[1116385]: {
Jan 16 15:39:40 pine.827.chasen.name trilium[1116385]:   "appVersion": "0.57.5",
Jan 16 15:39:40 pine.827.chasen.name trilium[1116385]:   "dbVersion": 197,
Jan 16 15:39:40 pine.827.chasen.name trilium[1116385]:   "syncVersion": 26,
Jan 16 15:39:40 pine.827.chasen.name trilium[1116385]:   "buildDate": "2022-12-13T23:08:52+01:00",
Jan 16 15:39:40 pine.827.chasen.name trilium[1116385]:   "buildRevision": "921f75beba6ac71d767f6b723692c73c1cd5f70e",
Jan 16 15:39:40 pine.827.chasen.name trilium[1116385]:   "dataDirectory": "/home/node/trilium-data",
Jan 16 15:39:40 pine.827.chasen.name trilium[1116385]:   "clipperProtocolVersion": "1.0",
Jan 16 15:39:40 pine.827.chasen.name trilium[1116385]:   "utcDateTime": "2023-01-16T20:39:26.817Z"
Jan 16 15:39:40 pine.827.chasen.name trilium[1116385]: }
Jan 16 15:39:40 pine.827.chasen.name trilium[1116385]: CPU model: Cortex-A53, logical cores: 4 freq: 1152 Mhz
...
Jan 18 22:17:38 pine.827.chasen.name trilium[1180461]: Sending message to all clients: {"type":"sync-finished","lastSyncedPush":176>
Jan 18 22:17:48 pine.827.chasen.name trilium[1180461]: 200 GET /api/health-check with 15 bytes took 4ms
Jan 18 22:18:19 pine.827.chasen.name trilium[1180461]: [session-file-store] Deleting expired sessions
Jan 18 22:18:20 pine.827.chasen.name trilium[1180461]: 200 GET /api/health-check with 15 bytes took 4ms
lines 9569-9603/9603 (END)
```

`journalctl --since "1 days ago" -b0 -t podman`

```
Jan 18 22:17:48 pine.827.chasen.name podman[1198444]: 2023-01-18 22:17:48.896314137 -0500 EST m=+0.366582615 container health_status 78ba0146d5531f7f00d1515ce4367ec293f9081d176860b88bd2cf0d79bfad0c (image=docker.io/zadam/trilium:0.57-latest, name=trilium, health_status=healthy)
Jan 18 22:17:48 pine.827.chasen.name podman[1198444]: 2023-01-18 22:17:48.979947795 -0500 EST m=+0.450217398 container exec_died 78ba0146d5531f7f00d1515ce4367ec293f9081d176860b88bd2cf0d79bfad0c (image=docker.io/zadam/trilium:0.57-latest, name=trilium)
Jan 18 22:18:19 pine.827.chasen.name podman[1198464]: 2023-01-18 22:18:19.970303511 -0500 EST m=+0.416003341 container health_status 78ba0146d5531f7f00d1515ce4367ec293f9081d176860b88bd2cf0d79bfad0c (image=docker.io/zadam/trilium:0.57-latest, name=trilium, health_status=healthy)
Jan 18 22:18:20 pine.827.chasen.name podman[1198464]: 2023-01-18 22:18:20.042085829 -0500 EST m=+0.487786784 container exec_died 78ba0146d5531f7f00d1515ce4367ec293f9081d176860b88bd2cf0d79bfad0c (image=docker.io/zadam/trilium:0.57-latest, name=trilium)
Jan 18 22:19:50 pine.827.chasen.name podman[1198486]: 2023-01-18 22:19:50.182698725 -0500 EST m=+48.234129938 container died 78ba0146d5531f7f00d1515ce4367ec293f9081d176860b88bd2cf0d79bfad0c (image=docker.io/zadam/trilium:0.57-latest, name=trilium)
Jan 18 22:19:56 pine.827.chasen.name podman[1198486]: Error: healthcheck command exceeded timeout of 30s
Jan 18 22:20:02 pine.827.chasen.name podman[1198497]: 2023-01-18 22:20:02.279117772 -0500 EST m=+33.973682770 container remove 78ba0146d5531f7f00d1515ce4367ec293f9081d176860b88bd2cf0d79bfad0c (image=docker.io/zadam/trilium:0.57-latest, name=trilium)
```

`journalctl --since "1 days ago" -b0 -t systemd-oomd`

```
Jan 18 22:19:05 pine.827.chasen.name systemd-oomd[577]: Killed /user.slice/user-1000.slice/user@1000.service/user.slice/libpod-78ba0146d5531f7f00d1515ce4367ec293f9081d176860b88bd2cf0d79bfad0c.scope/container due to memory pressure for /user.slice/user-1000.slice/user@1000.service being 72.76% > 50.00% for > 20s with reclaim activity
```

Now that it is stopped, I have 750060 bytes reported by `free`

 ```
               total        used        free      shared  buff/cache   available
Mem:          978308      147240       29776          60      801292      750060
Swap:         977916       53044      924872
```

**Comment by zadam** [comment]
> What is the expected memory footprint?

This depends on the data set. Trilium backend caches the whole tree structure (without contents) in memory for fast access. My database with ~30 000 notes takes ~200 MB RAM on the server. 

Would you be willing to provide an [anonymized database](https://github.com/zadam/trilium/wiki/Anonymized-database) to zadam.apps@gmail.com? This would allow me to look for something suspicious.

**Comment by chaseadam** [comment]
Sent anonymized DB. This is happening less often, but still getting this with 0.63-latest docker.

It is possible I am adding images and other blobs which are blowing up the db?

```

<--- Last few GCs --->

[1:0xffffaa882010] 1345502065 ms: Mark-sweep 2044.3 (2083.5) -> 2043.4 (2083.8) MB, 6918.6 / 1.3 ms  (average mu = 0.975, current mu = 0.955) task; scavenge might not succeed
[1:0xffffaa882010] 1345651555 ms: Mark-sweep 2044.2 (2083.8) -> 2043.6 (2084.0) MB, 6875.6 / 0.5 ms  (average mu = 0.968, current mu = 0.954) task; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```
