### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by dvai** [zadam/trilium#3527]
### Trilium Version

	0.58.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

debian

### Description

left launchbar disappears when the webpage is accessed
![image](https://user-images.githubusercontent.com/33273040/212520808-1e887f0d-a20e-43d6-99b8-bd8337c1b147.png)

**Comment by zadam** [comment]
Hello, could you please post here [error logs](https://github.com/zadam/trilium/wiki/Error-logs)? Thanks.

**Comment by SiriusXT** [comment]
I think you are using your own theme, but the customized theme does not adapt to the new version, please try to switch the default theme.

**Comment by dvai** [comment]
> Hello, could you please post here [error logs](https://github.com/zadam/trilium/wiki/Error-logs)? Thanks.

```
Uncaught (in promise) Error: Cannot find module '@electron/remote'
    at e ( sync:2:10)
    at Object.b [as dynamicRequire] (utils.js:283:16)
    at ci.doRender (history_navigation.js:26:28)
    at ci.render (basic_widget.js:73:14)
    at hi.doRender (launcher.js:26:41)
    at hi.render (basic_widget.js:73:14)
    at pi.renderChildren (container.js:11:40)
    at pi.load (launcher_container.js:48:14)
ws.js:18 21:18:42 Loading tabs '[{"ntxId":"dMmJ","mainNtxId":null,"notePath":"root","hoistedNoteId":"root","active":false},{"ntxId":"NPvW","mainNtxId":null,"notePath":"root/_hidden/_options/_optionsAppearance","hoistedNoteId":"_options","active":true}]' failed: Cannot read properties of undefined (reading 'toggleClass') TypeError: Cannot read properties of undefined (reading 'toggleClass')
    at ai.toggleInt (https://domain/assets/v0.58.4/app-dist/desktop.js:2:107314)
    at ai.refresh (https://domain/assets/v0.58.4/app-dist/desktop.js:2:109211)
    at ai.noteSwitched (https://domain/assets/v0.58.4/app-dist/desktop.js:2:109546)
    at ai.noteSwitchedEvent (https://domain/assets/v0.58.4/app-dist/desktop.js:2:109499)
    at ai.callMethod (https://domain/assets/v0.58.4/app-dist/desktop.js:2:22671)
    at ai.handleEvent (https://domain/assets/v0.58.4/app-dist/desktop.js:2:22051)
    at hi.handleEventInChildren (https://domain/assets/v0.58.4/app-dist/desktop.js:2:22420)
    at hi.handleEvent (https://domain/assets/v0.58.4/app-dist/desktop.js:2:22090)
    at pi.handleEventInChildren (https://domain/assets/v0.58.4/app-dist/desktop.js:2:22420)
    at pi.handleEvent (https://domain/assets/v0.58.4/app-dist/desktop.js:2:22090)
C @ ws.js:18
basic_widget.js:120 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toggleClass')
    at ai.toggleInt (basic_widget.js:120:22)
    at ai.refresh (note_context_aware_widget.js:50:18)
    at ai.activeContextChanged (note_context_aware_widget.js:84:20)
    at ai.activeContextChangedEvent (note_context_aware_widget.js:80:20)
    at ai.callMethod (component.js:104:29)
    at ai.handleEvent (component.js:48:24)
    at hi.handleEventInChildren (component.js:74:31)
    at hi.handleEvent (component.js:50:42)
    at pi.handleEventInChildren (component.js:74:31)
    at pi.handleEvent (component.js:50:42)
syhtr.woff2:1          Failed to load resource: the server responded with a status of 404 (Not Found)

```

**Comment by zadam** [comment]
@dvai is this in browser, not in the desktop app? Also, did you add the history navigation buttons (forward/back) to the launchbar?

**Comment by dvai** [comment]
@zadam This problem only appears in browsers，and I add the history navigation buttons to the launchbar

**Comment by Nriver** [comment]
Reset the launch bar can fix this temporarily.

**Comment by zadam** [comment]
@dvai ok, got it. Please hang on for 0.58.6 or as @Nriver says reset the launchbar in the desktop version.

**Comment by eliandoran** [comment]
Probably fixed as part of 0.58.6.
