### ISSUE TITLE
(Bug report) error during migration to version 206

### ISSUE THREAD

**Issue by OlegMaloglovets** [zadam/trilium#3536]
### Trilium Version

0.58.6

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Windows 10

### Description

Migration to version 205 has been successful.
Attempting migration to version 206
Migration with JS module
Becca (note cache) load took 4ms
ERROR: error during migration to version 206: TypeError: Cannot read properties of undefined (reading 'getChildBranches')
    at /usr/src/app/db/migrations/0206__delete_search_and_sql_console_history.js:15:47
    at /usr/src/app/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/usr/src/app/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/usr/src/app/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/usr/src/app/src/services/cls.js:5:22)
    at module.exports (/usr/src/app/db/migrations/0206__delete_search_and_sql_console_history.js:8:9)
    at executeMigration (/usr/src/app/src/services/migration.js:85:9)
    at Function.<anonymous> (/usr/src/app/src/services/migration.js:56:17)
    at Function.sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (/usr/src/app/src/services/sql.js:242:52)
ERROR: migration failed, crashing hard

**Comment by OlegMaloglovets** [comment]
Update docker image to latest tag

**Comment by cirulls** [comment]
I'm getting the same error when starting Trilium 0.58.6 on Ubuntu 20.04 on local (no-sync) using the [flatpak package](https://flathub.org/apps/details/com.github.zadam.trilium) (package updated on 16th January 2023, version 0.58.6). It was working fine with the previous flatpak version (0.58.5). 

This is the full error message I'm getting after updating the flatpak package and running `flatpak run com.github.zadam.trilium`:

```
Migration to version 205 has been successful.
Attempting migration to version 206
Migration with JS module
Becca (note cache) load took 3ms
ERROR: error during migration to version 206: TypeError: Cannot read properties of undefined (reading 'getChildBranches')
    at /app/trilium/resources/app.asar/db/migrations/0206__delete_search_and_sql_console_history.js:15:47
    at /app/trilium/resources/app.asar/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/app/trilium/resources/app.asar/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/app/trilium/resources/app.asar/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/app/trilium/resources/app.asar/src/services/cls.js:5:22)
    at module.exports (/app/trilium/resources/app.asar/db/migrations/0206__delete_search_and_sql_console_history.js:8:9)
    at executeMigration (/app/trilium/resources/app.asar/src/services/migration.js:85:9)
    at Function.<anonymous> (/app/trilium/resources/app.asar/src/services/migration.js:56:17)
    at Function.sqliteTransaction (/app/trilium/resources/app.asar/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (/app/trilium/resources/app.asar/src/services/sql.js:242:52)
ERROR: migration failed, crashing hard
TypeError: The database connection is not open
    at Function.sqliteTransaction (/app/trilium/resources/app.asar/node_modules/better-sqlite3/lib/methods/transaction.js:66:9)
    at Object.transactional (/app/trilium/resources/app.asar/src/services/sql.js:242:52)
    at migrate (/app/trilium/resources/app.asar/src/services/migration.js:51:9)
    at async Object.migrateIfNecessary (/app/trilium/resources/app.asar/src/services/migration.js:117:9)
    at async initDbConnection (/app/trilium/resources/app.asar/src/services/sql_init.js:41:5)
TypeError: The database connection is not open
    at Function.sqliteTransaction (/app/trilium/resources/app.asar/node_modules/better-sqlite3/lib/methods/transaction.js:66:9)
    at Object.transactional (/app/trilium/resources/app.asar/src/services/sql.js:242:52)
    at migrate (/app/trilium/resources/app.asar/src/services/migration.js:51:9)
    at async Object.migrateIfNecessary (/app/trilium/resources/app.asar/src/services/migration.js:117:9)
    at async initDbConnection (/app/trilium/resources/app.asar/src/services/sql_init.js:41:5)
(node:3) UnhandledPromiseRejectionWarning: TypeError: The database connection is not open
    at Function.sqliteTransaction (/app/trilium/resources/app.asar/node_modules/better-sqlite3/lib/methods/transaction.js:66:9)
    at Object.transactional (/app/trilium/resources/app.asar/src/services/sql.js:242:52)
    at migrate (/app/trilium/resources/app.asar/src/services/migration.js:51:9)
    at async Object.migrateIfNecessary (/app/trilium/resources/app.asar/src/services/migration.js:117:9)
    at async initDbConnection (/app/trilium/resources/app.asar/src/services/sql_init.js:41:5)
(Use `trilium --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by zadam** [comment]
Thank you for reporting this. This was a regression from the 0.58.6. Please try 0.58.7.

**Comment by cirulls** [comment]
I confirm this is now working fine with 0.58.7 using the flatpak package. Thanks for the quick turnaround on this.
