### ISSUE TITLE
Can't export in macOS Mojave

### ISSUE THREAD

**Issue by MasaAri** [zadam/trilium#362]
Hi.

I like this app very much and I use it in my study.
However, I cannot export my note.  Do you have a good idea to solve this?

I use macOS Mojave 10.14.2 (I am Japanese so I use Japanese version) and Trilium 0.27.4 (I use it only in local).

**Comment by zadam** [comment]
Can you please show a log in /Users/[user]/Library/Application Support/trilium-data/log?

**Comment by MasaAri** [comment]
OK, and I find logs(errors) reported when I try to export notes.

-------------------------------------------------------------------------------------------------
09:50:06.512 INFO  GET /api/notes/9yNPXmdoejf7/export/subtree/html?protectedSessionId=null 
09:50:06.529 INFO  ERROR: Error executing transaction, executing rollback. Inner exception: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (_http_outgoing.js:473:3)
    at Object.exportToTar (/Applications/Trilium Notes.app/Contents/Resources/app/src/services/export/tar.js:224:9)Error
    at Object.transactional (/Applications/Trilium Notes.app/Contents/Resources/app/src/services/sql.js:164:19)
    at cls.init (/Applications/Trilium Notes.app/Contents/Resources/app/src/routes/routes.js:73:38)
    at /Applications/Trilium Notes.app/Contents/Resources/app/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/Applications/Trilium Notes.app/Contents/Resources/app/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/Applications/Trilium Notes.app/Contents/Resources/app/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/Applications/Trilium Notes.app/Contents/Resources/app/src/services/cls.js:5:28)
    at router.(anonymous function) (/Applications/Trilium Notes.app/Contents/Resources/app/src/routes/routes.js:68:38)
    at Layer.handle [as handle_request] (/Applications/Trilium Notes.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/Applications/Trilium Notes.app/Contents/Resources/app/node_modules/express/lib/router/route.js:137:13)
    at checkApiAuthOrElectron (/Applications/Trilium Notes.app/Contents/Resources/app/src/services/auth.js:28:9) 
09:50:06.530 INFO  ERROR: get /api/notes/:branchId/export/:type/:format threw exception: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
    at ServerResponse.setHeader (_http_outgoing.js:473:3)
    at Object.exportToTar (/Applications/Trilium Notes.app/Contents/Resources/app/src/services/export/tar.js:224:9)

**Comment by zadam** [comment]
I see, this has been fixed in 0.28 which is still in beta.

**Comment by MasaAri** [comment]
Thank you for fixing that issue.
I am looking forward to version 0.28!
