### ISSUE TITLE
(Bug report) External spell checker error with CKEditor

### ISSUE THREAD

**Issue by Alexconquer** [zadam/trilium#3620]
### Trilium Version

0.58.8

### What operating system are you using?

Other (specify below)

### What is your setup?

Server access only

### Operating System Version

Docker on Debian

### Description

Hello,

I have just discovered lithium and I find it very interesting, but I have a problem.

I use a external spell checker (Merci app)
but i get browser console error in Trilium note when want fix the mistake.

my extension correctly highlight spelling mistakes but fail to replace the text to fix the mistake.

For testing, i disable a integrated spell checker, no effect

### Error logs

ws.js:18 23:11:06 Uncaught error: Message: Uncaught CKEditorError: Cannot read properties of undefined (reading 'contains')
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-Cannot read properties of undefined (reading 'contains'), URL: , Line: 6, Column: 347741, Error object: {"name":"CKEditorError","context":{}}, Stack: TypeError: Cannot read properties of undefined (reading 'contains')
    at Hb.isResizeHandle (<anonymous>:6:865594)
    at Ub._mouseDownListener (<anonymous>:6:869669)
    at Object.fire (<anonymous>:6:349341)
    at fs (<anonymous>:6:433953)
    at ws.fire (<anonymous>:6:433360)
    at ih.fire (<anonymous>:6:475364)
    at ih.onDomEvent (<anonymous>:6:671284)
    at listenTo.useCapture (<anonymous>:6:475273)
    at So.fire (<anonymous>:6:349341)
    at HTMLDivElement.e (<anonymous>:6:372453)
N @ ws.js:18
window.onerror @ glob.js:61
(anonymous) @ contentScript.bundle.js:1
zx @ contentScript.bundle.js:1
Gx @ contentScript.bundle.js:1
e.onSelectCorrection @ contentScript.bundle.js:1
e.didSelectSuggestion @ contentScript.bundle.js:1
o @ contentScript.bundle.js:1
VM1035:6 Uncaught TypeError: Cannot read properties of undefined (reading 'contains')
    at Hb.isResizeHandle (<anonymous>:6:865594)
    at Ub._mouseDownListener (<anonymous>:6:869669)
    at Object.fire (<anonymous>:6:349341)
    at fs (<anonymous>:6:433953)
    at ws.fire (<anonymous>:6:433360)
    at ih.fire (<anonymous>:6:475364)
    at ih.onDomEvent (<anonymous>:6:671284)
    at listenTo.useCapture (<anonymous>:6:475273)
    at So.fire (<anonymous>:6:349341)
    at HTMLDivElement.e (<anonymous>:6:372453)
rethrowUnexpectedError @ VM1035:6
fire @ VM1035:6
fs @ VM1035:6
fire @ VM1035:6
fire @ VM1035:6
onDomEvent @ VM1035:6
listenTo.useCapture @ VM1035:6
fire @ VM1035:6
e @ VM1035:6

**Comment by Alexconquer** [comment]
For more logs i found this in container logs : 

```
JS Error: Uncaught error: Message: Uncaught CKEditorError: Cannot read properties of undefined (reading 'contains')
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-Cannot read properties of undefined (reading 'contains'), URL: , Line: 6, Column: 347741, Error object: {"name":"CKEditorError","context":{}}, Stack: TypeError: Cannot read properties of undefined (reading 'contains')
    at Hb.isResizeHandle (<anonymous>:6:865594)
    at Ub._mouseDownListener (<anonymous>:6:869669)
    at Object.fire (<anonymous>:6:349341)
    at fs (<anonymous>:6:433953)
    at ws.fire (<anonymous>:6:433360)
    at ih.fire (<anonymous>:6:475364)
    at ih.onDomEvent (<anonymous>:6:671284)
    at listenTo.useCapture (<anonymous>:6:475273)
    at So.fire (<anonymous>:6:349341)
    at HTMLDivElement.e (<anonymous>:6:372453)


Stack: Error
    at Object.N [as logError] (https://note.lanath.fr/assets/v0.58.8/app-dist/desktop.js:2:103715)
    at window.onerror (https://note.lanath.fr/assets/v0.58.8/app-dist/desktop.js:2:607706)
```

**Comment by Alexconquer** [comment]
The bug comes from the extension, it's solved
