### ISSUE TITLE
(Bug report) Trilium sync from clients to server fails for a specific daily journal note

### ISSUE THREAD

**Issue by czen** [zadam/trilium#3626]
### Trilium Version

0.58.7

### What operating system are you using?

Ubuntu

### What is your setup?

Local + server sync

### Operating System Version

Linux Mint 20.1 and Windows 10 for clients, Debian 11 for server

### Description

I have Trilium installed on a Debian 11 server to sync with Linux and Windows clients.

I've created a daily note in the morning of 20.02.23, added some text to it.
Then after 15:00 PM I've noticed that any edits I do in that daily note or any of it's child notes don't get synced. Instead any edit gets removed after sync attempt with no error message being displayed. Tried it with 2 clients, every time the sync would result in client's note being replaced with the server's version of the daily note.
So I've deleted that note and sync now works. I don't know how to further investigate the issue, so I can just provide fully anonymized db and the daily log file. The daily note was the last one deleted.

Some error does appear in the log:

```
16:40:30.813 JS Error: Can't find note 0LKt6C8L7y3s
Stack: Error
    at Object.N [as logError] (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:103771)
    at Object.d [as resolveNotePathToSegments] (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:89560)
    at async V.getNodeFromPath (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:175880)
    at async V.refresh (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:177265)
    at async V.noteSwitched (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:110555)
    at async V.noteSwitchedEvent (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:110508)
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
16:40:30.813 JS Error: Could not find run path for notePath:
Stack: Error
    at N (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:103771)
    at V.getNodeFromPath (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:176454)
    at async V.refresh (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:177265)
    at async V.noteSwitched (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:110555)
    at async V.noteSwitchedEvent (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:110508)
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
16:40:30.819 200 GET /api/search/%23workspace%20%23!template with 16 bytes took 5ms
16:40:30.822 200 GET /api/search/%23workspace%20%23!template with 16 bytes took 3ms
16:40:30.825 200 GET /api/search/%23workspace%20%23!template with 16 bytes took 3ms
16:40:30.825 JS Error: Can't find note 0LKt6C8L7y3s
Stack: Error
    at Object.N [as logError] (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:103771)
    at Object.d [as resolveNotePathToSegments] (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:89560)
    at async V.getNodeFromPath (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:175880)
    at async V.refresh (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:177265)
    at async V.noteSwitched (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:110555)
    at async V.noteSwitchedEvent (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:110508)
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
16:40:30.825 JS Error: Could not find run path for notePath:
Stack: Error
    at N (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:103771)
    at V.getNodeFromPath (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:176454)
    at async V.refresh (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:177265)
    at async V.noteSwitched (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:110555)
    at async V.noteSwitchedEvent (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:110508)
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
16:40:30.825 JS Error: Can't find note 0LKt6C8L7y3s
Stack: Error
    at Object.N [as logError] (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:103771)
    at Object.d [as resolveNotePathToSegments] (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:89560)
    at async V.getNodeFromPath (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:175880)
    at async V.refresh (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:177265)
    at async V.noteSwitched (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:110555)
    at async V.noteSwitchedEvent (http://127.0.0.1:37840/assets/v0.58.7/app-dist/desktop.js:2:110508)
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
```

and there are other error messages.

### Error logs

[trilium-2023-02-20.log](https://github.com/zadam/trilium/files/10785028/trilium-2023-02-20.log)

**Comment by czen** [comment]
here's a fully anonymized db file

[anonymized-full-2023-02-20T134517.db.zip](https://github.com/zadam/trilium/files/10785088/anonymized-full-2023-02-20T134517.db.zip)

**Comment by mid1221213** [comment]
Hi,

I encountered the same kind of problem, maybe in notes where I tried to paste text with emojis in it.

After that action the layout was broken (pasted text was partly hidden behind the left border), and even after deleting this part of the text, every change I made was not saved in the server with the same kind of error message as mentioned in this bug report.

After deleting the notes (in which I lost several parts of text entered afterwards) and creating new ones, the problem did not occur again.

So for now I avoid pasting emojis in any note.

Not sure it is related but it may help.

**Comment by eliandoran** [comment]
Closing as stale, since quite some time has passed since the original issue and the sync management has been made more tolerant.
