### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by GerGitHub** [zadam/trilium#3644]
### Trilium Version

0.58.8

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Photon OS Docker server

### Description

docker run -itd --name=Trilium --restart=always -p 0.0.0.0:8080:8080 -v /opt/notebook:/home/node/trilium-data zadam/trilium
notebook is a mount NFS shared directory
host : 10.10.1.111

If the host directory is a shared directory mount NFS, Trilium will report an error after a few minutes and you will need to refresh the browser and login again. 

Error when calling PUT notes/UtLliiX8PHN2: error - Unauthorized.

### Error logs

[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open '/root/trilium-data/sessions/cN8YbZR35_-nZDktfLwVuCje8odMMXnz.json'
PUT /api/notes/UtLliiX8PHN2 rejected with 401 Logged in session not found
JS Error: Error when calling PUT notes/UtLliiX8PHN2: error - Unauthorized

Stack: Error
at Object.N [as logError] (http://10.10.1.111:8080/app-dist/desktop.js:2:97436)
at Object.throwError (http://10.10.1.111:8080/app-dist/desktop.js:2:82914)
at c (http://10.10.1.111:8080/app-dist/desktop.js:2:79764)
at async Object.error (http://10.10.1.111:8080/app-dist/desktop.js:2:80072)

**Comment by GerGitHub** [comment]
I understand.
option/password/Protected session timeout
