### ISSUE TITLE
(Bug report) 

### ISSUE THREAD

**Issue by Pierre-Gronau-ndaal** [zadam/trilium#3792]
### Trilium Version

0.5.93

### What operating system are you using?

macOS

### What is your setup?

Local (no sync)

### Operating System Version

macOS Ventura 13.3 

### Description

got:

npm install         
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated uuid@3.3.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/cloud/repos/trilium/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c prebuild-install || npm run build-release
npm ERR! > better-sqlite3@7.4.5 build-release
npm ERR! > node-gyp rebuild --release
npm ERR! 
npm ERR!   TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR!   ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR!   TOUCH Release/obj.target/deps/locate_sqlite3.stamp
npm ERR!   CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
npm ERR!   LIBTOOL-STATIC Release/sqlite3.a
npm ERR!   CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
npm ERR! rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR! prebuild-install warn install No prebuilt binaries found (target=19.8.1 runtime=node arch=x64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@19.8.1 | darwin | x64
npm ERR! gyp info find Python using Python version 3.11.2 found at "/usr/local/opt/python@3.11/bin/python3.11"
npm ERR! gyp info spawn /usr/local/opt/python@3.11/bin/python3.11
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/cloud/repos/trilium/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/cloud/repos/trilium/node_modules/better-sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/cloud/repos/trilium/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/cloud/Library/Caches/node-gyp/19.8.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/cloud/repos/trilium/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/cloud/Library/Caches/node-gyp/19.8.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/cloud/repos/trilium/node_modules/better-sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR! 
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/better_sqlite3.cpp:4:
npm ERR! In file included from ./src/better_sqlite3.lzz:11:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/node.h:73:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8.h:24:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-array-buffer.h:12:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-local-handle.h:12:
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:477:30: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! SHARED_EXTERNAL_POINTER_TAGS(CHECK_SHARED_EXTERNAL_POINTER_TAGS)
npm ERR!                              ^
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:477:30: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:477:30: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:477:30: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:477:30: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! PER_ISOLATE_EXTERNAL_POINTER_TAGS(CHECK_NON_SHARED_EXTERNAL_POINTER_TAGS)
npm ERR!                                   ^
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:659:61: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR!     static_assert(kJSObjectType + 1 == kFirstJSApiObjectType);
npm ERR!                                                             ^
npm ERR!                                                             , ""
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:660:55: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR!     static_assert(kJSObjectType < kLastJSApiObjectType);
npm ERR!                                                       ^
npm ERR!                                                       , ""
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:661:63: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
npm ERR!     static_assert(kFirstJSApiObjectType < kLastJSApiObjectType);
npm ERR!                                                               ^
npm ERR!                                                               , ""
npm ERR! In file included from ../src/better_sqlite3.cpp:4:
npm ERR! In file included from ./src/better_sqlite3.lzz:11:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/node.h:73:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8.h:24:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-array-buffer.h:13:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-object.h:9:
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-maybe.h:106:45: error: no template named 'is_lvalue_reference_v' in namespace 'std'; did you mean 'is_lvalue_reference'?
npm ERR!   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
npm ERR!                                        ~~~~~^~~~~~~~~~~~~~~~~~~~~
npm ERR!                                             is_lvalue_reference
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:942:29: note: 'is_lvalue_reference' declared here
npm ERR! struct _LIBCPP_TEMPLATE_VIS is_lvalue_reference : _BoolConstant<__is_lvalue_reference(_Tp)> { };
npm ERR!                             ^
npm ERR! In file included from ../src/better_sqlite3.cpp:4:
npm ERR! In file included from ./src/better_sqlite3.lzz:11:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/node.h:73:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8.h:24:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-array-buffer.h:13:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-object.h:9:
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-maybe.h:106:69: error: expected '(' for function-style cast or type construction
npm ERR!   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
npm ERR!                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-maybe.h:123:43: error: no template named 'is_lvalue_reference_v' in namespace 'std'; did you mean 'is_lvalue_reference'?
npm ERR! template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
npm ERR!                                      ~~~~~^~~~~~~~~~~~~~~~~~~~~
npm ERR!                                           is_lvalue_reference
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:942:29: note: 'is_lvalue_reference' declared here
npm ERR! struct _LIBCPP_TEMPLATE_VIS is_lvalue_reference : _BoolConstant<__is_lvalue_reference(_Tp)> { };
npm ERR!                             ^
npm ERR! In file included from ../src/better_sqlite3.cpp:4:
npm ERR! In file included from ./src/better_sqlite3.lzz:11:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/node.h:73:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8.h:24:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-array-buffer.h:13:
npm ERR! In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-object.h:9:
npm ERR! /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-maybe.h:123:67: error: expected '(' for function-style cast or type construction
npm ERR! template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
npm ERR!                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
npm ERR! ./src/util/macros.lzz:157:21: error: no member named 'AccessorSignature' in namespace 'v8'
npm ERR!                 v8::AccessorSignature::New(isolate, recv)
npm ERR!                 ~~~~^
npm ERR! ./src/util/binder.lzz:37:51: error: no member named 'CreationContext' in 'v8::Object'
npm ERR!                 v8::Local<v8::Context> ctx = obj->CreationContext();
npm ERR!                                              ~~~~~^
npm ERR! 20 warnings and 6 errors generated.
npm ERR! make: *** [Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/cloud/repos/trilium/node_modules/node-gyp/lib/build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.4.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/19.8.1/bin/node" "/Users/cloud/repos/trilium/node_modules/.bin/node-gyp" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/cloud/repos/trilium/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v19.8.1
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /Users/cloud/.npm/_logs/2023-04-02T10_14_54_125Z-debug-0.log

### Error logs

1323 verbose stack     at Socket.<anonymous> (node:internal/child_process:456:11)
1323 verbose stack     at Socket.emit (node:events:512:28)
1323 verbose stack     at Pipe.<anonymous> (node:net:332:12)
1324 verbose pkgid better-sqlite3@7.4.5
1325 verbose cwd /Users/cloud/repos/trilium
1326 verbose Darwin 22.4.0
1327 verbose node v19.8.1
1328 verbose npm  v9.5.1
1329 error code 1
1330 error path /Users/cloud/repos/trilium/node_modules/better-sqlite3
1331 error command failed
1332 error command sh -c prebuild-install || npm run build-release
1333 error > better-sqlite3@7.4.5 build-release
1333 error > node-gyp rebuild --release
1333 error
1333 error   TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
1333 error   ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
1333 error   TOUCH Release/obj.target/deps/locate_sqlite3.stamp
1333 error   CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
1333 error   LIBTOOL-STATIC Release/sqlite3.a
1333 error   CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
1333 error rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
1334 error prebuild-install warn install No prebuilt binaries found (target=19.8.1 runtime=node arch=x64 libc= platform=darwin)
1334 error gyp info it worked if it ends with ok
1334 error gyp info using node-gyp@9.1.0
1334 error gyp info using node@19.8.1 | darwin | x64
1334 error gyp info find Python using Python version 3.11.2 found at "/usr/local/opt/python@3.11/bin/python3.11"
1334 error gyp info spawn /usr/local/opt/python@3.11/bin/python3.11
1334 error gyp info spawn args [
1334 error gyp info spawn args   '/Users/cloud/repos/trilium/node_modules/node-gyp/gyp/gyp_main.py',
1334 error gyp info spawn args   'binding.gyp',
1334 error gyp info spawn args   '-f',
1334 error gyp info spawn args   'make',
1334 error gyp info spawn args   '-I',
1334 error gyp info spawn args   '/Users/cloud/repos/trilium/node_modules/better-sqlite3/build/config.gypi',
1334 error gyp info spawn args   '-I',
1334 error gyp info spawn args   '/Users/cloud/repos/trilium/node_modules/node-gyp/addon.gypi',
1334 error gyp info spawn args   '-I',
1334 error gyp info spawn args   '/Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/common.gypi',
1334 error gyp info spawn args   '-Dlibrary=shared_library',
1334 error gyp info spawn args   '-Dvisibility=default',
1334 error gyp info spawn args   '-Dnode_root_dir=/Users/cloud/Library/Caches/node-gyp/19.8.1',
1334 error gyp info spawn args   '-Dnode_gyp_dir=/Users/cloud/repos/trilium/node_modules/node-gyp',
1334 error gyp info spawn args   '-Dnode_lib_file=/Users/cloud/Library/Caches/node-gyp/19.8.1/<(target_arch)/node.lib',
1334 error gyp info spawn args   '-Dmodule_root_dir=/Users/cloud/repos/trilium/node_modules/better-sqlite3',
1334 error gyp info spawn args   '-Dnode_engine=v8',
1334 error gyp info spawn args   '--depth=.',
1334 error gyp info spawn args   '--no-parallel',
1334 error gyp info spawn args   '--generator-output',
1334 error gyp info spawn args   'build',
1334 error gyp info spawn args   '-Goutput_dir=.'
1334 error gyp info spawn args ]
1334 error No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
1334 error
1334 error No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
1334 error
1334 error No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
1334 error
1334 error gyp info spawn make
1334 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
1334 error In file included from ../src/better_sqlite3.cpp:4:
1334 error In file included from ./src/better_sqlite3.lzz:11:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/node.h:73:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8.h:24:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-array-buffer.h:12:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-local-handle.h:12:
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:477:30: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error SHARED_EXTERNAL_POINTER_TAGS(CHECK_SHARED_EXTERNAL_POINTER_TAGS)
1334 error                              ^
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:477:30: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:477:30: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:477:30: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:477:30: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error PER_ISOLATE_EXTERNAL_POINTER_TAGS(CHECK_NON_SHARED_EXTERNAL_POINTER_TAGS)
1334 error                                   ^
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:478:35: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:659:61: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error     static_assert(kJSObjectType + 1 == kFirstJSApiObjectType);
1334 error                                                             ^
1334 error                                                             , ""
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:660:55: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error     static_assert(kJSObjectType < kLastJSApiObjectType);
1334 error                                                       ^
1334 error                                                       , ""
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-internal.h:661:63: warning: static_assert with no message is a C++17 extension [-Wc++17-extensions]
1334 error     static_assert(kFirstJSApiObjectType < kLastJSApiObjectType);
1334 error                                                               ^
1334 error                                                               , ""
1334 error In file included from ../src/better_sqlite3.cpp:4:
1334 error In file included from ./src/better_sqlite3.lzz:11:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/node.h:73:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8.h:24:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-array-buffer.h:13:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-object.h:9:
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-maybe.h:106:45: error: no template named 'is_lvalue_reference_v' in namespace 'std'; did you mean 'is_lvalue_reference'?
1334 error   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
1334 error                                        ~~~~~^~~~~~~~~~~~~~~~~~~~~
1334 error                                             is_lvalue_reference
1334 error /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:942:29: note: 'is_lvalue_reference' declared here
1334 error struct _LIBCPP_TEMPLATE_VIS is_lvalue_reference : _BoolConstant<__is_lvalue_reference(_Tp)> { };
1334 error                             ^
1334 error In file included from ../src/better_sqlite3.cpp:4:
1334 error In file included from ./src/better_sqlite3.lzz:11:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/node.h:73:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8.h:24:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-array-buffer.h:13:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-object.h:9:
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-maybe.h:106:69: error: expected '(' for function-style cast or type construction
1334 error   template <class U, std::enable_if_t<!std::is_lvalue_reference_v<U>>*>
1334 error                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-maybe.h:123:43: error: no template named 'is_lvalue_reference_v' in namespace 'std'; did you mean 'is_lvalue_reference'?
1334 error template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
1334 error                                      ~~~~~^~~~~~~~~~~~~~~~~~~~~
1334 error                                           is_lvalue_reference
1334 error /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:942:29: note: 'is_lvalue_reference' declared here
1334 error struct _LIBCPP_TEMPLATE_VIS is_lvalue_reference : _BoolConstant<__is_lvalue_reference(_Tp)> { };
1334 error                             ^
1334 error In file included from ../src/better_sqlite3.cpp:4:
1334 error In file included from ./src/better_sqlite3.lzz:11:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/node.h:73:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8.h:24:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-array-buffer.h:13:
1334 error In file included from /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-object.h:9:
1334 error /Users/cloud/Library/Caches/node-gyp/19.8.1/include/node/v8-maybe.h:123:67: error: expected '(' for function-style cast or type construction
1334 error template <class T, std::enable_if_t<!std::is_lvalue_reference_v<T>>* = nullptr>
1334 error                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
1334 error ./src/util/macros.lzz:157:21: error: no member named 'AccessorSignature' in namespace 'v8'
1334 error                 v8::AccessorSignature::New(isolate, recv)
1334 error                 ~~~~^
1334 error ./src/util/binder.lzz:37:51: error: no member named 'CreationContext' in 'v8::Object'
1334 error                 v8::Local<v8::Context> ctx = obj->CreationContext();
1334 error                                              ~~~~~^
1334 error 20 warnings and 6 errors generated.
1334 error make: *** [Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
1334 error gyp ERR! build error 
1334 error gyp ERR! stack Error: `make` failed with exit code: 2
1334 error gyp ERR! stack     at ChildProcess.onExit (/Users/cloud/repos/trilium/node_modules/node-gyp/lib/build.js:201:23)
1334 error gyp ERR! stack     at ChildProcess.emit (node:events:512:28)
1334 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
1334 error gyp ERR! System Darwin 22.4.0
1334 error gyp ERR! command "/usr/local/Cellar/node/19.8.1/bin/node" "/Users/cloud/repos/trilium/node_modules/.bin/node-gyp" "rebuild" "--release"
1334 error gyp ERR! cwd /Users/cloud/repos/trilium/node_modules/better-sqlite3
1334 error gyp ERR! node -v v19.8.1
1334 error gyp ERR! node-gyp -v v9.1.0
1334 error gyp ERR! not ok
1335 verbose exit 1
1336 timing npm Completed in 26695ms
1337 verbose unfinished npm timer reify 1680430118262
1338 verbose unfinished npm timer reify:build 1680430122528
1339 verbose unfinished npm timer build 1680430122530
1340 verbose unfinished npm timer build:deps 1680430122530
1341 verbose unfinished npm timer build:run:install 1680430122561
1342 verbose unfinished npm timer build:run:install:node_modules/better-sqlite3 1680430122561
1343 verbose code 1
1344 error A complete log of this run can be found in:

**Comment by Nriver** [comment]
node 19 is not supported

**Comment by zadam** [comment]
It's recommended to use one of the [pre-built packages](https://github.com/zadam/trilium/releases/tag/v0.59.3) or a docker image.
