### ISSUE TITLE
consistency-checks-failed

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#382]
I started getting this suddenly, I am not sure about how to locate the issue. 

I am on Debian, using the desktop app release

```Content hash checks PASSED
Trace: ERROR: Attribute reference to the owning note is broken: 'ES5YxZe5Fgcn'
    at Object.error (/opt/trillium/resources/app.asar/src/services/log.js:33:13)
    at runCheck (/opt/trillium/resources/app.asar/src/services/consistency_checks.js:20:13)
Consistency checks failed (took 15ms) with these errors: ["Attribute reference to the owning note is broken: 'ES5YxZe5Fgcn'"]
Sending message to all clients: {"type":"consistency-checks-failed"}

```

**Comment by zadam** [comment]
Would it be possible to attach the logs? This would allow me to investigate the issue. Please zip the whole log folder and attach it here. Log directory is in:

* `/home/[user]/.local/share/trilium-data/log` for Linux
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

**Comment by zadam** [comment]
Logs should not have any personal information - they mostly log what happened to note XYZ etc.

**Comment by gerroon** [comment]
Ok I will take a look at it.

**Comment by gerroon** [comment]
Would this do it"

```
DB ready.
DB size: 954 KB
Slow query took 1157ms: INSERT  INTO source_ids(sourceId, dateCreated) VALUES (?, ?)
Autocomplete load took 1340ms

Trace: ERROR: Attribute reference to the owning note is broken: 'ES5YxZe5Fgcn'
    at Object.error (/usr/src/app/src/services/log.js:33:13)
    at runCheck (/usr/src/app/src/services/consistency_checks.js:20:13)
Consistency checks failed (took 744ms) with these errors: ["Attribute reference to the owning note is broken: 'ES5YxZe5Fgcn'"]                                                               
Sending message to all clients: {"type":"consistency-checks-failed"}
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open '/tmp/trilium-sessions/teBwIPyJuWs7XzyoA9oSig8qgW27pfAv.json'                         
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open '/tmp/trilium-sessions/teBwIPyJuWs7XzyoA9oSig8qgW27pfAv.json'                         
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open '/tmp/trilium-sessions/teBwIPyJuWs7XzyoA9oSig8qgW27pfAv.json'                         
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open '/tmp/trilium-sessions/teBwIPyJuWs7XzyoA9oSig8qgW27pfAv.json'                         
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open '/tmp/trilium-sessions/teBwIPyJuWs7XzyoA9oSig8qgW27pfAv.json'                         
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open '/tmp/trilium-sessions/teBwIPyJuWs7XzyoA9oSig8qgW27pfAv.json'                         
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open '/tmp/trilium-sessions/teBwIPyJuWs7XzyoA9oSig8qgW27pfAv.json'                         
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open '/tmp/trilium-sessions/teBwIPyJuWs7XzyoA9oSig8qgW27pfAv.json'                         
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open '/tmp/trilium-sessions/teBwIPyJuWs7XzyoA9oSig8qgW27pfAv.json'                         
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open '/tmp/trilium-sessions/teBwIPyJuWs7XzyoA9oSig8qgW27pfAv.json'                         
Generated sourceId=WEvv4hrTi7xU
websocket client connected
Trace: ERROR: JS Error: Can't find note "root%2FzmDffRKOAWib%2FOfJIaJiuiVmL%2Fiykb0YOKggoO"
    at Object.error (/usr/src/app/src/services/log.js:33:13)
    at WebSocket.ws.on.messageJson (/usr/src/app/src/services/messaging.js:31:21)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage (/usr/src/app/node_modules/ws/lib/websocket.js:741:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (/usr/src/app/node_modules/ws/lib/receiver.js:417:14)
    at Receiver.getData (/usr/src/app/node_modules/ws/lib/receiver.js:347:17)
    at Receiver.startLoop (/usr/src/app/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/usr/src/app/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:410:12)

```

**Comment by zadam** [comment]
This is a log showing there is an inconsistency, but it doesn't help me with tracking down where it happened - that's why I'd prefer zip of the whole log directory ...

**Comment by zadam** [comment]
closing because of lack of information
