### ISSUE TITLE
Search scripts broken

### ISSUE THREAD

**Issue by mechanarchy** [zadam/trilium#4048]
### Trilium Version

0.60.3

### What operating system are you using?

macOS

### What is your setup?

Server access only

### Operating System Version

Monterey 12.6.3

### Description

I'm trying to create a search script, currently using the example code from the tooltip verbatim:
```
// 1. prefiltering using standard search
const candidateNotes = api.searchForNotes("#journal"); 

// 2. applying custom search criteria
const matchedNotes = candidateNotes
    .filter(note => note.title.match(/[0-9]{1,2}. ?[0-9]{1,2}. ?[0-9]{4}/));

return matchedNotes;
```

Putting this into a new code 'JS (backend)' note, and selecting it on the search UI results in the following error in the web ui: `scriptService.executeNote is not a function`.

Backend log below provides more detail

### Error logs

```
ERROR: get /api/search-note/:noteId threw exception: 'scriptService.executeNote is not a function', stack: TypeError: scriptService.executeNote is not a function
    at searchFromRelation (/usr/src/app/src/services/search/services/search.js:76:34)
    at Object.searchFromNote (/usr/src/app/src/services/search/services/search.js:24:31)
    at searchFromNote (/usr/src/app/src/routes/api/search.js:28:26)
    at Function.cb (/usr/src/app/src/routes/routes.js:413:34)
    at Function.sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (/usr/src/app/src/services/sql.js:242:52)
    at /usr/src/app/src/routes/routes.js:415:44
    at /usr/src/app/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/usr/src/app/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/usr/src/app/node_modules/cls-hooked/context.js:117:8)
(node:1) Warning: Accessing non-existent property 'executeNote' of module exports inside circular dependency
JS Error: 500 GET search-note/I0NZuXkSXNUo - scriptService.executeNote is not a function
Stack: Error
    at Object.N [as logError] (https://domain.xyz/assets/v0.60.3/app-dist/desktop.js:2:103948)
    at Object.throwError (https://domain.xyz/assets/v0.60.3/app-dist/desktop.js:2:89111)
    at h (https://domain.xyz/assets/v0.60.3/app-dist/desktop.js:2:85051)
    at async Object.error (https://domain.xyz/assets/v0.60.3/app-dist/desktop.js:2:85367)
```

**Comment by zadam** [comment]
Thanks for reporting, fixed.
