### ISSUE TITLE
(Bug report) 61.3-beta Copy/Paste doesn't work

### ISSUE THREAD

**Issue by Engr-AllanG** [zadam/trilium#4143]
### Trilium Version

61.3-beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11

### Description

Unable to paste text into Trilium that was copied _outside_ of Trilium. Copy/paste works within Trilium.

This is true for both desktop app and web version. Server has been rebooted as well as desktop computer. 

### Error logs

The 3 last entries of the log are below. The first two lines is a copy/paste within Trilum. The last error section is when trying to paste in text from external source. Appears to be related to skeditor

00:57:00.688 204 PUT /api/notes/4B36K1U09TDh/data with 0 bytes took 3ms
00:57:00.692 200 GET /api/notes/4B36K1U09TDh/blob with 334 bytes took 0ms
00:57:25.651 JS Error: Uncaught error: Message: Uncaught CKEditorError: Cannot read properties of null (reading 'map')
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-Cannot read properties of null (reading 'map'), URL: http://127.0.0.1:37840/#root/dgifkd7tNI2z/wpQFuVI7325K/xSWYXLQ3O5Li/0Ly8UNqj7nre/4B36K1U09TDh?ntxId=oGnSEl, Line: 6, Column: 382002, Error object: {"name":"CKEditorError","context":{}}, Stack: TypeError: Cannot read properties of null (reading 'map')
    at Object.<anonymous> (<anonymous>:6:1290561)
    at Object.fire (<anonymous>:6:383577)
    at _s (<anonymous>:6:469768)
    at xs.fire (<anonymous>:6:469175)
    at Object.<anonymous> (<anonymous>:6:923254)
    at Object.fire (<anonymous>:6:383577)
    at _s (<anonymous>:6:469768)
    at xs.fire (<anonymous>:6:469175)
    at Vw.fire (<anonymous>:6:511653)
    at Vw.onDomEvent (<anonymous>:6:924094)
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.3-beta/app-dist/desktop.js:2:114149)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.3-beta/app-dist/desktop.js:2:653072)

**Comment by Engr-AllanG** [comment]
Woops, this is a duplicate of #4138

**Comment by zadam** [comment]
I believe I isolated the bug to a specific (relatively unimportant) ListProperties plugin and after its deactivation the paste appears to work. Fix will be in the next beta.

**Comment by dvai** [comment]
@zadam Has this issue been fixed in 0.61.4beta? I still encounter this problem in 0.61.4beta.

error logs:

> `ws.js:18 11:18:12 Uncaught error: Message: Uncaught CKEditorError: Cannot read properties of null (reading 'map')
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-Cannot read properties of null (reading 'map'), URL: , Line: 6, Column: 382018, Error object: {"name":"CKEditorError","context":{}}, Stack: TypeError: Cannot read properties of null (reading 'map')
    at Object.<anonymous> (<anonymous>:6:1261272)
    at Object.fire (<anonymous>:6:383577)
    at Cs (<anonymous>:6:469768)
    at xs.fire (<anonymous>:6:469175)
    at Object.<anonymous> (<anonymous>:6:922689)
    at Object.fire (<anonymous>:6:383577)
    at Cs (<anonymous>:6:469768)
    at xs.fire (<anonymous>:6:469175)
    at Rw.fire (<anonymous>:6:511653)
    at Rw.onDomEvent (<anonymous>:6:923529)
T @ ws.js:18
Ri.window.onerror @ glob.js:62
VM58:6 Uncaught TypeError: Cannot read properties of null (reading 'map')
    at Object.<anonymous> (<anonymous>:6:1261272)
    at Object.fire (<anonymous>:6:383577)
    at Cs (<anonymous>:6:469768)
    at xs.fire (<anonymous>:6:469175)
    at Object.<anonymous> (<anonymous>:6:922689)
    at Object.fire (<anonymous>:6:383577)
    at Cs (<anonymous>:6:469768)
    at xs.fire (<anonymous>:6:469175)
    at Rw.fire (<anonymous>:6:511653)
    at Rw.onDomEvent (<anonymous>:6:923529)
rethrowUnexpectedError @ VM58:6
fire @ VM58:6
Cs @ VM58:6
fire @ VM58:6
(anonymous) @ VM58:6
fire @ VM58:6
Cs @ VM58:6
fire @ VM58:6
fire @ VM58:6
onDomEvent @ VM58:6
listenTo.useCapture @ VM58:6
fire @ VM58:6
e @ VM58:6`

**Comment by dvai** [comment]
@zadam I have tried it myself: pasting into titles and attributes works fine, but I am unable to paste into the content of the note. Additionally, using the "pasteMarkdownIntoText" Keyboard Shortcuts  does not generate an error."
