### ISSUE TITLE
Saved Search will save but is not present in tree (Bug report) 

### ISSUE THREAD

**Issue by sottey** [zadam/trilium#4154]
### Trilium Version

0.61.3 beta

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubunto 20

### Description

When Clicking "Save Search" in search page, alert comes up saying note was saved to my inbox (inbox has #seachHome. This happened before I added that label however) but the search does not appear in the tree.

```
Log shows:
13:03:03.845 JS Error: No parents found for note QSaef1BOD0vn (Search: note.title!=Personal) for path root/7MTilC98G81P/mz4AnlL89x3B/gsqBJw1TfUk8/RcsCx2ZWBCc2/IvIAXrqOSaFk/QSaef1BOD0vn
Stack: Error
    at Object.T [as logError] (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:114149)
    at d (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:98101)
    at async Object.resolveNotePath (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:99861)
    at async I.getResolvedNotePath (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:8649)
    at async I.setNote (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:7248)
    at async HTMLButtonElement.<anonymous> (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:442076)
13:03:03.847 JS Error: Cannot resolve note path root/7MTilC98G81P/mz4AnlL89x3B/gsqBJw1TfUk8/RcsCx2ZWBCc2/IvIAXrqOSaFk/QSaef1BOD0vn
Stack: Error
    at T (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:114149)
    at I.getResolvedNotePath (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:8759)
    at async I.setNote (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:7248)
    at async HTMLButtonElement.<anonymous> (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:442076)
13:03:10.426 204 PUT /api/branches/v4yInsMGnDr6_gIkE5tChr6SY/expanded/0 with 0 bytes took 1ms
```

If I go into the SQL Console, using:
`SELECT * FROM notes WHERE noteId = 'QSaef1BOD0vn'`

I get:

noteId | title | isProtected | type | mime | blobId | isDeleted | deleteId | dateCreated | dateModified | utcDateCreated | utcDateModified
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
QSaef1BOD0vn | Search: note.title!=Personal | 0 | search | application/json | z4PhNX7vuL3xVChQ1m2A | 0 |   | 2023-08-08 05:57:07.495-0700 | 2023-08-08 06:01:03.471-0700

So the note is saved, it is just not accessible in the tree.

### Error logs

13:03:30.889 JS Error: No parents found for note QSaef1BOD0vn (Search: note.title!=Personal) for path root/_hidden/_search/vMTlnSWWEvCq/QSaef1BOD0vn
Stack: Error
    at Object.T [as logError] (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:114149)
    at d (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:98101)
    at async Object.resolveNotePath (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:99861)
    at async I.getResolvedNotePath (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:8649)
    at async I.setNote (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:7248)
    at async N.switchToNoteContext (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:14718)
13:03:30.890 JS Error: Cannot resolve note path root/_hidden/_search/vMTlnSWWEvCq/QSaef1BOD0vn
Stack: Error
    at T (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:114149)
    at I.getResolvedNotePath (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:8759)
    at async I.setNote (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:7248)
    at async N.switchToNoteContext (http://t4.vc/assets/v0.61.3-beta/app-dist/desktop.js:2:14718)
13:03:31.320 304 GET /api/search/%23workspace%20%23!template with 31 bytes took 4ms

**Comment by zadam** [comment]
Hello, if you restart the app and search for "QSaef1BOD0vn", does it appear then?

**Comment by sottey** [comment]
Doesn't seem so.

Here is the search result:
![image](https://github.com/zadam/trilium/assets/8494620/e101076a-61cb-4b77-9b28-c667a3a4f77d)


and here is the SQL Console Result:
![image](https://github.com/zadam/trilium/assets/8494620/3dff4a47-a655-444a-ae33-0b7bc0d333ee)

Thanks so much for the quick reply!
Sean

**Comment by sottey** [comment]
Hm, it shows as deleted (there is a deleteid). Strange
