### ISSUE TITLE
(Bug report) The tooltip on the ribbon tab does not disappear

### ISSUE THREAD

**Issue by dvai** [zadam/trilium#4160]
### Trilium Version

0.61.4beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

windows11

### Description

Reproduction steps: 
1. Open a note;
2. Click the "Owned Attributes" button on the ribbon tab；
3. add a label arbitrarily, do not click save, and directly click the other button.

Just like this：
![bandicam-2023-08-11-18-31-53-341](https://github.com/zadam/trilium/assets/33273040/0652cdc0-0b61-4323-a4b2-dc2d467b9bda)

**Comment by dvai** [comment]
I noticed that the console throws an error when editing the attributes, and I'm not sure if it's the reason behind it.

Error logs:
> attribute_editor.js:452  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at ct.getClickIndex (attribute_editor.js:452:50)
    at ct.handleEditorClick (attribute_editor.js:386:37)
    at HTMLDivElement.<anonymous> (attribute_editor.js:347:44)
    at HTMLDivElement.dispatch (jquery.min.js:2:39997)
    at v.handle (jquery.min.js:2:37968)
