### ISSUE TITLE
(Bug report) The action of moving a subtree to another tree has not been handled correctly.

### ISSUE THREAD

**Issue by dvai** [zadam/trilium#4167]
### Trilium Version

0.61.4beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

windows11

### Description

Moving the notes to another tree, after a while, the frontend interface will reload and change the status of the notes to "recovered". I tried to put the recovered notes back in their correct positions, but it was unsuccessful.

I encountered the same problem yesterday as well. When I dragged a subtree to another tree, a similar issue occurred.
![bandicam-2023-08-15-10-43-17-079](https://github.com/zadam/trilium/assets/33273040/748fa150-573f-4e40-9ba5-6a01d5911480)

### Error logs

10:44:04.536 JS Error: No parents found for note _lbToday (Open Today's Journal Note) for path root/_hidden/_lbRoot/_lbVisibleLaunchers/_lbToday
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:114214)
    at d (http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:98166)
    at async Object.resolveNotePath (http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:99926)
    at async I.getResolvedNotePath (http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:8649)
    at async I.setNote (http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:7248)
    at async N.openContextWithNote (http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:15884)
    at async http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:12641
    at async i.allowUpdateWithoutChange (http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:96005)
    at async N.loadTabs (http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:12566)
10:44:04.536 JS Error: Cannot resolve note path root/_hidden/_lbRoot/_lbVisibleLaunchers/_lbToday
Stack: Error
    at T (http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:114214)
    at I.getResolvedNotePath (http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:8759)
    at async I.setNote (http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:7248)
    at async N.openContextWithNote (http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:15884)
    at async http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:12641
    at async i.allowUpdateWithoutChange (http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:96005)
    at async N.loadTabs (http://127.0.0.1:37840/assets/v0.61.4-beta/app-dist/desktop.js:2:12566)
10:44:04.576 200 GET /api/search/%23workspace%20%23!template with 4126 bytes took 7ms
10:44:04.593 200 POST /api/tree/load with 266862 bytes took 4ms
10:44:06.150 200 GET /api/script/startup with 73470 bytes took 6ms
10:44:06.153 200 POST /api/tree/load with 9176 bytes took 0ms
10:44:06.162 200 POST /api/script/exec with 43 bytes took 4ms
10:44:06.164 200 POST /api/tree/load with 5904 bytes took 1ms
10:44:06.167 200 POST /api/tree/load with 6914 bytes took 0ms
10:44:06.198 200 POST /api/script/exec with 641 bytes took 1ms
10:44:06.200 200 POST /api/script/exec with 4799 bytes took 1ms
10:44:07.719 Table counts: notes: 2040, revisions: 3428, attachments: 265, branches: 2508, attributes: 4342, etapi_tokens: 6
10:44:07.798 Consistency issue fixed: Created missing branch 'root__lbToday' for note '_lbToday'
10:44:07.866 Becca (note cache) load took 33ms
10:44:07.866 Sending message to all clients: {"type":"reload-frontend"}
10:44:07.866 All consistency checks passed after some fixes (took 149ms)
10:44:07.868 JS Info: Frontend app reload: received request from backend to reload frontend
10:44:07.873 Generated CSRF token uk7ZeuSa-pG_hN5R7459oCtLp5h1ysUsqNXQ with secret undefined

**Comment by dvai** [comment]
I tried to put the recovered notes back in their correct positions, but it was unsuccessful.
![22 (1)](https://github.com/zadam/trilium/assets/33273040/0ec43396-1b36-4d66-b1c7-2c34f729b103)

I encountered the same problem yesterday as well. When I dragged a subtree to another tree, a similar issue occurred.

**Comment by dvai** [comment]
When I disable synchronization and only use the local client, the above issues will not occur. Perhaps this is a problem caused by synchronization.

**Comment by zadam** [comment]
Hmm, unfortunately I'm not able to reproduce this, even with sync.

**Comment by zadam** [comment]
BTW, I wonder, why do you move this action shortcut to the normal visible tree?

**Comment by dvai** [comment]
> BTW, I wonder, why do you move this action shortcut to the normal visible tree?
This is caused by a bug.

**Comment by zadam** [comment]
So you've been originally moving the shortcut between Available Shortcuts and Visible Shortcuts?

**Comment by dvai** [comment]
Yes, I'm not sure why it appeared in the normal visible tree.

**Comment by zadam** [comment]
Ok, thanks for info. I have to dive into this deeper. It might be related to sync as you pointed out.

**Comment by eliandoran** [comment]
Closing as stale.
