### ISSUE TITLE
[BUG] dateCreated column not in note_contents

### ISSUE THREAD

**Issue by Belphemur** [zadam/trilium#417]
Hello,

This is using the current master with commit https://github.com/zadam/trilium/commit/1d5fb0b64644c3c0dfa2eefc1a3cd8448c7da363

When creating a new date note I'm getting this error:

```
fév 20 09:59:38 dolma trilium[18563]: Trace: ERROR: Error executing query. Inner exception: Error: SQLITE_ERROR: table note_contents has no column named dateCreatedError
fév 20 09:59:38 dolma trilium[18563]:     at wrap (/srv/dev-disk-by-label-Data/syncthing/trilium/src/services/sql.js:137:23)
fév 20 09:59:38 dolma trilium[18563]:     at execute (/srv/dev-disk-by-label-Data/syncthing/trilium/src/services/sql.js:122:26)
fév 20 09:59:38 dolma trilium[18563]:     at insert (/srv/dev-disk-by-label-Data/syncthing/trilium/src/services/sql.js:24:23)
fév 20 09:59:38 dolma trilium[18563]:     at Object.replace (/srv/dev-disk-by-label-Data/syncthing/trilium/src/services/sql.js:30:18)
fév 20 09:59:38 dolma trilium[18563]:     at sql.transactional (/srv/dev-disk-by-label-Data/syncthing/trilium/src/services/repository.js:106:19)
fév 20 09:59:38 dolma trilium[18563]:     at Object.transactional (/srv/dev-disk-by-label-Data/syncthing/trilium/src/services/sql.js:156:22)
fév 20 09:59:38 dolma trilium[18563]:     at Object.updateEntity (/srv/dev-disk-by-label-Data/syncthing/trilium/src/services/repository.js:105:15)
fév 20 09:59:38 dolma trilium[18563]:     at Object.error (/srv/dev-disk-by-label-Data/syncthing/trilium/src/services/log.js:33:13)
fév 20 09:59:38 dolma trilium[18563]:     at wrap (/srv/dev-disk-by-label-Data/syncthing/trilium/src/services/sql.js:143:13)
fév 20 09:59:38 dolma trilium[18563]: Trace: ERROR: Execution of script "Yesterday" (jpwMARal4tGY) failed with error: Load of script note "Yesterday" (jpwMARal4tGY) failed with: Error: SQLITE_ERROR: table note_contents has no column named dateCreated
fév 20 09:59:38 dolma trilium[18563]:     at Object.error (/srv/dev-disk-by-label-Data/syncthing/trilium/src/services/log.js:33:13)
fév 20 09:59:38 dolma trilium[18563]:     at executeBundle (/srv/dev-disk-by-label-Data/syncthing/trilium/src/services/script.js:47:13)

```

**Comment by zadam** [comment]
Hi, it's not really safe to use master revisions. It looks like you migrated your DB before these columns were added and then updated to code which uses them already.

You should be able to fix it by opening SQL console with `ALT-O` and running:

```
ALTER TABLE note_contents  `dateCreated`	TEXT DEFAULT "";
ALTER TABLE note_contents  `dateModified`	TEXT DEFAULT "";
```

**Comment by Belphemur** [comment]
I see, my bad ...

It was on my development instance, trying to see if I can contribute to the project. I miss the change in the migration script.
