### ISSUE TITLE
(Bug report) Current 0.61.5-beta still has excalidraw issues

### ISSUE THREAD

**Issue by deajan** [zadam/trilium#4181]
### Trilium Version

0.61.5-beta

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10 22H2 x64

### Description

I've had trouble with excalidraw in trilium for a while now (see #3979) so I decided to check latest beta version to make sure everything will work well.

Opened a local version of my trilium-data folder made with 0.59, and noticed the following:

- My texts are still missing (it seems they were saved with 0px size according to excalidraw, see https://github.com/excalidraw/excalidraw/issues/6686 )
- When I double click on any object, trilium becomes unresponsive (see error below)

I am really willing to work with trilium (I actually love it, so far it's the best docu tool I found), but my experience with excalidraw issues since I first tried trilium (in v0.56 or so) has always been afwul.
I am willing to recreate (or fix the json) of all my current excalidraw canvas so I can get to use Trilium's canvas features, but even this doesn't work (see my other bug report #4182)

Please, make excalidraw a first class citizen in Trilium ;)

### Error logs

Console output
```
200 GET /api/notes/xsbM6A0a4KJl/blob with 222445 bytes took 6ms
204 PUT /api/options with 0 bytes took 6ms
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/8GUkr3ZGdXGn/qSNvv3Cs3Q0B/xsbM6A0a4KJl?ntxId=jwPD, Line: 63, Column: 23, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at O (<anonymous>:2:728019)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/8GUkr3ZGdXGn/qSNvv3Cs3Q0B/xsbM6A0a4KJl?ntxId=jwPD, Line: 2, Column: 728019, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at O (<anonymous>:2:728019)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/8GUkr3ZGdXGn/qSNvv3Cs3Q0B/xsbM6A0a4KJl?ntxId=jwPD, Line: 2, Column: 728019, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at O (<anonymous>:2:728019)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/8GUkr3ZGdXGn/qSNvv3Cs3Q0B/xsbM6A0a4KJl?ntxId=jwPD, Line: 63, Column: 23, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at <anonymous>:2:726986
    at O (<anonymous>:2:727178)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/8GUkr3ZGdXGn/qSNvv3Cs3Q0B/xsbM6A0a4KJl?ntxId=jwPD, Line: 2, Column: 728019, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at O (<anonymous>:2:728019)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/8GUkr3ZGdXGn/qSNvv3Cs3Q0B/xsbM6A0a4KJl?ntxId=jwPD, Line: 2, Column: 728019, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at O (<anonymous>:2:728019)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/8GUkr3ZGdXGn/qSNvv3Cs3Q0B/xsbM6A0a4KJl?ntxId=jwPD, Line: 2, Column: 728019, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at O (<anonymous>:2:728019)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/8GUkr3ZGdXGn/qSNvv3Cs3Q0B/xsbM6A0a4KJl?ntxId=jwPD, Line: 2, Column: 728019, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at O (<anonymous>:2:728019)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/8GUkr3ZGdXGn/qSNvv3Cs3Q0B/xsbM6A0a4KJl?ntxId=jwPD, Line: 2, Column: 728019, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at O (<anonymous>:2:728019)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/8GUkr3ZGdXGn/qSNvv3Cs3Q0B/xsbM6A0a4KJl?ntxId=jwPD, Line: 2, Column: 728019, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at O (<anonymous>:2:728019)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/8GUkr3ZGdXGn/qSNvv3Cs3Q0B/xsbM6A0a4KJl?ntxId=jwPD, Line: 2, Column: 728019, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at O (<anonymous>:2:728019)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/8GUkr3ZGdXGn/qSNvv3Cs3Q0B/xsbM6A0a4KJl?ntxId=jwPD, Line: 2, Column: 728019, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at O (<anonymous>:2:728019)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
sync failed: Could not setup sync since local sync protocol version is 31 while remote is 29. To fix this issue, use same Trilium version on all instances.
stack: Error: Could not setup sync since local sync protocol version is 31 while remote is 29. To fix this issue, use same Trilium version on all instances.
    at Object.hasSyncServerSchemaAndSeed (C:\Users\Orsiris\Desktop\trilium-windows-x64\resources\app.asar\src\services\setup.js:15:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async login (C:\Users\Orsiris\Desktop\trilium-windows-x64\resources\app.asar\src\services\sync.js:90:10)
    at async C:\Users\Orsiris\Desktop\trilium-windows-x64\resources\app.asar\src\services\sync.js:35:37
    at async Object.doExclusively (C:\Users\Orsiris\Desktop\trilium-windows-x64\resources\app.asar\src\services\sync_mutex.js:13:16)
    at async sync (C:\Users\Orsiris\Desktop\trilium-windows-x64\resources\app.asar\src\services\sync.js:27:16)
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/8GUkr3ZGdXGn/qSNvv3Cs3Q0B/xsbM6A0a4KJl?ntxId=jwPD, Line: 79, Column: 227, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at Gi (<anonymous>:171:413)
    at Aa (<anonymous>:171:382)
    at Gi (<anonymous>:171:494)
    at Aa (<anonymous>:171:382)
    at Gi (<anonymous>:171:494)
    at Aa (<anonymous>:171:382)
    at Gi (<anonymous>:172:188)
    at Aa (<anonymous>:171:382)
    at Gi (<anonymous>:172:188)
    at Aa (<anonymous>:171:382)
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/8GUkr3ZGdXGn/qSNvv3Cs3Q0B/xsbM6A0a4KJl?ntxId=jwPD, Line: 2, Column: 728019, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at O (<anonymous>:2:728019)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
    at <anonymous>:2:732982
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
```

**Comment by deajan** [comment]
I've exported a drawing from 0.59.4 and imported it into a fresh 0.61.5-beta version of Trilium.

Canvas in v0.59.4
![image](https://github.com/zadam/trilium/assets/4681318/5c833d24-86e2-46cb-9b11-100e1612f028)
![image](https://github.com/zadam/trilium/assets/4681318/27d22a31-bb62-4cd2-889b-f0745d03ecf1)

Canvas in v0.61.5-beta
![image](https://github.com/zadam/trilium/assets/4681318/c0b37194-9386-465f-86ec-5d064be07fde)
![image](https://github.com/zadam/trilium/assets/4681318/7d20f022-b894-4866-8632-892c07ad618f)

The fun part is that the text appears in the small rendered images (maybe because of the SVG that comes with the export ?)
![image](https://github.com/zadam/trilium/assets/4681318/ef234194-f8c4-41f5-a6bf-825ff320b98a)

Trying to edit one of the shapes that should have text gives the following errors:
```
Slow 200 POST /api/notes/root/notes-import with 358 bytes took 23ms
Sending message to all clients: {"type":"taskSucceeded","taskId":"2c2XfHk5dj","taskType":"importNotes","data":{"safeImport":true,"shrinkImages":true,"textImportedAsText":true,"codeImportedAsCode":true,"explodeArchives":true,"replaceUnderscoresWithSpaces":true},"result":{"parentNoteId":"root","importedNoteId":"mPI4uboGa6jB"}}
200 POST /api/tree/load with 754 bytes took 1ms
200 GET /api/note-map/mPI4uboGa6jB/backlink-count with 11 bytes took 1ms
200 GET /api/notes/mPI4uboGa6jB/blob with 115201 bytes took 2ms
200 GET /api/tree?subTreeNoteId=root with 14970 bytes took 1ms
204 PUT /api/options with 0 bytes took 2ms
Slow 204 PUT /api/notes/mPI4uboGa6jB/data with 0 bytes took 11ms
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/mPI4uboGa6jB?ntxId=3HkzvI, Line: 63, Column: 23, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at hc (<anonymous>:37:210)
    at Vc (<anonymous>:38:386)
    at ia (<anonymous>:184:69)
    at ya (<anonymous>:183:466)
    at Object.enqueueSetState (<anonymous>:238:360)
    at w.setState (<anonymous>:19:14)
    at Ur.onSceneUpdated (<anonymous>:2:433749)
    at e.value (<anonymous>:2:794782)
    at f (<anonymous>:2:701006)
    at O (<anonymous>:2:728381)
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
JS Error: Uncaught error: Message: Uncaught RangeError: Maximum call stack size exceeded, URL: http://127.0.0.1:37840/#root/mPI4uboGa6jB?ntxId=3HkzvI, Line: 79, Column: 227, Error object: {}, Stack: RangeError: Maximum call stack size exceeded
    at Gi (<anonymous>:171:413)
    at Aa (<anonymous>:171:382)
    at Gi (<anonymous>:171:494)
    at Aa (<anonymous>:171:382)
    at Gi (<anonymous>:171:494)
    at Aa (<anonymous>:171:382)
    at Gi (<anonymous>:172:188)
    at Aa (<anonymous>:171:382)
    at Gi (<anonymous>:172:188)
    at Aa (<anonymous>:171:382)
Stack: Error
    at Object.T [as logError] (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:114214)
    at Ri.window.onerror (http://127.0.0.1:37840/assets/v0.61.5-beta/app-dist/desktop.js:2:654402)
Slow 204 PUT /api/notes/mPI4uboGa6jB/data with 0 bytes took 10ms
```

I've also tried to create new alike schemas with 0.61.5-beta, export them, import them again, and check if they can be modified, seems like this works properly.

My question is, should I just "abandon" my elder canvas, or is there some way to get them to work with newer trilium version perhaps ?
I've attached two (of about 20) canvas exported via trilium 0.59-4.
[Cluster applicatif BDD (MySQL) (1).zip](https://github.com/zadam/trilium/files/12394961/Cluster.applicatif.BDD.MySQL.1.zip)
[Cluster applicatif BDD Arbiter.zip](https://github.com/zadam/trilium/files/12394962/Cluster.applicatif.BDD.Arbiter.zip)

**Comment by zadam** [comment]
Honestly I don't know what to do with this. IIRC this issue comes from the excalidraw and I won't be able to fix issues in excalidraw itself.

**Comment by deajan** [comment]
Fair enough. I'll close my trilium/excalidraw issues since they probably involve malformatted json canvas from earlier excalidraw versions I guess.

I am able to recover my current drawings by:
1. Exporting the note via Trilium
2. Unzip the file and edit the JSON
2.1. Replace header from
```
    "_meta": "This note has type `canvas`. It uses excalidraw and stores an exported svg alongside.",
```
to
```
    "type": "excalidraw",
    "version": 2,
    "source": "https://excalidraw.com",
```

2.2. Replace `appstate` from whatever to this clean state
```
    "appState": {
        "gridSize": null,
        "viewBackgroundColor": "#ffffff"
    },
```

2.3. Remove `svg` entry in json (and make sure to remove the comma after `files` entry)
3. Import json file into excalidraw.com, export it as `somename.excalidraw`
4.  Import it using excalidraw/open in Trilium

Maybe this should be documented somewhere, since I guess there might be a couple of people using canvas since 0.5x days that could be impacted.
