### ISSUE TITLE
(Bug report) Sync failed: Request to PUT {uri} failed, error: 500 Internal Server Error

### ISSUE THREAD

**Issue by hzxsw** [zadam/trilium#4231]
### Trilium Version

0.61.5-beta

### What operating system are you using?

macOS

### What is your setup?

Local + server sync

### Operating System Version

MacOS Ventura

### Description

After a day or two of synchronizing the configuration server, it will permanently fail to synchronize. The solution is to delete all the data on the server, reconfigure the synchronization, and import the data. However, this solution can only temporarily maintain for a day or two before the same problem occurs again. I'm not sure if this problem is with the MACOS client or the LINUX server. Thank you very much for solving this problem.

error:
![image](https://github.com/zadam/trilium/assets/141128095/10f78597-f1ae-48b3-971d-22cedc8695d1)

nginx log:
`
IP - - [03/Sep/2023:03:22:59 +0800] "PUT /api/sync/update?logMarkerId=uLmI1VMHb5 HTTP/1.1" 500 56 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TriliumNotes/0.61.5-beta Chrome/114.0.5735.289 Electron/25.5.0 Safari/537.36" "-" request_body:"-"
`

trilium error log:
`
ERROR: put /api/sync/update threw exception: 'Cannot convert undefined or null to object', stack: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at insert (/usr/src/app/src/services/sql.js:29:25)
    at Object.replace (/usr/src/app/src/services/sql.js:52:12)
    at updateNormalEntity (/usr/src/app/src/services/sync_update.js:63:13)
    at Object.updateEntity (/usr/src/app/src/services/sync_update.js:14:11)
    at Function.<anonymous> (/usr/src/app/src/routes/api/sync.js:171:31)
    at Function.sqliteTransaction (/usr/src/app/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at Object.transactional (/usr/src/app/src/services/sql.js:242:52)
    at update (/usr/src/app/src/routes/api/sync.js:169:9)
    at Function.cb (/usr/src/app/src/routes/routes.js:439:34)
`
![image](https://github.com/zadam/trilium/assets/141128095/9e269ccd-a585-4f03-bc50-44ec235426f3)

**Comment by dvai** [comment]
I encountered the same problem. Have you ever edited the code notes? I speculate that it could be caused by this issue(#4176 )

**Comment by zadam** [comment]
Hello, sorry for the trouble. Unstable sync protocol is the main reason why 0.61 remains in beta.

I implemented fixes to the sync which fixes this problem and few others. I will release another beta likely today.

**Comment by eliandoran** [comment]
Should have been fixed at some point, according to @zadam .
