### ISSUE TITLE
(Bug report) Seeing forced front end reloads

### ISSUE THREAD

**Issue by sottey** [zadam/trilium#4241]
### Trilium Version

0.61.6-beta

### What operating system are you using?

Ubuntu

### What is your setup?

Server access only

### Operating System Version

Ubuntu 20

### Description

While editing a note (any note), I eventually have everything reload and I am put back at the top of the page.

Backend log shows:
23:05:53.109 JS Error: Encountered error Process exceeded time limit 30000: Error: Process exceeded time limit 30000
    at Object.timeLimit (https://t4.vc/assets/v0.61.6-beta/app-dist/desktop.js:2:105536)
    at https://t4.vc/assets/v0.61.6-beta/app-dist/desktop.js:2:115797
    at https://t4.vc/assets/v0.61.6-beta/app-dist/desktop.js:2:116512
    at WebSocket.A (https://t4.vc/assets/v0.61.6-beta/app-dist/desktop.js:2:116540), reloading frontend.
Stack: Error
    at T (https://t4.vc/assets/v0.61.6-beta/app-dist/desktop.js:2:114906)
    at https://t4.vc/assets/v0.61.6-beta/app-dist/desktop.js:2:115847

Console logs are empty.

**Comment by sottey** [comment]
Note: I have moved back to 60.4. the stable works fine. I wonder if there is some websocket config that changed that I need to configure?

Thanks!

**Comment by zadam** [comment]
Hmm, this happens when there's some error and the safe way to recover from it is to reload. Is there perhaps something interesting in the backend log?

**Comment by eliandoran** [comment]
Closing as stale.
