### ISSUE TITLE
(Bug report) Error in migration from 0.60.4 to 0.61.6-beta

### ISSUE THREAD

**Issue by Nriver** [zadam/trilium#4262]
### Trilium Version

0.61.6-beta

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

Windows 10

### Description

I tried to upgrade from 0.60.4 to 0.61.6-beta and get error in database migration. I've sent an anonymized db to your email. That should help you to reproduce the error.

### Error logs

The error part:

```
Migration to version 215 has been successful.
Attempting migration to version 216
Migration with JS module
ERROR: error during migration to version 216: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received null
   at new NodeError (node:internal/errors:399:5)
   at Hash.update (node:internal/crypto/hash:109:11)
   at Object.hashedBlobId (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\src\services\utils.js:29:52)
   at module.exports (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\db\migrations\0216__move_content_into_blobs.js:9:30)
   at executeMigration (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\src\services\migration.js:91:9)
   at Function.<anonymous> (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\src\services\migration.js:59:17)
   at Function.sqliteTransaction (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\node_modules\better-sqlite3\lib\methods\transaction.js:65:24)
   at Object.transactional (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\src\services\sql.js:242:52)
   at migrate (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\src\services\migration.js:54:9)
   at async Object.migrateIfNecessary (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\src\services\migration.js:123:9)
ERROR: migration failed, crashing hard
The database connection is not open
TypeError: The database connection is not open
   at Function.sqliteTransaction (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\node_modules\better-sqlite3\lib\methods\transaction.js:66:9)
   at Object.transactional (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\src\services\sql.js:242:52)
   at migrate (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\src\services\migration.js:54:9)
   at async Object.migrateIfNecessary (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\src\services\migration.js:123:9)
   at async initDbConnection (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\src\services\sql_init.js:41:5)
TypeError: The database connection is not open
   at Function.sqliteTransaction (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\node_modules\better-sqlite3\lib\methods\transaction.js:66:9)
   at Object.transactional (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\src\services\sql.js:242:52)
   at migrate (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\src\services\migration.js:54:9)
   at async Object.migrateIfNecessary (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\src\services\migration.js:123:9)
   at async initDbConnection (Y:\trilium-windows-x64-0.61.6-beta\trilium-windows-x64\resources\app.asar\src\services\sql_init.js:41:5)
```

**Comment by zadam** [comment]
Thanks for the DB, it was easy to reproduce! I will release a fixed build soon.

**Comment by Nriver** [comment]
Thank you
