### ISSUE TITLE
(Bug report) Sync stopped after sharing a note

### ISSUE THREAD

**Issue by deajan** [zadam/trilium#4297]
### Trilium Version

0.61.7-beta & 0.61.8-beta

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

Windows 11 22H2 - Almalinux 9.2

### Description

Nothing more to say, my trilium was in sync.
Create a share with an alias.

Sync stopped working:
![image](https://github.com/zadam/trilium/assets/4681318/a336a062-aaba-40e0-bd4f-37477cbcb144)

Cannot sync anymore, or even unshare.
CTRL+R fixed the sync, but there's something probably in cache where I created the share before the sync operation was done ?
If I happen to reshare the note, it says shared, but "404 not found on server".

### Error logs

11:38:55.245 Sending message to all clients: {"type":"sync-pull-in-progress","lastSyncedPush":8885}
11:38:55.544 Sync failed: 'Entity branches '_share_MnecBjHnw0gf' not found.', stack: Error: Entity branches '_share_MnecBjHnw0gf' not found.
    at getEntityChangeRow (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:304:19)
    at getEntityChangeRecords (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:330:24)
    at pushChanges (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:196:38)
    at C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:37:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.doExclusively (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync_mutex.js:13:16)
    at async Object.sync (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:27:16)
11:38:55.545 Slow 200 POST /api/sync/now with 78 bytes took 300ms
11:38:59.608 200 GET /api/notes/NvGbOBXAu1oL/blob with 155 bytes took 1ms
11:39:01.667 Sync failed: 'Entity branches '_share_MnecBjHnw0gf' not found.', stack: Error: Entity branches '_share_MnecBjHnw0gf' not found.
    at getEntityChangeRow (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:304:19)
    at getEntityChangeRecords (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:330:24)
    at pushChanges (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:196:38)
    at C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:37:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.doExclusively (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync_mutex.js:13:16)
    at async sync (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:27:16)
11:39:08.751 200 GET /api/notes/f7zxcCBe1vSo/blob with 2512 bytes took 1ms
11:39:42.208 200 GET /api/notes/NvGbOBXAu1oL/blob with 155 bytes took 1ms
11:39:45.199 200 POST /api/search-related with 1051 bytes took 3ms
11:39:45.202 200 POST /api/tree/load with 9195 bytes took 0ms
11:39:46.676 204 PUT /api/notes/MnecBjHnw0gf/attributes with 0 bytes took 2ms
11:39:48.409 Received request to trigger sync now.
11:39:48.409 Sending message to all clients: {"type":"sync-pull-in-progress","lastSyncedPush":8885}
11:39:48.699 Sync failed: 'Entity branches '_share_MnecBjHnw0gf' not found.', stack: Error: Entity branches '_share_MnecBjHnw0gf' not found.
    at getEntityChangeRow (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:304:19)
    at getEntityChangeRecords (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:330:24)
    at pushChanges (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:196:38)
    at C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:37:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.doExclusively (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync_mutex.js:13:16)
    at async Object.sync (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:27:16)
11:39:48.699 Slow 200 POST /api/sync/now with 78 bytes took 290ms
11:40:01.687 Sync failed: 'Entity branches '_share_MnecBjHnw0gf' not found.', stack: Error: Entity branches '_share_MnecBjHnw0gf' not found.
    at getEntityChangeRow (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:304:19)
    at getEntityChangeRecords (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:330:24)
    at pushChanges (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:196:38)
    at C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:37:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.doExclusively (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync_mutex.js:13:16)
    at async sync (C:\Users\USer\Documents\trilium-windows-x64-0.61.7-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:27:16)

**Comment by deajan** [comment]
Seems this happens if I add a `#shareAlias=abc` locally before sharing.
I can share parent note without problem.
Need anonymized DB ?

**Comment by deajan** [comment]
Actually happens too without the sharealias property.
![image](https://github.com/zadam/trilium/assets/4681318/9e4cd543-7eaf-4950-ba1a-7e17dad5d55d)

**Comment by deajan** [comment]
I've moved the current trilium-data to and resynced a new one.
I can share some items, other make the same error, so I guess there's something wrong in my database.
Both integrity checks and fix inconsistency say everything is okay.

**Comment by deajan** [comment]
Updated both client and server to 0.61.8-beta, same results.

The server doesn't show any error.
The client (fresh install and sync from scratch) will not sync anymore when I tried to share certain notes.
I only can imagine a DB inconsistency at this stage.

```
204 PUT /api/notes/MnecBjHnw0gf/attributes with 0 bytes took 2ms
Marking branches _share_MnecBjHnw0gf as deleted
200 DELETE /api/branches/_share_MnecBjHnw0gf?taskId=no-progress-reporting with 21 bytes took 2ms
Received request to trigger sync now.
Sending message to all clients: {"type":"sync-pull-in-progress","lastSyncedPush":7543}
Sync failed: 'Entity branches '_share_MnecBjHnw0gf' not found.', stack: Error: Entity branches '_share_MnecBjHnw0gf' not found.
    at getEntityChangeRow (C:\Users\USer\Documents\trilium-windows-x64-0.61.8-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:304:19)
    at getEntityChangeRecords (C:\Users\USer\Documents\trilium-windows-x64-0.61.8-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:330:24)
    at pushChanges (C:\Users\USer\Documents\trilium-windows-x64-0.61.8-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:196:38)
    at C:\Users\USer\Documents\trilium-windows-x64-0.61.8-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:37:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.doExclusively (C:\Users\USer\Documents\trilium-windows-x64-0.61.8-beta\trilium-windows-x64\resources\app.asar\src\services\sync_mutex.js:13:16)
    at async Object.sync (C:\Users\USer\Documents\trilium-windows-x64-0.61.8-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:27:16)
Slow 200 POST /api/sync/now with 78 bytes took 52ms
200 GET /api/notes/NvGbOBXAu1oL/blob with 155 bytes took 1ms
Sync failed: 'Entity branches '_share_MnecBjHnw0gf' not found.', stack: Error: Entity branches '_share_MnecBjHnw0gf' not found.
    at getEntityChangeRow (C:\Users\USer\Documents\trilium-windows-x64-0.61.8-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:304:19)
    at getEntityChangeRecords (C:\Users\USer\Documents\trilium-windows-x64-0.61.8-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:330:24)
    at pushChanges (C:\Users\USer\Documents\trilium-windows-x64-0.61.8-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:196:38)
    at C:\Users\USer\Documents\trilium-windows-x64-0.61.8-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:37:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.doExclusively (C:\Users\USer\Documents\trilium-windows-x64-0.61.8-beta\trilium-windows-x64\resources\app.asar\src\services\sync_mutex.js:13:16)
    at async sync (C:\Users\USer\Documents\trilium-windows-x64-0.61.8-beta\trilium-windows-x64\resources\app.asar\src\services\sync.js:27:16)
```

**Comment by zadam** [comment]
@deajan if you can please send me the anonymised DB to zadam.apps@gmail.com, that would be very useful for me. Sync bugs are the top priority for me now.

**Comment by zadam** [comment]
In [https://github.com/zadam/trilium/issues/4288#issuecomment-1741869107](https://github.com/zadam/trilium/issues/4288#issuecomment-1741869107) you mention that it's likely caused by corrupt database. What kind of corruption you mean? Like low level database-level corruption or a logical (trilium) one?

**Comment by deajan** [comment]
@zadam You have the anonymized db in #4288
My systems seem okay, I didn't have any power outages or else, so I guess it's a logical database issue.

I am willing to demonstrate the issue via remote screen or so if needed.

**Comment by deajan** [comment]
@zadam: Anything I can add to help ? I can reproduce this error easily with a fresh local trilium 0.61.8-beta that I sync from my server.

**Comment by zadam** [comment]
@deajan I'm not able to reproduce the behavior with the supplied database and I think it's because it's just one side of the sync process. Could you please provide both client and server anonymized database to zadam.apps@gmail.com? This would be greatly appreciated!

**Comment by deajan** [comment]
@zadam I've sent you both server and client side anonymized DBs.
Try to share / unshare note and this happened: `Sync failed: Entity branches '_share_MnecBjHnw0gf' not found.`
Once I get this error, I am unable to sync.
Tried with 0.61-9.beta too.

**Comment by zadam** [comment]
@deajan thanks for the files, I'm able to reproduce the issue and I'm working on a fix!

**Comment by deajan** [comment]
Great ! Ping me if you need me to test a potentiel fix.

**Comment by deajan** [comment]
Tried 0.61.10-beta today, looks like the problem is resvoled ;)
Thank you.
