### ISSUE TITLE
(Bug report) Logged in session not found

### ISSUE THREAD

**Issue by eliandoran** [zadam/trilium#4399]
### Trilium Version

v0.61.12

### What operating system are you using?

Linux

### What is your setup?

Local (no sync)

### Operating System Version

NixOS 23.05

### Description

1. Have server & client v0.61.
2. Update server to v0.62.
3. Update client to v0.62.
4. Try to do a sync on the client.

### Error logs

Log on client:

```
Sync failed: 'Request to PUT http://notes.eliandoran.me/api/sync/update?logMarkerId=yuPjpt7ZOH failed, error: 401  Logged in session not found', stack: Error: Request to PUT http://notes.eliandoran.me/api/sync/update?logMarkerId=yuPjpt7ZOH failed, error: 401  Logged in session not found
    at generateError (/nix/store/7lpdrh5xgf7vr15yjwiwf550rw5s2axz-trilium-desktop-0.61.12/share/trilium/resources/app.asar/src/services/request.js:200:12)
    at IncomingMessage.<anonymous> (/nix/store/7lpdrh5xgf7vr15yjwiwf550rw5s2axz-trilium-desktop-0.61.12/share/trilium/resources/app.asar/src/services/request.js:91:32)
    at IncomingMessage.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Log on server:

```
Nov 06 16:54:42 nixos trilium-server[3101405]: PUT /api/sync/update rejected with 401 Logged in session not found
```

**Comment by rauenzi** [comment]
Sounds like #1956 from a brief glance

**Comment by eliandoran** [comment]
The issue was caused by having the wrong sync configuration in the client (Electron), more specifically I had used the `http` protocol instead of `https`.

To note that it did use to work in the past versions since I had this configuration on multiple devices, maybe something got changed with the Trilium dependencies updated.

**Comment by rauenzi** [comment]
Node (via the Electron upgrade) was updated to v18 which contained a lot of under-the-cover networking changes including what you describe I believe.
