### ISSUE TITLE
(Bug report) An uneditable sample suddenly appeared while editing content

### ISSUE THREAD

**Issue by Joackk** [zadam/trilium#4444]
### Trilium Version

0.62.1

### What operating system are you using?

Windows

### What is your setup?

Local (no sync)

### Operating System Version

wind10

### Description

I was editing my notes when I suddenly got stuck, and my interface magically added a copy of the content I just edited, but it is not editable
![bec374b8-fa70-4acb-b007-888ac3c0fef4](https://github.com/zadam/trilium/assets/45162558/f73a7213-74d6-4094-90f1-5bc6974e15ce)

He looks like this in the review element
![image](https://github.com/zadam/trilium/assets/45162558/1cdbc2f9-8606-4c22-a64b-82a46fa68fb1)

### Error logs

`SyntaxHighlightWidget:  Creating SyntaxHighlightWidget debugLevel:2
bundle.js:47 Custom widget does not have mandatory 'parentWidget' property defined
2VM1071:57 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'editing')
    at getNoteContainer (eval at <anonymous> (bundle.js:21:20), <anonymous>:57:45)
    at async eval (eval at <anonymous> (bundle.js:21:20), <anonymous>:60:44)
 banner notification 启动通知
VM1069:6 image-style-configuration-definition-invalid Object 
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-image-style-configuration-definition-invalid
k @ VM1069:6
jquery.min.js:2 A soft navigation has been detected: http://127.0.0.1:37840/#root/zcsaZfUJ7yAf/Jdn8S85qmPdJ/owwGyRi5KU88?ntxId=Nq8Wo0
ws.js:18 16:40:22 Uncaught error: Message: ResizeObserver loop limit exceeded, URL: http://127.0.0.1:37840/#root/fEWAVWF59Vir/ytdBNpLGeqbi/HNH8sctBAYqV?ntxId=Nq8Wo0, Line: 0, Column: 0, Error object: null, Stack: null
T @ ws.js:18
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/assets/v0.62.1-beta/libraries/bootstrap/js/bootstrap.bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/assets/v0.62.1-beta/libraries/fancytree/jquery.fancytree-all-deps.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/assets/v0.62.1-beta/libraries/split.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/libraries/ckeditor/ckeditor.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://127.0.0.1:37840/assets/v0.62.1-beta/libraries/bootstrap/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
ws.js:221 16:44:57 Lost websocket connection to the backend. If you keep having this issue repeatedly, you might want to check your reverse proxy (nginx, apache) configuration and allow/unblock WebSocket.
ws.js:221 16:45:34 Lost websocket connection to the backend. If you keep having this issue repeatedly, you might want to check your reverse proxy (nginx, apache) configuration and allow/unblock WebSocket.`

**Comment by zadam** [comment]
Unfortunately likely a bug in CKEditor. There seems to be some trouble with Chinese input specifically. The workaround is to reload with CTRL-R.

**Comment by Joackk** [comment]
@zadam That is, is this the mistake CKEditor made when editing Chinese again? Refreshing or switching the page can bring it back to normal.
