### ISSUE TITLE
Error GLIBC_2.29

### ISSUE THREAD

**Issue by 531536942** [zadam/trilium#4527]
### Trilium Version

0.62.4

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Linux 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Description

My system:
Linux 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Error logs

Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/trilium-linux-x64-server/node_modules/better-sqlite3/build/Release/better_sqlite3.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at bindings (/usr/local/trilium-linux-x64-server/node_modules/bindings/bindings.js:112:48)
    at new Database (/usr/local/trilium-linux-x64-server/node_modules/better-sqlite3/lib/database.js:48:64)
    at Object.<anonymous> (/usr/local/trilium-linux-x64-server/src/services/sql.js:13:22)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by Nriver** [comment]
You are using an outdated version of the Linux operating system. I strongly advise transitioning to a more contemporary Linux distribution.

Alternatively, if you choose to stick with your current system, upgrading the GNU C Library (glibc) is necessary. However, be aware that such an upgrade carries a significant risk of system instability and potential breakage.

**Comment by 531536942** [comment]
您好，邮件已收到，我查阅后会尽快回复您。

**Comment by 531536942** [comment]
您好，邮件已收到，我查阅后会尽快回复您。
