### ISSUE TITLE
(Bug report) Unable to load KaTeX correctly on the sharing page.

### ISSUE THREAD

**Issue by harveyTon** [zadam/trilium#4558]
### Trilium Version

0.62.4

### What operating system are you using?

Other Linux

### What is your setup?

Server access only

### Operating System Version

Ubuntu 22.04.3 LTS (Jammy Jellyfish) x86_64

## Share Page HTML Code
```HTML
<script src="../../assets/v0.62.4/libraries/katex/katex.min.js"></script> 
<link rel="stylesheet" href="../../assets/v0.62.4/libraries/katex/katex.min.css"> 
<script src="../../assets/v0.62.4/libraries/katex/auto-render.min.js"></script> 
<script src="../../assets/v0.62.4/libraries/katex/mhchem.min.js"></script> 
<script> 
document.addEventListener("DOMContentLoaded", function() { 
    renderMathInElement(document.getElementById('content')); 
});
 </script>
```

### Error logs

```
Error: Router not found for request GET /assets/v0.62.4/libraries/katex/auto-render.min.js
    at /app/src/routes/error_handlers.js:18:21
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12) {
  status: 404
}
Error: Router not found for request GET /assets/v0.62.4/libraries/katex/katex.min.css
    at /app/src/routes/error_handlers.js:18:21
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12) {
  status: 404
}
Error: Router not found for request GET /assets/v0.62.4/libraries/katex/katex.min.css
    at /app/src/routes/error_handlers.js:18:21
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
    at /app/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12) {
  status: 404
}
```

**Comment by zadam** [comment]
Hello, thanks for reporting, will be fixed in the next patch release.
