### ISSUE TITLE
(Bug report) TRILIUM_DATA_DIR doesn't work if subdirectory doesn't exist

### ISSUE THREAD

**Issue by Dialga** [zadam/trilium#4580]
### Trilium Version

latest

### What operating system are you using?

Other Linux

### What is your setup?

Local (no sync)

### Operating System Version

Arch Linux

### Description

```
$ env TRILIUM_DATA_DIR='/home/me/new folder/new new folder' trilium
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, mkdir '/home/me/new folder/new new folder'
    at Object.mkdirSync (node:fs:1396:3)
    at getTriliumDataDir (/opt/trilium-bin/resources/app.asar/src/services/data_dir.js:41:16)
    at Object.<anonymous> (/opt/trilium-bin/resources/app.asar/src/services/data_dir.js:62:26)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
```
TRILIUM_DATA_DIR doesn't work if the subfolder doesn't exist.

**Comment by Nriver** [comment]
If you manually specify the path, you should make sure it exists and writable.

**Comment by zadam** [comment]
I think it's better this way. Trilium creating the directory itself could mean it accepts e.g. paths with typos which could have unintended consequences.
