### ISSUE TITLE
Sqlite3?what's wrong whit it?

### ISSUE THREAD

**Issue by ffywhxf** [zadam/trilium#461]
![sp20190324_213349_206](https://user-images.githubusercontent.com/48848717/54880144-b9b3f280-4e7c-11e9-9af0-ba8f8dbcbc9d.png)

**Comment by zadam** [comment]
Looks like you upgraded to electron 4.1 for some reason, that's not supported.

**Comment by MrEliptik** [comment]
I also have a problem with sqlite3.

```
node src/www
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/home/mreliptik/trilium/node_modules/sqlite3/lib/binding/node-v64-linux-arm64/node_sqlite3.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/mreliptik/trilium/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```
When trying to install it (even though I've already ran `npm install` in the trilium directory:
```
npm install sqlite3
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mreliptik/.npm/_logs/2019-03-30T07_50_42_495Z-debug.log
```
I've looked online for a long time and it seems to be because of the node or npm version.. What version of both is recommended? I've tried many and it's still not working. Currently using 

- node v10.4.1
- npm v6.1.0

**Comment by zadam** [comment]
node 10 versions older than 10.5 are pretty buggy - so first thing I'd try would be upgrading to latest version

**Comment by MrEliptik** [comment]
Oh yes ok, I read that wrong when choosing a node version. As it's very slow on my small arm server to compile node, I wont try again. I moved to an x86 machine and used the binaries provided. Thanks for the response anyway.
