### ISSUE TITLE
0.31.0-beta issue - client won't start

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#475]
I am running the 30.1 beta on windows.  I launch the app and I can see it in task manager but it never gives me a desktop window.  One thing is that I don't have a connection to the server that I sync to.

**Comment by pcause** [comment]
updated the server to 30.1 beta and have a connection before i start the client.  it now starts.  however i get a sync error:

Sync failed: Request to GET http://127.0.0.1:9999//api/sync/cha

I am using an ssh tunnel to connect to the server.  i can access the server with no problems from a web browser.  also i added 2 notes and sync'ed, got the error, but the notes are synced and i can see them via the browser accessing the server.  both windows desktop and server at 30.1 beta

**Comment by zadam** [comment]
Do you mean 0.30.1-beta? That's very old and if I remember correctly quite buggy. It would be the best to upgrade to latest 0.30.7

**Comment by pcause** [comment]
sorry, corrected the title.  I meant the latest beta 31.0.  sorry for the confusion

**Comment by zadam** [comment]
Oh, I see. Does the error persist? Since based on what you're saying the apps managed to sync the content after all ... 

Could you post more logs around the error?

**Comment by pcause** [comment]
There is the app version info first then I  get these 2 error messages:

08:13:11.055 INFO  ERROR: Error executing query. Inner exception: TypeError: Cannot read property 'all' of undefined
    at wrap (C:\tools\trilium-windows-x64\resources\app.asar\src\services\sql.js:109:38)
    at wrap (C:\tools\trilium-windows-x64\resources\app.asar\src\services\sql.js:163:22)
    at Object.getRows (C:\tools\trilium-windows-x64\resources\app.asar\src\services\sql.js:109:18)
    at Object.schemaExists (C:\tools\trilium-windows-x64\resources\app.asar\src\services\sql_init.js:29:36)
    at createMainWindow (C:\tools\trilium-windows-x64\resources\app.asar\electron.js:35:23)
    at App.app.on (C:\tools\trilium-windows-x64\resources\app.asar\electron.js:95:24)
    at App.emit (events.js:187:15)Error
    at wrap (C:\tools\trilium-windows-x64\resources\app.asar\src\services\sql.js:160:23)
    at Object.getRows (C:\tools\trilium-windows-x64\resources\app.asar\src\services\sql.js:109:18)
    at Object.schemaExists (C:\tools\trilium-windows-x64\resources\app.asar\src\services\sql_init.js:29:36)
    at createMainWindow (C:\tools\trilium-windows-x64\resources\app.asar\electron.js:35:23)
    at App.app.on (C:\tools\trilium-windows-x64\resources\app.asar\electron.js:95:24)
    at App.emit (events.js:187:15)
08:13:11.059 INFO  TypeError: Cannot read property 'all' of undefined
    at wrap (C:\tools\trilium-windows-x64\resources\app.asar\src\services\sql.js:109:38)
    at wrap (C:\tools\trilium-windows-x64\resources\app.asar\src\services\sql.js:163:22)
    at Object.getRows (C:\tools\trilium-windows-x64\resources\app.asar\src\services\sql.js:109:18)
    at Object.schemaExists (C:\tools\trilium-windows-x64\resources\app.asar\src\services\sql_init.js:29:36)
    at createMainWindow (C:\tools\trilium-windows-x64\resources\app.asar\electron.js:35:23)
    at App.app.on (C:\tools\trilium-windows-x64\resources\app.asar\electron.js:95:24)
    at App.emit (events.js:187:15)
{"message":"TypeError: Cannot read property 'all' of undefined\n    at wrap (C:\\tools\\trilium-windows-x64\\resources\\app.asar\\src\\services\\sql.js:109:38)\n    at wrap (C:\\tools\\trilium-windows-x64\\resources\\app.asar\\src\\services\\sql.js:163:22)\n    at Object.getRows (C:\\tools\\trilium-windows-x64\\resources\\app.asar\\src\\services\\sql.js:109:18)\n    at Object.schemaExists (C:\\tools\\trilium-windows-x64\\resources\\app.asar\\src\\services\\sql_init.js:29:36)\n    at createMainWindow (C:\\tools\\trilium-windows-x64\\resources\\app.asar\\electron.js:35:23)\n    at App.app.on (C:\\tools\\trilium-windows-x64\\resources\\app.asar\\electron.js:95:24)\n    at App.emit (events.js:187:15)"}
Error
    at wrap (C:\tools\trilium-windows-x64\resources\app.asar\src\services\sql.js:160:23)
    at Object.getRows (C:\tools\trilium-windows-x64\resources\app.asar\src\services\sql.js:109:18)
    at Object.schemaExists (C:\tools\trilium-windows-x64\resources\app.asar\src\services\sql_init.js:29:36)
    at createMainWindow (C:\tools\trilium-windows-x64\resources\app.asar\electron.js:35:23)
    at App.app.on (C:\tools\trilium-windows-x64\resources\app.asar\electron.js:95:24)
    at App.emit (events.js:187:15)

This is followed by a message that the DB is at 126 and needs to migrate to 131 and then a bunch of migrate messages.   A couple of DB ready messages and then a size message and messages about making a backup.  After that there are just messages about "No connection to the server" repeated over and over for the next 30 minutes.  So, my original speculation that it was just spinning becuase it couldn't get to the server (I wasn't connected) appears to be correct.

**Comment by pcause** [comment]
for the sync errors, I started the client and it had 1 item to sync.  I got the error and the log had this:

15:48:51.194 INFO  POST /api/sync/now
15:48:51.538 INFO  Pushing 1 syncs in 182ms
15:48:51.544 INFO  Nothing to push
15:48:51.608 INFO  sync failed: Request to GET http://127.0.0.1:9999//api/sync/changed?lastSyncId=8476 failed, error: 500 Internal S
erver ErrorError: Request to GET http://127.0.0.1:9999//api/sync/changed?lastSyncId=8476 failed, error: 500 Internal Server Error
    at generateError (C:\tools\trilium-windows-x64\resources\app.asar\src\services\request.js:115:12)
    at ClientRequest.request.on.response (C:\tools\trilium-windows-x64\resources\app.asar\src\services\request.js:61:28)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (C:\tools\trilium-windows-x64\resources\electron.asar\browser\api\net.js:207:12)
    at URLRequest.emit (events.js:182:13)
15:48:51.681 INFO  ERROR: Failed to deserialize sync response: Internal Server Error

**Comment by pcause** [comment]
seems fixed
