### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by dongido001** [zadam/trilium#479]
I get an internal server error when I try to run the app. This is my first time installing it.

**Version**: 4.0.3

**OS**: MacOS Mojave v10.14.3

Logs:

```15:36:36.166 INFO  Generated sourceId=zzTJKATLeZqT 
15:36:36.167 INFO  App HTTP server starting up at port 52869 
15:36:36.167 INFO  {
  "appVersion": "0.30.7",
  "dbVersion": 127,
  "syncVersion": 6,
  "buildDate": "2019-03-30T20:13:53+01:00",
  "buildRevision": "c240fb98967d11ea3925c2c39b44138bb8e46f58",
  "dataDirectory": "/Users/dongido/Library/Application Support/trilium-data"
} 
15:36:36.561 INFO  GET / 
15:36:36.579 INFO  DB ready. 
15:36:36.581 INFO  ERROR: Error executing query. Inner exception: Error: SQLITE_ERROR: table source_ids has no column named dateCreatedError
    at wrap (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:137:23)
    at execute (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:122:26)
    at Object.insert (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:24:23)
    at saveSourceId (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/source_id.js:9:15)
    at sqlInit.dbReady.then.cls.wrap (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/source_id.js:45:37)
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:117:8)
    at init (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/cls.js:5:28)
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/cls.js:9:30 
15:36:36.584 INFO  Error: SQLITE_ERROR: table source_ids has no column named dateCreated
{"message":"Error: SQLITE_ERROR: table source_ids has no column named dateCreated"}
Error
    at wrap (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:137:23)
    at execute (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:122:26)
    at Object.insert (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:24:23)
    at saveSourceId (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/source_id.js:9:15)
    at sqlInit.dbReady.then.cls.wrap (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/source_id.js:45:37)
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:117:8)
    at init (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/cls.js:5:28)
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/cls.js:9:30 
15:36:36.587 INFO  DB size: 774 KB 
15:36:36.589 INFO  Generated sourceId=OuX9OjTZCV9L 
15:36:36.590 INFO  ERROR: Error executing query. Inner exception: Error: SQLITE_ERROR: table source_ids has no column named dateCreatedError
    at wrap (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:137:23)
    at execute (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:122:26)
    at Object.insert (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:24:23)
    at saveSourceId (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/source_id.js:9:15)
    at Object.generateSourceId (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/source_id.js:27:11)
    at index (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/index.js:22:41) 
15:36:36.590 INFO  ERROR: Error executing transaction, executing rollback. Inner stack: Error
    at wrap (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:137:23)
    at execute (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:122:26)
    at Object.insert (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:24:23)
    at saveSourceId (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/source_id.js:9:15)
    at Object.generateSourceId (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/source_id.js:27:11)
    at index (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/index.js:22:41)
Outside stack: Error
    at Object.transactional (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:164:23)
    at cls.init (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/routes.js:73:38)
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/cls.js:5:28)
    at router.(anonymous function) (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/routes.js:68:38)
    at Layer.handle [as handle_request] (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at checkAuth (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/auth.js:17:9) 
15:36:36.591 INFO  ERROR: get / threw exception: Error
    at wrap (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:137:23)
    at execute (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:122:26)
    at Object.insert (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:24:23)
    at saveSourceId (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/source_id.js:9:15)
    at Object.generateSourceId (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/source_id.js:27:11)
    at index (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/index.js:22:41) 
15:36:37.596 INFO  Created backup at /Users/dongido/Library/Application Support/trilium-data/backup/backup-daily.db 
15:36:37.601 INFO  ERROR: Error executing query. Inner exception: Error: SQLITE_ERROR: table options has no column named dateModifiedError
    at wrap (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:137:23)
    at execute (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:122:26)
    at insert (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:24:23)
    at Object.replace (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:30:18)
    at sql.transactional (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/repository.js:106:19)
    at Promise (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:173:25) 
15:36:37.601 INFO  ERROR: Error executing transaction, executing rollback. Inner stack: Error
    at wrap (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:137:23)
    at execute (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:122:26)
    at insert (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:24:23)
    at Object.replace (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:30:18)
    at sql.transactional (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/repository.js:106:19)
    at Promise (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:173:25)
Outside stack: Error
    at Object.transactional (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:164:23)
    at Object.updateEntity (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/repository.js:105:15) 
15:36:37.604 INFO  Error: SQLITE_ERROR: table options has no column named dateModified
{"message":"Error: SQLITE_ERROR: table options has no column named dateModified"}
Error
    at wrap (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:137:23)
    at execute (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:122:26)
    at insert (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:24:23)
    at Object.replace (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:30:18)
    at sql.transactional (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/repository.js:106:19)
    at Promise (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:173:25) 
```

**Comment by dongido001** [comment]
Yeah, it's quite possible but not sure.

I first downloaded from ElectronJS site but got the same error then I
download the version from GitHub.

Deleting the folder and starting from scratch solved it, thanks!
