### ISSUE TITLE
31.0-beta sync not working

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#483]
It looked like sync was working but it appears it isn't.  I can see items on the server and after a sync there aren't sent.  I do get the sync error I posted before. but previously the sync seemed to work.  If I go to options and say test sync I get not error.  here is what I see in the log:

1:15:24.690 INFO  sync failed: Request to GET http://localhost:8080//api/sync/changed?lastSyncId=9620 failed, error: 500 Internal Server ErrorError: Request to GET http://localhost:8080//api/sync/changed?lastSyncId=9620 failed, error: 500 Internal Server Error
    at generateError (/home/pcause/apps/trilium-linux-x64/resources/app.asar/src/services/request.js:115:12)
    at ClientRequest.request.on.response (/home/pcause/apps/trilium-linux-x64/resources/app.asar/src/services/request.js:61:28)
    at ClientRequest.emit (events.js:182:13)
    at URLRequest.ClientRequest.urlRequest.on (/home/pcause/apps/trilium-linux-x64/resources/electron.asar/browser/api/net.js:207:12)
    at URLRequest.emit (events.js:182:13) 
11:15:24.732 INFO  ERROR: Failed to deserialize sync response: Internal Server Error

NOTE:  Server is on linux, clients on both linux and win10.  recently updated my linux to ubuntu 19.04 and that did bring in a newer node 10.15.2

**Comment by zadam** [comment]
This is an error from the client side, could you also include the logs from the server side where more details would be available (since the error apparently originated from the server).

I recently fixed a bug in 0.31 sync, but to be sure it's the same thing I'd need to see the server logs ...
I will try to release a new beta with bug fixes this weekend.

**Comment by pcause** [comment]
here is the log:

11:07:24.636 INFO  ERROR: Error executing transaction, executing rollback. Inner stack: TypeError: Cannot read property 'content' of undefined
    at getEntityRow (/home/pcause/apps/trilium-linux-x64-server/src/services/sync.js:271:80)
Outside stack: Error
    at Object.transactional (/home/pcause/apps/trilium-linux-x64-server/src/services/sql.js:187:23)
    at cls.init (/home/pcause/apps/trilium-linux-x64-server/src/routes/routes.js:79:38)
    at /home/pcause/apps/trilium-linux-x64-server/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/home/pcause/apps/trilium-linux-x64-server/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/home/pcause/apps/trilium-linux-x64-server/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/home/pcause/apps/trilium-linux-x64-server/src/services/cls.js:5:28)
    at router.(anonymous function) (/home/pcause/apps/trilium-linux-x64-server/src/routes/routes.js:74:38)
    at Layer.handle [as handle_request] (/home/pcause/apps/trilium-linux-x64-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pcause/apps/trilium-linux-x64-server/node_modules/express/lib/router/route.js:137:13)
    at checkApiAuth (/home/pcause/apps/trilium-linux-x64-server/src/services/auth.js:37:9) 
11:07:24.637 INFO  ERROR: get /api/sync/changed threw exception: TypeError: Cannot read property 'content' of undefined
    at getEntityRow (/home/pcause/apps/trilium-linux-x64-server/src/services/sync.js:271:80)

**Comment by zadam** [comment]
Thank you for the logs, 0.31.1 should fix the sync issues.
