### ISSUE TITLE
31-1-beta issue opening item 

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#486]
I updated from 31-0-beta to 31-1-beta.  server and client both at 31-1-beta.  Opened client.  Seemed to resync everything.  After that I tried to open a date in the journal that had a child that previously hadn't synced.  I just got a spinning icon.  Exited and tried again, same thing so I clicked refresh front end and it now worked.  serverlog shows 

08:35:43.781 INFO  Slow query took 302ms: COMMIT 
08:35:44.012 INFO  POST //api/sync/finished 
08:35:44.095 INFO  DB ready. 
08:35:44.382 INFO  Slow query took 288ms: COMMIT 

client shows a db migrate.  then a lot of messages like

08:33:30.788 INFO  Creating missing sync record for note_contents 11ARui7up4Ma 
and similar about branches, note revisions, recent notes, attributes and more. After DB ready I see this in the server: 

08:33:52.602 INFO  Slow query took 20196ms: INSERT  INTO source_ids(sourceId, utcDateCreated) VALUES (?, ?) 

I then see it pushing a lot of syncs and see more intermittent

08:33:52.602 INFO  Slow query took 20196ms: INSERT  INTO source_ids(sourceId, utcDateCreated) VALUES (?, ?) 

I then see the matching error:

08:35:51.921 INFO  invalid csrf token
{"code":"EBADCSRFTOKEN"}
ForbiddenError: invalid csrf token
    at csrf (/home/phil/apps/trilium-linux-x64/resources/app.asar/node_modules/c
surf/index.js:112:19)
    at Layer.handle [as handle_request] (/home/phil/apps/trilium-linux-x64/resou
rces/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/phil/apps/trilium-linux-x64/resources/app.asar/node_modules/e
xpress/lib/router/route.js:137:13)
    at checkApiAuth (/home/phil/apps/trilium-linux-x64/resources/app.asar/src/se
rvices/auth.js:37:9)
    at Layer.handle [as handle_request] (/home/phil/apps/trilium-linux-x64/resou
rces/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/phil/apps/trilium-linux-x64/resources/app.asar/node_modules/e
xpress/lib/router/route.js:137:13)
    at Route.dispatch (/home/phil/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/phil/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at /home/phil/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/phil/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/index.js:335:12)

**Comment by pcause** [comment]
I updated another PC, this one windows and it sync'ed and opened the item without any issue

**Comment by zadam** [comment]
Hello, yes, update to 0.31.1 forced full sync which should resolve any sync issues previously experienced.

0.31 added CSRF protection which is related to the error in the logs, but I'm not yet sure what's the reason behind it. Thanks for testing.

**Comment by pcause** [comment]
On Windows 10:  This morning I could click on anything.  Could click on a note and have it open.  Couldn't click on a node and open to see child notes.  Etc.  Had to delete the trilium data directories and resync from scratch.  Hopefully this just an issue for me, given I did the beta and then -1 upgrades.  BTW, linux client was fine

**Comment by pcause** [comment]
fixed in beta 2
