### ISSUE TITLE
31-1 beta : open item

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#490]
on 31-1 beta I loaded things up this morning and then I clicked an item which is a top level for a heirarchy of saved content.  I got the spinning circle and nothing else.  Saw this message:

Execution of 1mH0b5isKOz7 failed with error: Load of script note "displayOnStart" (1mH0b5isKOz7) failed with: server error: undefined

log has this:

10:01:33.037 INFO  invalid csrf token
{"code":"EBADCSRFTOKEN"}
ForbiddenError: invalid csrf token
    at csrf (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at checkApiAuth (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/src/services/auth.js:37:9)
    at Layer.handle [as handle_request] (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
at next (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at /home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/index.js:335:12) 
10:01:33.037 INFO  invalid csrf token
{"code":"EBADCSRFTOKEN"}
ForbiddenError: invalid csrf token
    at csrf (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at checkApiAuth (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/src/services/auth.js:37:9)
    at Layer.handle [as handle_request] (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node
ForbiddenError: invalid csrf token
    at csrf (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at checkApiAuth (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/src/services/auth.js:37:9)
    at Layer.handle [as handle_request] (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/node

**Comment by zadam** [comment]
To give some answer - I did not manage to reproduce any of these CSRF related problems, but I saw issues with opening notes and the app being kind of frozen (or specifically backend/node process). This was caused by the new FTS5 fulltext introduced in the first beta, but it will be removed in the next beta because of these issues.

**Comment by pcause** [comment]
Thanks.  I think if you can give some message when the FTS5 starts that it is working and progress (X% done) than you can leave the capability

**Comment by zadam** [comment]
Yeah, I was thinking about some possible workarounds but there were some other issues (e.g. it can't tokenize chinese) and overall benefits of FTS5 over simple/"stupid" search are not that big so I decided it will be better to drop FTS5 for now.

**Comment by pcause** [comment]
seems fixed in -2
