### ISSUE TITLE
31-1 beta won't start fresh install

### ISSUE THREAD

**Issue by pcause** [zadam/trilium#491]
client on ubuntu 19.04

I run a server and a client on a linux box.  I start the trilium client with:

TRILIUM_DATA_DIR=/home/XXXX/.trilium-client  /home/phil/apps/trilium-linux-x64/trilium  >/dev/null 2>&1

I'd deleted the old .trilium-client directory.  The client wouldn't start and gave this message:

A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, mkdir '/home/XXXX/.trilium-client/log'
    at Object.mkdirSync (fs.js:731:3)
    at Object.<anonymous> (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/src/services/log.js:7:8)
    at Object.<anonymous> (/home/XXXX/apps/trilium-linux-x64/resources/app.asar/src/services/log.js:53:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)

i then created the .trilium-client directory, but not the log directory, and the client started and is syncing

**Comment by zadam** [comment]
Normally trilium tries to create data directory if it doesn't exist, but this wasn't the case when the directory was given in TRILIUM_DATA_DIR env variable. This is now fixed.
