### ISSUE TITLE
Importing ~2000 markdown notes with tar breaks the app

### ISSUE THREAD

**Issue by hakanu** [zadam/trilium#525]
First of all, thanks for the great app, I absolutely loved it. I'm having some trouble while migrating my other notes into trilium.

For bug reports, please mention **version of the application** and include **log files** from following location:

Server version: trilium-linux-x64-server-0.31.5
UI version: 0.31.5

Whenever I try to import my notes to migrate to trilium from Windows client to local server, it successfully seems to import as I watch the logs from the server, db size grows significantly but the loading icon next to the parent note seems persistent and I can not expand the tree from there. When I reload the frontend, it shows full white window and server starts returning the error below. Although I see the parent note in web UI, I can not expand either. 

Needed to rollback to old db to save up my notes. I have around 5K markdown notes to import like this to fully migrate to trilium.

* `/home/[user]/.local/share/trilium-data/log` for Linux
Trace: ERROR: Error executing transaction, executing rollback. Inner stack: Error
    at wrap (trilium-linux-x64-server/src/services/sql.js:160:23)
    at getRows (trilium-linux-x64-server/src/services/sql.js:109:18)
    at Object.getManyRows (trilium-linux-x64-server/src/services/sql.js:102:40)
    at load (trilium-linux-x64-server/src/routes/api/tree.js:91:30)
    at trilium-linux-x64-server/src/routes/routes.js:81:38
    at trilium-linux-x64-server/src/services/sql.js:196:25
Outside stack: Error
    at Object.transactional (trilium-linux-x64-server/src/services/sql.js:187:23)
    at async trilium-linux-x64-server/src/routes/routes.js:80:28
    at async Object.init (trilium-linux-x64-server/src/services/cls.js:5:12)
    at async trilium-linux-x64-server/src/routes/routes.js:75:28
    at Object.error (trilium-linux-x64-server/src/services/log.js:33:13)
    at trilium-linux-x64-server/src/services/sql.js:205:21
Trace: ERROR: post /api/tree/load threw exception: Error
    at wrap (trilium-linux-x64-server/src/services/sql.js:160:23)
    at getRows (trilium-linux-x64-server/src/services/sql.js:109:18)
    at Object.getManyRows (trilium-linux-x64-server/src/services/sql.js:102:40)
    at load (trilium-linux-x64-server/src/routes/api/tree.js:91:30)
    at trilium-linux-x64-server/src/routes/routes.js:81:38
    at trilium-linux-x64-server/src/services/sql.js:196:25
    at Object.error (trilium-linux-x64-server/src/services/log.js:33:13)
    at trilium-linux-x64-server/src/routes/routes.js:94:17
Trace: ERROR: JS Error: Error when calling POST tree/load: 500 - Internal Server Error
    at Object.error (trilium-linux-x64-server/src/services/log.js:33:13)
    at WebSocket.<anonymous> (trilium-linux-x64-server/src/services/messaging.js:31:21)
    at WebSocket.emit (events.js:196:13)
    at Receiver.receiverOnMessage (trilium-linux-x64-server/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:196:13)
    at Receiver.dataMessage (trilium-linux-x64-server/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (trilium-linux-x64-server/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (trilium-linux-x64-server/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (trilium-linux-x64-server/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:417:12)
* `C:\Users\[user]\AppData\Roaming\trilium-data\log` for Windows Vista and up
* `/Users/[user]/Library/Application Support/trilium-data/log` for Mac OS

**Comment by hakanu** [comment]
Just in case if you need a test set, this one liner creates 40KB 2000 markdown files:
 
```bash
mkdir test_large; cd test_large; echo "for i in range(2000):open('file_' + str(i) + '.md', 'w').write('blah' * 10000)" > test_gen.py;python test_gen.py
```

**Comment by zadam** [comment]
Hello, thank you for bug report and especially for very nice test case using which it was super easy to reproduce the problem. Bug is not actually related to import, but is more general and affected any note containing more than 999 subnotes.

Bug has been fixed and fixed version will be released soon.

**Comment by hakanu** [comment]
Thanks for the reply. Didn't know there is a limit.
Imported 900 by 900 and worked like a charm even in my version. thanks!
