### ISSUE TITLE
500 error during startup -  Error when calling GET tree: 500 - Internal Server Error

### ISSUE THREAD

**Issue by hakanu** [zadam/trilium#530]
Hi there, me again. I was deleting some notes from a large tree and suddenly web app stuttered and frozen. When I refresh the page it was all blank apart from the top navigation bar and I see 3 500 errors as modals:
Error when calling GET tree: 500 - Internal Server Error
Error when calling GET script/startup: 500 - Internal Server Error
Error when calling GET options: 500 - Internal Server Error

Sync works fine with my remote desktop app though only web app is problematic.

What do you think is the problem here?

And below my server logs: 

```
at Receiver.receiverOnMessage (trilium-linux-x64-server_031/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:196:13)
    at Receiver.dataMessage (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:417:12)
Trace: ERROR: JS Error: Error when calling GET script/startup: 500 - Internal Server Error
    at Object.error (trilium-linux-x64-server_031/src/services/log.js:33:13)
    at WebSocket.<anonymous> (trilium-linux-x64-server_031/src/services/messaging.js:31:21)
    at WebSocket.emit (events.js:196:13)
    at Receiver.receiverOnMessage (trilium-linux-x64-server_031/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:196:13)
    at Receiver.dataMessage (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:417:12)
Trace: ERROR: JS Error: Error when calling GET options: 500 - Internal Server Error
    at Object.error (trilium-linux-x64-server_031/src/services/log.js:33:13)
    at WebSocket.<anonymous> (trilium-linux-x64-server_031/src/services/messaging.js:31:21)
    at WebSocket.emit (events.js:196:13)
    at Receiver.receiverOnMessage (trilium-linux-x64-server_031/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:196:13)
    at Receiver.dataMessage (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:417:12)
Trace: ERROR: JS Error: Uncaught error: Message: Uncaught Error: Error when calling GET options: 500 - Internal Server Error - URL: http://.../libraries/jquery.min.js - Line:
2 - Column: 31040 - Error object: {}
    at Object.error (trilium-linux-x64-server_031/src/services/log.js:33:13)
    at WebSocket.<anonymous> (trilium-linux-x64-server_031/src/services/messaging.js:31:21)
    at WebSocket.emit (events.js:196:13)
    at Receiver.receiverOnMessage (trilium-linux-x64-server_031/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:196:13)
    at Receiver.dataMessage (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (trilium-linux-x64-server_031/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:417:12)
```

**Comment by zadam** [comment]
Hello, thank you for reporting this.

Are there any other logs? Since this shows only websocket errors which are not very consequential. You can attach whole log file (or send it to zadam.apps@gmail.com)

**Comment by hakanu** [comment]
Thanks for quick reply. Unfortunately I can not reproduce this anymore. I have tried a couple of stuff and interestingly fixed it by copying the new src folder into my src folder (felt like some input js file is missing in the UI code, no idea how it happened :-O).
Closing for now, will open it up in the future if it happens again. Thanks again for the great tool.
