### ISSUE TITLE
Migration Error?

### ISSUE THREAD

**Issue by wesrer** [zadam/trilium#557]
I'm trying to migrate to the latest version - 0.32.3, and for some reason, it's giving me a fatal error - Not sure what the issue is . Here are the Errors generated - 

```
18:54:52.184 INFO  ERROR: Error executing query. Inner exception: Error: SQLITE_ERROR: no such column: noteIdError
    at wrap (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sql.js:160:23)
    at Object.execute (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sql.js:145:26)
    at cleanupSyncRowsForMissingEntities (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sync_table.js:57:15)
    at fillSyncRows (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sync_table.js:65:11)
    at Object.fillAllSyncRows (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sync_table.js:94:11) 
18:54:52.184 INFO  ERROR: Error executing transaction, executing rollback. Inner stack: Error
    at wrap (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sql.js:160:23)
    at Object.execute (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sql.js:145:26)
    at cleanupSyncRowsForMissingEntities (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sync_table.js:57:15)
    at fillSyncRows (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sync_table.js:65:11)
    at Object.fillAllSyncRows (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sync_table.js:94:11)
Outside stack: Error
    at Object.transactional (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sql.js:187:23)
    at Object.migrate (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/migration.js:49:23) 
18:54:52.184 INFO  Creating missing sync record for note_revisions zxGI5ZrYvgs9 
18:54:52.185 INFO  ERROR: error during migration to version 132: Error
    at wrap (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sql.js:160:23)
    at Object.execute (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sql.js:145:26)
    at cleanupSyncRowsForMissingEntities (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sync_table.js:57:15)
    at fillSyncRows (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sync_table.js:65:11)
    at Object.fillAllSyncRows (/home/sayak/Applications/trilium-linux-x64/resources/app.asar/src/services/sync_table.js:94:11) 
18:54:52.185 INFO  ERROR: migration failed, crashing hard 
```

**Comment by zadam** [comment]
Hello, I'll take a look at it.

Are you by chance running 0.30.X? I got a report recently that the direct migration from 0.30 to 0.32 doesn't work, but if you first migrate to 0.31 and then 0.32, then it's OK, so it might be a workaround ...

**Comment by wesrer** [comment]
That might be it. I'll try migrating to 0.31 first.
