### ISSUE TITLE
Sync server has source ID .... which is also local. Try restarting sync server.

### ISSUE THREAD

**Issue by gpanders** [zadam/trilium#603]
I'm on version 0.34.1. The log files says this:

```
sync failed: Sync server has source ID xadbVC52AOoU which is also local. Try restarting sync server.Error: Sync server has source ID xadbVC52AOoU which is also local. Try restarting sync server.
    at doLogin (/usr/src/app/src/services/sync.js:100:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async login (/usr/src/app/src/services/sync.js:82:12)
    at async /usr/src/app/src/services/sync.js:32:33
    at async Object.doExclusively (/usr/src/app/src/services/sync_mutex.js:13:16)
    at async sync (/usr/src/app/src/services/sync.js:27:16)
    at async init (/usr/src/app/src/services/cls.js:5:12)
    at async Timeout._onTimeout (/usr/src/app/src/services/cls.js:9:24)
```

and repeats multiple times. This is running in a Docker container and I have tried restarting the container multiple times to no avail.

**Comment by zadam** [comment]
Hello, did you attempt to configure sync? One possible explanation of such an error would be that the sync configuration points to itself and thus trying to synchronize with itself (which is of course pointless).

**Comment by gpanders** [comment]
That does seem to have been the problem! Easy enough fix, thanks a lot.
