### ISSUE TITLE
Sync failed (0.34.3)

### ISSUE THREAD

**Issue by ma-sadeghi** [zadam/trilium#635]
Version: 0.34.3
Log file
```
13:15:28.777 INFO  POST /api/tree/load
13:26:52.956 INFO  Generated sourceId=1otZS8typHC2
13:26:52.957 INFO  App HTTP server starting up at port 8080
13:26:52.958 INFO  {
  "appVersion": "0.34.3",
  "dbVersion": 136,
  "syncVersion": 9,
  "buildDate": "2019-08-13T21:48:56+02:00",
  "buildRevision": "90f1bfb3e4838cfea676c7968473c6978ecbed1b",
  "dataDirectory": "/root/trilium-data",
  "clipperProtocolVersion": "1.0"
}
13:26:53.021 INFO  DB ready.
13:26:53.043 INFO  DB size: 1085 KB
13:26:53.647 INFO  GET /api/setup/status
13:26:53.700 INFO  POST /api/login/sync
13:27:03.063 INFO  All consistency checks passed (took 39ms)
13:27:53.433 INFO  GET /api/setup/status
13:27:53.456 INFO  POST /api/login/sync
13:28:49.057 INFO  GET /
13:28:49.342 INFO  GET /login
13:28:53.410 INFO  GET /api/setup/status
13:28:53.433 INFO  POST /api/login/sync
13:28:54.719 INFO  POST /login
13:28:55.108 INFO  GET /
13:28:55.115 INFO  Generated CSRF token KBst5VKz-Hn7WXT8EkxN12hRgveskh9B6kkk with secret undefined
13:28:55.116 INFO  Generated sourceId=oYNKEtP0as4Z
13:28:55.785 INFO  GET /api/tree
13:28:55.786 INFO  GET /api/notes/download/2lsidPoeG49M
13:28:55.787 INFO  GET /api/notes/download/A3VbaWzaxSmA
13:28:55.788 INFO  GET /api/notes/download/8a7HcvwZl6Hi
13:28:55.789 INFO  GET /api/options
13:28:55.892 INFO  POST /api/tree/load
13:28:55.926 INFO  POST /api/tree/load
13:28:55.971 INFO  POST /api/tree/load
13:28:56.003 INFO  GET /api/notes/nPmhuyA0GiOJ
13:28:56.080 INFO  GET /api/notes/nPmhuyA0GiOJ/attributes
13:28:56.419 INFO  GET /api/script/relation/nPmhuyA0GiOJ/runOnNoteView
13:28:56.457 INFO  POST /api/tree/load
13:28:56.503 INFO  GET /api/script/startup
13:28:56.535 INFO  POST /api/tree/load
13:28:56.570 INFO  POST /api/tree/load
13:28:56.604 INFO  POST /api/tree/load
13:28:56.634 INFO  POST /api/tree/load
13:28:56.664 INFO  POST /api/tree/load
13:28:56.692 INFO  POST /api/tree/load
13:28:56.724 INFO  POST /api/tree/load
13:28:56.755 INFO  POST /api/tree/load
13:28:56.785 INFO  POST /api/tree/load
13:28:59.330 INFO  POST /logout
13:28:59.354 INFO  GET /login
13:29:05.754 INFO  GET /api/setup/status
13:29:05.774 INFO  POST /api/login/sync
13:29:53.410 INFO  GET /api/setup/status
13:29:53.433 INFO  POST /api/login/sync
13:30:53.411 INFO  GET /api/setup/status
13:30:53.433 INFO  POST /api/login/sync
13:31:53.416 INFO  GET /api/setup/status
13:31:53.439 INFO  POST /api/login/sync
13:32:36.820 INFO  GET /api/setup/status
13:32:36.841 INFO  POST /api/login/sync
```

**Comment by zadam** [comment]
Hello, is it ui which tells you "sync failed" since log doesn't say anything ...

Also, since I see login & logout in the log, this is probably a server instance ... with what other instance are you trying to sync? Typically what's supported is that desktop syncs with the server, but then the sync must be initiated from the desktop.

**Comment by ma-sadeghi** [comment]
@zadam The desktop app fails to sync.

**Comment by ma-sadeghi** [comment]
```
 
09:58:52.981 INFO  sync failed: Request to PUT https://notes.zaboor.ca/api/sync/update failed, error: 413 Request Entity Too LargeError: Request to PUT https://notes.zaboor.ca/api/sync/update failed, error: 413 Request Entity Too Large
    at generateError (C:\Users\Amin\Downloads\Compressed\trilium-windows-x64-0.34.3\trilium-windows-x64\resources\app.asar\src\services\request.js:121:12)
    at ClientRequest.<anonymous> (C:\Users\Amin\Downloads\Compressed\trilium-windows-x64-0.34.3\trilium-windows-x64\resources\app.asar\src\services\request.js:51:28)
    at ClientRequest.emit (events.js:200:13)
    at URLRequest.<anonymous> (C:\Users\Amin\Downloads\Compressed\trilium-windows-x64-0.34.3\trilium-windows-x64\resources\electron.asar\browser\api\net.js:221:18)
    at URLRequest.emit (events.js:200:13) 
09:59:52.991 INFO  ERROR: Failed to deserialize sync response: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.15.9 (Ubuntu)</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
 
09:59:52.992 INFO  sync failed: Request to PUT https://notes.zaboor.ca/api/sync/update failed, error: 413 Request Entity Too LargeError: Request to PUT https://notes.zaboor.ca/api/sync/update failed, error: 413 Request Entity Too Large
    at generateError (C:\Users\Amin\Downloads\Compressed\trilium-windows-x64-0.34.3\trilium-windows-x64\resources\app.asar\src\services\request.js:121:12)
    at ClientRequest.<anonymous> (C:\Users\Amin\Downloads\Compressed\trilium-windows-x64-0.34.3\trilium-windows-x64\resources\app.asar\src\services\request.js:51:28)
    at ClientRequest.emit (events.js:200:13)
    at URLRequest.<anonymous> (C:\Users\Amin\Downloads\Compressed\trilium-windows-x64-0.34.3\trilium-windows-x64\resources\electron.asar\browser\api\net.js:221:18)
    at URLRequest.emit (events.js:200:13) 
```

**Comment by ma-sadeghi** [comment]
I found a similar issue #395, which fixed mine! Thanks @ryansyah.

**Comment by ma-sadeghi** [comment]
@zadam, just a suggestion: maybe include the workaround in the Wiki page related to server setup.

**Comment by zadam** [comment]
Glad to see you resolved it. This is actually already mentioned in the server setup paragraph on nginx: https://github.com/zadam/trilium/wiki/Server-installation
