### ISSUE TITLE
Importing fails with mime.toLowerCase() is not a function

### ISSUE THREAD

**Issue by mkg20001** [zadam/trilium#665]
Version: 0.35.2
OS: Ubuntu 19.04 amd64

```
00:04:49.941 INFO  POST /api/notes/kxjFe3a7Y6JZ/import 
00:04:49.960 INFO  ERROR: Import failed with following error: 'mime.toLowerCase is not a function'. More details might be in the logs.TypeError: mime.toLowerCase is not a function
    at Object.getType (/usr/lib/trilium/resources/app.asar/src/services/import/mime.js:82:17)
    at Object.importSingleFile (/usr/lib/trilium/resources/app.asar/src/services/import/single.js:23:57)
    at importToBranch (/usr/lib/trilium/resources/app.asar/src/routes/api/import.js:56:46)
    at async /usr/lib/trilium/resources/app.asar/src/routes/routes.js:84:32
    at async /usr/lib/trilium/resources/app.asar/src/services/sql.js:196:19 
00:04:49.961 INFO  Sending message to all clients: {"type":"import-error","message":"Import failed with following error: 'mime.toLowerCase is not a function'. More details might be in the logs."} 
00:04:49.963 INFO  POST /api/notes/kxjFe3a7Y6JZ/import returned 500 with response "Import failed with following error: 'mime.toLowerCase is not a function'. More details might be in the logs." 
```

**Comment by zadam** [comment]
Hi, thanks for reporting this issue, I think this has been fixed in the master already (0.36.X)
