### ISSUE TITLE
[BUG] Cannot rename note (TypeError: Cannot read property 'replace' of undefined)

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#694]
Version: v0.36.3

Each time i rename the tittle of an existing note (from the GUI, i don't know if it also happens from the script API), it first seems to work properly, but the change is not persistent, if i leave note then go back, the old name if still here.

Error from logs:
```
INFO  ERROR: Error executing transaction, executing rollback. Inner stack: TypeError: Cannot read property 'replace' of undefined
    at findImageLinks (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/services/notes.js:228:20)
    at saveLinks (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/services/notes.js:269:19)
    at Object.updateNote (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/services/notes.js:374:37)
    at async updateNote (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/routes/api/notes.js:73:12)
    at async /lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/routes/routes.js:84:32
    at async /lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/services/sql.js:196:19
Outside stack: Error
    at Object.transactional (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/services/sql.js:187:23)
    at /lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/routes/routes.js:83:38
    at /lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/services/cls.js:5:28)
    at /lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/routes/routes.js:78:38
    at Layer.handle [as handle_request] (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at csrf (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/node_modules/csurf/index.js:117:5) 
21:52:20.287 INFO  ERROR: put /api/notes/:noteId threw exception: TypeError: Cannot read property 'replace' of undefined
    at findImageLinks (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/services/notes.js:228:20)
    at saveLinks (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/services/notes.js:269:19)
    at Object.updateNote (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/services/notes.js:374:37)
    at async updateNote (/lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/routes/api/notes.js:73:12)
    at async /lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/routes/routes.js:84:32
    at async /lib/trilium/trilium-linux-x64-0.36.3/resources/app.asar/src/services/sql.js:196:19
```

Anyway, the project is growing fast, and as it becomes more complex, the need for devops integration / automated tests start being interesting.

**Comment by zadam** [comment]
Thanks for bug report, this has been fixed. It affects only text node in "auto-book" mode when they are empty and instead show the children. Workaround is to click "here" in the `This note doesn't have any content so we display its children. Click here if you want to add some text.` and then rename the note.

For the note on the automated tests - that would be definitely nice, but automated tests for GUI apps are pretty time consuming. For now I prefer to move fast even with the risk of having bugs. In the coming months I plan to release 1.0 version with increased testing and more conservative/careful approach to development.
