### ISSUE TITLE
ERROR: Execution of script "tool note not in path failed with error: Unexpected identifier 

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#709]
Hi ! in order to search with prefix path (as stated in https://github.com/zadam/trilium/issues/534), i created a [Saved search with script relation](https://github.com/zadam/trilium/wiki/Search#saved-search-with-script-relation):
```js
// return all notes maching '@cssClass=tool', but only if they are NOT in path 'Tools /'

// true if `note` has some indirect parent with `noteId`
function hasParent(note, noteId) {
    if (note.noteId === noteId) {
        return true;
    }
    for (const parent of await note.getParentNotes()) {
        if (hasParent(parent, noteId)) {
            return true;
        }
    }
    return false;
}

const result = [];
for (const note of await api.searchForNotes("@cssClass=tool")) {
    if (!hasParent(note, 'QlURGdaKf3rf')) {
        result.push(note);
    }
}

return result;
```
Therefore, when i try to execute it (by clicking `Refresh search results` in related `Saved Search note`), no note is returned, the `loading` icon keeps going round in circles, and the following error is thrown (in logs):
```js
16:29:50.142 INFO  ERROR: Execution of script "tool note not in path 'Tools /'" (VodoIT6Z5guv) failed with error: Unexpected identifier 
16:29:50.145 INFO  ERROR: Error executing transaction, executing rollback. Inner stack: SyntaxError: Unexpected identifier
    at ScriptContext.<anonymous> (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:76:76)
    at execute (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:76:96)
    at /opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:47:62
    at Object.transactional (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/sql.js:184:22)
    at executeBundle (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:47:30)
    at async Object.executeNote (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:17:12)
    at async searchFromRelation (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/routes/api/search.js:80:20)
    at async searchFromNote (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/routes/api/search.js:47:19)
    at async /opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/routes/routes.js:84:32
    at async /opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/sql.js:201:19
Outside stack: Error
    at Object.transactional (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/sql.js:192:23)
    at /opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/routes/routes.js:83:38
    at /opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/cls.js:5:28)
    at /opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/routes/routes.js:78:38
    at Layer.handle [as handle_request] (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at csrf (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/node_modules/csurf/index.js:117:5) 
16:29:50.147 INFO  ERROR: get /api/search-note/:noteId threw exception: SyntaxError: Unexpected identifier
    at ScriptContext.<anonymous> (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:76:76)
    at execute (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:76:96)
    at /opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:47:62
    at Object.transactional (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/sql.js:184:22)
    at executeBundle (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:47:30)
    at async Object.executeNote (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:17:12)
    at async searchFromRelation (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/routes/api/search.js:80:20)
    at async searchFromNote (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/routes/api/search.js:47:19)
    at async /opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/routes/routes.js:84:32
    at async /opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/sql.js:201:19 
16:29:50.150 INFO  ERROR: get /api/search-note/:noteId threw exception: SyntaxError: Unexpected identifier
    at ScriptContext.<anonymous> (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:76:76)
    at execute (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:76:96)
    at /opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:47:62
    at Object.transactional (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/sql.js:184:22)
    at executeBundle (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:47:30)
    at async Object.executeNote (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/script.js:17:12)
    at async searchFromRelation (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/routes/api/search.js:80:20)
    at async searchFromNote (/opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/routes/api/search.js:47:19)
    at async /opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/routes/routes.js:84:32
    at async /opt/trilium/trilium-linux-x64-0.37.0-beta/resources/app.asar/src/services/sql.js:201:19
```

**Comment by zadam** [comment]
Your `hasParent` function must be async since it calls await. Unfortunately the error message is not helpful but that just comes from the JS engine ...

**Comment by nil0x42** [comment]
Thank you !
