### ISSUE TITLE
0.37.2 No recent changes anymore

### ISSUE THREAD

**Issue by jaroet** [zadam/trilium#713]
After installing 0.37.2 my recent changes is not working anymore. 

The log is showing the following:
18:48:49.866 INFO  GET /api/recent-changes 
18:48:49.867 INFO  ERROR: Error executing query. Inner exception: Error: SQLITE_ERROR: ambiguous column name: utcDateCreatedError
    at wrap (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:165:23)
    at Object.getRows (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:109:18)
    at getRecentChanges (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/api/recent_changes.js:7:37)
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/routes.js:84:38
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:201:25 
18:48:49.869 INFO  ERROR: Error executing transaction, executing rollback. Inner stack: Error
    at wrap (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:165:23)
    at Object.getRows (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:109:18)
    at getRecentChanges (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/api/recent_changes.js:7:37)
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/routes.js:84:38
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:201:25
Outside stack: Error
    at Object.transactional (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:192:23)
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/routes.js:83:38
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/cls.js:5:28)
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/routes.js:78:38
    at Layer.handle [as handle_request] (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at csrf (/Applications/Trilium Notes.app/Contents/Resources/app.asar/node_modules/csurf/index.js:117:5) 
18:48:49.870 INFO  ERROR: get /api/recent-changes threw exception: Error
    at wrap (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:165:23)
    at Object.getRows (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:109:18)
    at getRecentChanges (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/api/recent_changes.js:7:37)
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/src/routes/routes.js:84:38
    at /Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/sql.js:201:25 
18:48:53.713 INFO  POST /api/recent-notes 

New edits also do not show up in the recent changes. It is totally empty with only the title visible. 

Editing notes seems to work fine. When I add text to notes the search function is finding that text correctly so it seems to be specific to the recent changes. 

Regards,
JeRoen

**Comment by zadam** [comment]
Thank you for reporting this issue, the recent change dialog was indeed broken. This was fixed and patch version will be released soon.
