### ISSUE TITLE
customRequestHandler: api.getTodayNote is not a function

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#744]
Hello
I'm trying to make my custom request handler, but there is an issue i couldn't understand.
When i do my HTTP POST, the following error it triggered in the log:
```
21:12:08.704 INFO  ERROR: Error executing transaction, executing rollback. Inner stack: Error: Load of script note "render-singlefile" (jK93sM48CW5L) failed with: api.getTodayNote is not a function
    at Object.eval (eval at <anonymous> (/lib/trilium/trilium-linux-x64-0.37.6/resources/app.asar/src/services/script.js:76:39), <anonymous>:68:21)
    at eval (eval at <anonymous> (/lib/trilium/trilium-linux-x64-0.37.6/resources/app.asar/src/services/script.js:76:39), <anonymous>:72:4)
    at eval (eval at <anonymous> (/lib/trilium/trilium-linux-x64-0.37.6/resources/app.asar/src/services/script.js:76:39), <anonymous>:75:2)
    at ScriptContext.<anonymous> (/lib/trilium/trilium-linux-x64-0.37.6/resources/app.asar/src/services/script.js:76:39)
    at execute (/lib/trilium/trilium-linux-x64-0.37.6/resources/app.asar/src/services/script.js:76:96)
    at /lib/trilium/trilium-linux-x64-0.37.6/resources/app.asar/src/services/script.js:47:62
    at /lib/trilium/trilium-linux-x64-0.37.6/resources/app.asar/src/services/sql.js:201:25
Outside stack: Error
    at Object.transactional (/lib/trilium/trilium-linux-x64-0.37.6/resources/app.asar/src/services/sql.js:192:23)
    at executeBundle (/lib/trilium/trilium-linux-x64-0.37.6/resources/app.asar/src/services/script.js:47:30)
    at async Object.executeNote (/lib/trilium/trilium-linux-x64-0.37.6/resources/app.asar/src/services/script.js:17:12)
    at async /lib/trilium/trilium-linux-x64-0.37.6/resources/app.asar/src/routes/custom.js:37:21 
21:12:08.705 INFO  ERROR: Execution of script "render-singlefile" (jK93sM48CW5L) failed with error: Load of script note "render-singlefile" (jK93sM48CW5L) failed with: api.getTodayNote is not a function 
21:12:08.706 INFO  ERROR: Custom handler jK93sM48CW5L failed with Load of script note "render-singlefile" (jK93sM48CW5L) failed with: api.getTodayNote is not a function
```

Here is the source of my `customRequestHandler`:
```js
// render-singlefile

const template = `
<script>
    var iframe = document.getElementById('r-iframe');

    function pageY(elem) {
        return elem.offsetParent ? (elem.offsetTop + pageY(elem.offsetParent)) : elem.offsetTop;
    }

    function resizeIframe() {
        var height = document.documentElement.clientHeight;
        height -= pageY(iframe) + 20 ;
        height = (height < 0) ? 0 : height;
        iframe.style.height = height + 'px';
    }

    iframe.onload = resizeIframe;
    window.onresize = resizeIframe;
</script>

<iframe id="r-iframe" style="width:100%" src="data:text/html;charset=utf-8,%%CONTENT%%" sandbox="">
`;

const {req, res} = api;
const {title, url, content} = req.body;

if (req.method == 'POST') {
    const todayNote = await api.getTodayNote();
    
    // create render note
    const renderNote = (await api.createNewNote({
        parentNoteId: todayNote.noteId,
        title: title,
        content: '',
        type: 'render'
    })).note;
    await renderNote.setLabel('clipType', 'render-singlefile');
    await renderNote.setLabel('pageUrl', url);
    await renderNote.setLabel('pageTitle', title);

    // create child `content.html`
    content = template.replace("%%CONTENT%%", encodeURI(content));

    const htmlNote = (await api.createNewNote({
        parentNoteId: renderNote.noteId,
        title: 'content.html',
        content: content,
        type: 'file',
        mime: 'text/html'
    })).note;
    await htmlNote.setLabel('archived');

    // link renderNote to htmlNote
    await renderNote.setRelation('renderNote', htmlNote.noteId);

    res.send(201); // http 201: created
}
else {
    res.send(400); // http 400: bad request
}
```

**Comment by zadam** [comment]
The issue is that getTodayNote() is not available in the backend script API, only in the frontend one. Use `getDateNote()` with the date as parameter. Actually master branch already contains this script API for backend.

Unfortunately the frontend and backend script APIs are distinct - I try to keep them mostly in sync, but it is a manual process ...

**Comment by nil0x42** [comment]
Ahhh got it, so the doc is about master branch.
I remove the need for getTodayNote() on my script, but i am now blocked by the lack of `createNewNote()`, which is mandatory for my script because i need to create both a `render` and a `file` note.

So i'll have to be patient, right ?

**Comment by zadam** [comment]
Should be doable using old `.createNote()` API - see https://github.com/zadam/trilium/blob/stable/src/services/backend_script_api.js

Master/0.38 has refactoring of this note creation API since the old .createNote() is kind of messy ...
