### ISSUE TITLE
Vacuum database throws error

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#745]
I get the following error in the terminal log wwhen clikc on vacuum database in the settings.

Trilium Linux X64

```
App version:	0.37.6
DB version:	153
Sync version:	11
```

```
Trace: ERROR: Error executing query. Inner exception: Error: SQLITE_ERROR: cannot VACUUM from within a transactionError
    at wrap (/usr/lib/trilium/resources/app.asar/src/services/sql.js:165:23)
    at Object.execute (/usr/lib/trilium/resources/app.asar/src/services/sql.js:145:26)
    at vacuumDatabase (/usr/lib/trilium/resources/app.asar/src/routes/api/cleanup.js:7:15)
    at /usr/lib/trilium/resources/app.asar/src/routes/routes.js:88:34
    at /usr/lib/trilium/resources/app.asar/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/usr/lib/trilium/resources/app.asar/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/usr/lib/trilium/resources/app.asar/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/usr/lib/trilium/resources/app.asar/src/services/cls.js:5:28)
    at /usr/lib/trilium/resources/app.asar/src/routes/routes.js:78:38
    at Layer.handle [as handle_request] (/usr/lib/trilium/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at Object.error (/usr/lib/trilium/resources/app.asar/src/services/log.js:33:13)
    at wrap (/usr/lib/trilium/resources/app.asar/src/services/sql.js:171:13)
Trace: ERROR: post /api/cleanup/vacuum-database threw exception: Error
    at wrap (/usr/lib/trilium/resources/app.asar/src/services/sql.js:165:23)
    at Object.execute (/usr/lib/trilium/resources/app.asar/src/services/sql.js:145:26)
    at vacuumDatabase (/usr/lib/trilium/resources/app.asar/src/routes/api/cleanup.js:7:15)
    at /usr/lib/trilium/resources/app.asar/src/routes/routes.js:88:34
    at /usr/lib/trilium/resources/app.asar/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/usr/lib/trilium/resources/app.asar/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/usr/lib/trilium/resources/app.asar/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/usr/lib/trilium/resources/app.asar/src/services/cls.js:5:28)
    at /usr/lib/trilium/resources/app.asar/src/routes/routes.js:78:38
    at Layer.handle [as handle_request] (/usr/lib/trilium/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at Object.error (/usr/lib/trilium/resources/app.asar/src/services/log.js:33:13)
    at /usr/lib/trilium/resources/app.asar/src/routes/routes.js:97:17

```

**Comment by zadam** [comment]
Hmm, I cannot reproduce, vacuum works for me ...

**Comment by gerroon** [comment]
Thanks for the feedback. I opened the db in sqlitebrowser, optimized the db in it and restarted Trilium now I do not get this error.
