### ISSUE TITLE
Syncing Client to new Trilium Server

### ISSUE THREAD

**Issue by Xorso** [zadam/trilium#748]
I moved my Trilium backend server to a new server and started fresh (I lost my other server). I am now getting the errors below while trying to sync.

Version: 
Server:
```
{
  "appVersion": "0.37.8",
  "dbVersion": 153,
  "syncVersion": 11,
  "buildDate": "2019-12-03T22:31:20+01:00",
  "buildRevision": "b0310e34e2c6f023cc8190310ff63d840157f6cc",
  "dataDirectory": "/root/trilium-data",
  "clipperProtocolVersion": "1.0"
}
```
MacOS Client Version:
Version 0.37.8 (0.37.8)

Server Logs:
```
DB not initialized, please visit setup page to see instructions on how to initialize Trilium.
Creating database for sync
Slow query took 202ms: COMMIT
Schema and not synced options generated.
PUT /api/sync/update rejected with 401 Not authorized
PUT /api/sync/update rejected with 401 Not authorized
PUT /api/sync/update rejected with 401 Not authorized
PUT /api/sync/update rejected with 401 Not authorized
```

Client logs:
```
08:38:45.351 INFO  ERROR: Failed to deserialize sync response: Not authorized
08:38:45.352 INFO  sync failed: Request to PUT https://notes.lordinnovators.com/api/sync/update failed, error: 401 Error: Request to PUT https://notes.lordinnovators.com/api/sync/update failed, error: 401
    at generateError (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/request.js:121:12)
    at ClientRequest.<anonymous> (/Applications/Trilium Notes.app/Contents/Resources/app.asar/src/services/request.js:51:28)
    at ClientRequest.emit (events.js:200:13)
    at URLRequest.<anonymous> (/Applications/Trilium Notes.app/Contents/Resources/electron.asar/browser/api/net.js:221:18)
    at URLRequest.emit (events.js:200:13)
```

**Comment by Xorso** [comment]
Looks like my issue was that I was proxying through CloudFlare and the communication all the way through was not matching up. If I hit the server directly it worked fine.
