### ISSUE TITLE
[BUG][web-clipper] not working since v0.38-beta

### ISSUE THREAD

**Issue by nil0x42** [zadam/trilium#752]
Hi ! Since v0.38 i could not use trilium-web-clipper anymore.

Here is the trilium backend error:
```
19:19:03.596 INFO  POST /api/clipper/notes 
19:19:03.598 INFO  ERROR: Error executing transaction, executing rollback. Inner stack: Error: Note type is a required param
    at deriveMime (/lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/src/services/notes.js:39:15)
    at Object.createNewNote (/lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/src/services/notes.js:109:15)
    at async createNote (/lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/src/routes/api/clipper.js:58:20)
    at async /lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/src/routes/routes.js:85:32
    at async /lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/src/services/sql.js:206:19
Outside stack: Error
    at Object.transactional (/lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/src/services/sql.js:197:23)
    at /lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/src/routes/routes.js:84:38
    at /lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/src/services/cls.js:5:28)
    at /lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/src/routes/routes.js:79:38
    at Layer.handle [as handle_request] (/lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/node_modules/express/lib/router/route.js:112:3) 
19:19:03.599 INFO  ERROR: post /api/clipper/notes threw exception: Error: Note type is a required param
    at deriveMime (/lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/src/services/notes.js:39:15)
    at Object.createNewNote (/lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/src/services/notes.js:109:15)
    at async createNote (/lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/src/routes/api/clipper.js:58:20)
    at async /lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/src/routes/routes.js:85:32
    at async /lib/trilium/trilium-linux-x64-0.38.0-beta/resources/app.asar/src/services/sql.js:206:19
```

**Comment by zadam** [comment]
Thanks, fixed.

**Comment by ygbillet** [comment]
Hi,

Seems broken again on 0.39.5 and 0.40.0 beta

```
14:30:18.048 INFO  POST /api/clipper/notes 
14:30:18.056 INFO  ERROR: Error executing transaction, executing rollback. Inner stack: Error: Note type is a required param
    at deriveMime (C:\tools\trilium\resources\app.asar\src\services\notes.js:38:15)
    at Object.createNewNote (C:\tools\trilium\resources\app.asar\src\services\notes.js:108:15)
    at async getRootCalendarNote (C:\tools\trilium\resources\app.asar\src\services\date_notes.js:39:21)
    at async Object.getDateNote (C:\tools\trilium\resources\app.asar\src\services\date_notes.js:142:22)
    at async createNote (C:\tools\trilium\resources\app.asar\src\routes\api\clipper.js:57:23)
    at async C:\tools\trilium\resources\app.asar\src\routes\routes.js:89:32
    at async C:\tools\trilium\resources\app.asar\src\services\sql.js:206:19
Outside stack: Error
    at Object.transactional (C:\tools\trilium\resources\app.asar\src\services\sql.js:197:23)
    at C:\tools\trilium\resources\app.asar\src\routes\routes.js:88:38
    at C:\tools\trilium\resources\app.asar\node_modules\cls-hooked\context.js:118:13
    at Namespace.run (C:\tools\trilium\resources\app.asar\node_modules\cls-hooked\context.js:97:5)
    at Namespace.runAndReturn (C:\tools\trilium\resources\app.asar\node_modules\cls-hooked\context.js:117:8)
    at Object.init (C:\tools\trilium\resources\app.asar\src\services\cls.js:5:28)
    at C:\tools\trilium\resources\app.asar\src\routes\routes.js:83:38
    at Layer.handle [as handle_request] (C:\tools\trilium\resources\app.asar\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\tools\trilium\resources\app.asar\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\tools\trilium\resources\app.asar\node_modules\express\lib\router\route.js:112:3) 
14:30:18.057 INFO  ERROR: post /api/clipper/notes threw exception: Error: Note type is a required param
    at deriveMime (C:\tools\trilium\resources\app.asar\src\services\notes.js:38:15)
    at Object.createNewNote (C:\tools\trilium\resources\app.asar\src\services\notes.js:108:15)
    at async getRootCalendarNote (C:\tools\trilium\resources\app.asar\src\services\date_notes.js:39:21)
    at async Object.getDateNote (C:\tools\trilium\resources\app.asar\src\services\date_notes.js:142:22)
    at async createNote (C:\tools\trilium\resources\app.asar\src\routes\api\clipper.js:57:23)
    at async C:\tools\trilium\resources\app.asar\src\routes\routes.js:89:32
    at async C:\tools\trilium\resources\app.asar\src\services\sql.js:206:19 
```

**Comment by zadam** [comment]
@ygbillet thanks for reporting this issue - this is not related to the clipper specifically but is a bit special case since you did not have a root calendar note yet and there was a bug in creating this root note. This has been fixed and will be released in a patch release soon.

**Comment by zadam** [comment]
To be clear, this was a bug - if there isn't a rootCalendar note, it should be automatically created. This is now fixed.
