### ISSUE TITLE
Cannot Add Types to Code Notes 

### ISSUE THREAD

**Issue by joshcsullivan** [zadam/trilium#755]
OS V: Ubuntu 18.04.3 (LTS) x64
Trilium V: 0.37.8
Log: [trilium-2019-12-07.log](https://github.com/zadam/trilium/files/3935165/trilium-2019-12-07.log)

When I try to add any MIME type in the Options > Code notes menu, it doesn't add them.

From the log:
```
14:43:23.951 INFO  Updating option codeNotesMimeTypes to ["text/x-csrc","text/x-c++src","text/x-csharp","text/css","text/x-go","text/x-groovy","text/x-haskell","text/html","message/http","text/x-java","application/javascript;env=frontend","application/javascript;env=backend","application/json","text/x-kotlin","text/x-markdown","text/x-perl","text/x-php","application/x-powershell","text/x-python","text/x-ruby","text/x-sh","text/x-sql","text/x-swift","text/xml","text/x-yaml"] 
14:43:23.951 INFO  Option codeNotesMimeTypes doesn't exist
{}
Error: Option codeNotesMimeTypes doesn't exist
    at Object.setOption (/home/josh/trilium-linux-x64-server/src/services/options.js:45:15)
    at async update (/home/josh/trilium-linux-x64-server/src/routes/api/options.js:73:5) 
14:43:23.969 INFO  GET /api/options 
14:43:24.661 INFO  PUT /api/options 
14:43:24.665 INFO  Updating option codeNotesMimeTypes to ["text/x-csrc","text/x-c++src","text/x-csharp","text/css","text/x-go","text/x-groovy","text/x-haskell","text/html","message/http","text/x-java","application/javascript;env=frontend","application/javascript;env=backend","application/json","text/x-kotlin","text/x-markdown","text/x-perl","text/x-php","text/x-pgsql","application/x-powershell","text/x-python","text/x-ruby","text/x-sh","text/x-sql","text/x-swift","text/xml","text/x-yaml"] 
14:43:24.666 INFO  Option codeNotesMimeTypes doesn't exist
{}
Error: Option codeNotesMimeTypes doesn't exist
    at Object.setOption (/home/josh/trilium-linux-x64-server/src/services/options.js:45:15)
    at async update (/home/josh/trilium-linux-x64-server/src/routes/api/options.js:73:5) 
```

This happens with any type, but in that example, I was trying to add PowerShell and PostgreSQL.

Any help is appreciated.

Cheers,
Josh

**Comment by zadam** [comment]
Hi Josh, thanks for reporting this issue, it looks like a bug. As a quick fix to remedy this problem for you, open the SQL console (ALT+O), put following query to the text area and hit execute:

```sql
INSERT INTO options (name, value, utcDateCreated, utcDateModified, isSynced)
VALUES ('codeNotesMimeTypes', '["text/x-csrc","text/x-c++src","text/x-csharp","text/css","text/x-go","text/x-groovy","text/x-haskell","text/html","message/http","text/x-java","application/javascript;env=frontend","application/javascript;env=backend","application/json","text/x-kotlin","text/x-markdown","text/x-perl","text/x-php","text/x-python","text/x-ruby",null,"text/x-sql","text/x-swift","text/xml","text/x-yaml"]', '2018-07-29T18:31:00.874Z', '2018-07-29T18:31:00.874Z', 1);
```

After that you should be able to change the code note setting.
