### ISSUE TITLE
0.39 server does not start Error: Cannot find module 'electron'

### ISSUE THREAD

**Issue by gerroon** [zadam/trilium#784]
```

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'electron'
Require stack:
- /media/drive/opt/trillium_server/src/services/window.js
- /media/drive/opt/trillium_server/src/routes/setup.js
- /media/drive/opt/trillium_server/src/routes/routes.js
- /media/drive/opt/trillium_server/src/app.js
- /media/drive/opt/trillium_server/src/www
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/media/drive/opt/trillium_server/src/services/window.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/media/drive/opt/trillium_server/src/services/window.js',
    '/media/drive/opt/trillium_server/src/routes/setup.js',
    '/media/drive/opt/trillium_server/src/routes/routes.js',
    '/media/drive/opt/trillium_server/src/app.js',
    '/media/drive/opt/trillium_server/src/www'
  ]
}


```

**Comment by zadam** [comment]
Hi, thanks for reporting this issue. It's fixed now and I re-uploaded fixed server release to github ...

**Comment by gerroon** [comment]
THanks, I will test it.
