### ISSUE TITLE
Day note shortcut doesn't work (v0.39 beta)

### ISSUE THREAD

**Issue by bwat47** [zadam/trilium#786]
OS is windows 10

Steps to Re-create:
1. Open trilium
2. Invoke the global daynote shortcut (in my case Ctrl + Alt + P)

Expected: Should create new day note

Actual: Nothing happens

NOTE: The trilium log seems to generate this error after I use the shortcut:

ReferenceError: mainWindow is not defined
    at C:\Users\bwatkins.MISYS\trilium-windows-x64\resources\app.asar\electron.js:43:21
    at C:\Users\bwatkins.MISYS\trilium-windows-x64\resources\app.asar\node_modules\cls-hooked\context.js:118:13
    at Namespace.run (C:\Users\bwatkins.MISYS\trilium-windows-x64\resources\app.asar\node_modules\cls-hooked\context.js:97:5)
    at Namespace.runAndReturn (C:\Users\bwatkins.MISYS\trilium-windows-x64\resources\app.asar\node_modules\cls-hooked\context.js:117:8)
    at init (C:\Users\bwatkins.MISYS\trilium-windows-x64\resources\app.asar\src\services\cls.js:5:28)
    at AsyncFunction.<anonymous> (C:\Users\bwatkins.MISYS\trilium-windows-x64\resources\app.asar\src\services\cls.js:9:30) 

Full log attached:
[trilium-2019-12-26.log](https://github.com/zadam/trilium/files/4002707/trilium-2019-12-26.log)

NOTE: I tried enabling the native titlebar, but it didn't make a difference

**Comment by zadam** [comment]
Thanks for reporting this bug, it has been fixed.

For the native title bar, did you try to restart the app after changing the settings?
