### ISSUE TITLE
Failed to optimize image

### ISSUE THREAD

**Issue by chncho** [zadam/trilium#801]
When I past a image from clipboard, the log appears an error like this

```
Trace: ERROR: Failed to optimize image 'image.png'
Stack: Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:548:9)
    at Module.module.exports (/usr/lib/trilium/resources/app.asar/node_modules/imagemin-mozjpeg/node_modules/execa/index.js:205:26)
    at Function.module.exports.stdout (/usr/lib/trilium/resources/app.asar/node_modules/imagemin-mozjpeg/node_modules/execa/index.js:319:45)
    at /usr/lib/trilium/resources/app.asar/node_modules/imagemin-mozjpeg/index.js:105:15
    at /usr/lib/trilium/resources/app.asar/node_modules/p-pipe/index.js:12:25
    at AsyncFunction.module.exports.buffer (/usr/lib/trilium/resources/app.asar/node_modules/imagemin/index.js:72:26)
    at optimize (/usr/lib/trilium/resources/app.asar/src/services/image.js:119:27)
    at async shrinkImage (/usr/lib/trilium/resources/app.asar/src/services/image.js:82:28)
    at async processImage (/usr/lib/trilium/resources/app.asar/src/services/image.js:25:50)
    at Object.error (/usr/lib/trilium/resources/app.asar/src/services/log.js:33:13)
    at shrinkImage (/usr/lib/trilium/resources/app.asar/src/services/image.js:84:13)
Trace: ERROR: JS Error: Uncaught error: Message: Uncaught Error: The module '/tmp/.org.chromium.Chromium.8hHnLM'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
```
So , should I re-compiling it on my system? Or , are there any settings to fix it ?

**Comment by chncho** [comment]
Oh, my desktop version is 0.38.3

**Comment by zadam** [comment]
Hello, do you use a build from the github or did you compile from sources yourself?

**Comment by chncho** [comment]
I download it from https://github.com/zadam/trilium/releases/download/v0.38.3/trilium-linux-x64-0.38.3.tar.xz, does not compile myself, thanks.

**Comment by zadam** [comment]
Not sure what the issue is. However, besides the error log does the image upload still work?

Since in the code there's a fallback that if image optimization fails then the unoptimized image is used instead ...

**Comment by chncho** [comment]
Yes , it is still work with unoptimized image upload.

**Comment by popey456963** [comment]
> Trace: ERROR: JS Error: Uncaught error: Message: Uncaught Error: The module '/tmp/.org.chromium.Chromium.8hHnLM'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing

I'm curious if it was just a bad build.  If you try it on a more recent build does it work?
