### ISSUE TITLE
.40 Beta Recent Changes Error

### ISSUE THREAD

**Issue by joshcsullivan** [zadam/trilium#823]
I just installed .40 beta release (server version), once installed, I deleted a test note I had then clicked on Recent changes and received the following error:

`Error when calling GET search-note/MoYl9KBmpy2J: error - Internal Server Error`

Here is the backend log related error:

```
14:13:00.187 INFO  ERROR: Error executing transaction, executing rollback. Inner stack: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Note.getJsonContent (/home/josh/trilium-linux-x64-server/src/entities/note.js:113:21)
    at async searchFromNote (/home/josh/trilium-linux-x64-server/src/routes/api/search.js:36:18)
    at async /home/josh/trilium-linux-x64-server/src/routes/routes.js:89:32
    at async /home/josh/trilium-linux-x64-server/src/services/sql.js:206:19
Outside stack: Error
    at Object.transactional (/home/josh/trilium-linux-x64-server/src/services/sql.js:197:23)
    at /home/josh/trilium-linux-x64-server/src/routes/routes.js:88:38
    at /home/josh/trilium-linux-x64-server/node_modules/cls-hooked/context.js:118:13
    at Namespace.run (/home/josh/trilium-linux-x64-server/node_modules/cls-hooked/context.js:97:5)
    at Namespace.runAndReturn (/home/josh/trilium-linux-x64-server/node_modules/cls-hooked/context.js:117:8)
    at Object.init (/home/josh/trilium-linux-x64-server/src/services/cls.js:5:28)
    at /home/josh/trilium-linux-x64-server/src/routes/routes.js:83:38
    at Layer.handle [as handle_request] (/home/josh/trilium-linux-x64-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/josh/trilium-linux-x64-server/node_modules/express/lib/router/route.js:137:13)
    at csrf (/home/josh/trilium-linux-x64-server/node_modules/csurf/index.js:117:5) 
14:13:00.188 INFO  ERROR: get /api/search-note/:noteId threw exception: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Note.getJsonContent (/home/josh/trilium-linux-x64-server/src/entities/note.js:113:21)
    at async searchFromNote (/home/josh/trilium-linux-x64-server/src/routes/api/search.js:36:18)
    at async /home/josh/trilium-linux-x64-server/src/routes/routes.js:89:32
    at async /home/josh/trilium-linux-x64-server/src/services/sql.js:206:19 
14:13:00.203 INFO  ERROR: JS Error: Error when calling GET search-note/MoYl9KBmpy2J: error - Internal Server Error 
14:13:00.203 INFO  ERROR: JS Error: Uncaught error: Message: Uncaught Error: Error when calling GET search-note/MoYl9KBmpy2J: error - Internal Server Error - URL: https://XXX.XXX.XXX/javascripts/services/toast.js - Line: 89 - Column: 5 - Error object: {} 
```

Cheers,
Josh

**Comment by joshcsullivan** [comment]
Update: It seems to be if I delete a note, Trilium automatically selects the next note to view (makes sense), if I then click on recent changes, it gives that error.

Instead if I delete a note, let Trilium open the next note, then click on a separate note, then click on Recent changes, it does not give that error.

**Comment by zadam** [comment]
Hello, thank you for reporting this issue. Unfortunately I can't reproduce this - from the provided logs it seems that there is a note of "search" involved - I tried to play a bit with this but could not produce such error. 

If you search for "MoYl9KBmpy2J" (noteId of the problematic search note), do you get something? Wondering if this could be caused by the fact this note is already deleted ...

**Comment by joshcsullivan** [comment]
Unfortunately, I cannot find that note. It seems that on first logon or after a force refresh of the page, then clicking Recent Changes brings up that error. After that, clicking Recent changes doesn't give that error.

I've cleared the browser cache for the site, in case it was related to the browser, but that didn't fix it.

**Comment by joshcsullivan** [comment]
Error has finally stopped coming up, closing.
