### ISSUE TITLE
Error: Router not found for request /javascripts/setup.js

### ISSUE THREAD

**Issue by gshell** [zadam/trilium#966]
Hi,
I just tried the the 0.41.2 beta server version and am getting the following error when I navigate to the setup page
Generated sourceId=CSBre28WCsuj
App HTTP server starting up at port 8900
{
  "appVersion": "0.41.2-beta",
  "dbVersion": 158,
  "syncVersion": 14,
  "buildDate": "2020-04-13T10:30:11+02:00",
  "buildRevision": "87510fd72ba7ec9a8b83cd8a00dbe1d12b5e8a3f",
  "dataDirectory": "/home/mohammed/.local/share/trilium-data",
  "clipperProtocolVersion": "1.0"
}
DB not initialized, please visit setup page - http://[your-server-host]:8900 to see instructions on how to initialize Trilium.
Error: Router not found for request /javascripts/setup.js
    at /home/mohammed/trilium-linux-x64-server/src/app.js:85:17
    at Layer.handle [as handle_request] (/home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/index.js:317:13)
    at /home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/index.js:317:13)
    at /home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/index.js:335:12) {
  status: 404
}
Error: Router not found for request /javascripts/setup.js
    at /home/mohammed/trilium-linux-x64-server/src/app.js:85:17
    at Layer.handle [as handle_request] (/home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/index.js:317:13)
    at /home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/index.js:335:12)
    at next (/home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/index.js:317:13)
    at /home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/mohammed/trilium-linux-x64-server/node_modules/express/lib/router/index.js:335:12) {
  status: 404

However when I went to the the last stable release (v0.40.7 ) is is working fine.

Thanks

**Comment by zadam** [comment]
Hello, thank you for reporting this issue, look like webpack related. I will fix that shortly.

Otherwise you can use either the latest stable 0.40.7 or the previous beta (0.41.1-beta).
