### ISSUE TITLE
[v0.41.6] TypeError: Argument 0 must be a string trilium at Promise.then.db.driver

### ISSUE THREAD

**Issue by rogatty** [zadam/trilium#992]
I upgraded Trilium from v0.40.7 to v0.41.6 on my Raspberry Pi using this script:
```
cd ~/git/trilium
git fetch --all --tags --prune
git checkout tags/v0.41.6
mv package.json package.json.backup
cat package.json.backup | grep -v electron > package.json
docker build .

“Successfully built 5495663b0f77”

docker tag 5495663b0f77 zadam/trilium:0.41.6
cd ~
sed -i 's/zadam\/trilium:0.40.7/zadam\/trilium:0.41.6/' docker-compose.yaml
docker-compose up trilium
```

And got the following error when container tried to start, restarting it doesn't help:
```
07:35:50.285 INFO  Generated sourceId=TzsVtAtO3QEj
07:35:50.291 INFO  Argument 0 must be a string
{}
TypeError: Argument 0 must be a string
    at Promise.then.db.driver (/usr/src/app/node_modules/sqlite/main.js:484:16)
    at new Promise (<anonymous>)
    at Database.db.open (/usr/src/app/node_modules/sqlite/main.js:474:10)
    at createConnection (/usr/src/app/src/services/sql_init.js:17:25)
    at /usr/src/app/src/services/sql_init.js:25:22
    at new Promise (<anonymous>)
    at Object.<anonymous> (/usr/src/app/src/services/sql_init.js:23:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
```

I used the same script previously and never had issues so I suspect it's not the problem here. Did something change in sqlite configuration in v0.41?

**Comment by zadam** [comment]
Actually yes, there was a (node) sqlite major version update in 0.41 ...

I will check what might have caused this ...

**Comment by zadam** [comment]
Hi, I think your script is missing `npm install` so the new dependency is simply not pulled ...

**Comment by rogatty** [comment]
There is `npm install` in the `Dockerfile`, so it should be ran during `docker build .` 🤔 

Anyway, I used `./bin/build-docker.sh` instead and it worked as expected. Maybe there was some issue during sqlite compilation that I missed. Thanks and sorry for wasting your time!
